### ISSUE TITLE
Contar con la documentación actualizada de todas las herramientas(comentarios (#), lógica (if, for each, etc), funciones)

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#10]
Actualizar la documentación en el sitio de FRIDA acerca de la implementación de lógica en los scripts

**Comment by Johhnn117** [comment]
Hola Heber,

La documentación la pueden encontrar en Teams

[https://teams.microsoft.com/l/file/DFB92226-D943-45EC-B708-1401CB0B2FDC?tenantId=94b74aad-5485-4f8d-9d06-53603c463791&fileType=pdf&objectUrl=https%3A%2F%2Fhebmex1.sharepoint.com%2Fsites%2FFRIDA-HEBTesting%2FShared%20Documents%2FGeneral%2FLogical%20Instructions%20PDF.pdf&baseUrl=https%3A%2F%2Fhebmex1.sharepoint.com%2Fsites%2FFRIDA-HEBTesting&serviceName=teams&threadId=19:a848376040d0447cbdf36c70b6c15305@thread.skype&groupId=1a6c07df-6fa1-459c-890d-c1bf130d2227](url)

Saludos

**Comment by gantonioid** [comment]
Hay que revisar si tiene acceso, mejor incluirla como funciones de MixedReader (con PDF)

**Comment by heber-solis** [comment]
si, si tenemos acceso, gracias
