### ISSUE TITLE
timeout en instrucción elementExists no respeta tiempo de espera

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#101]
tiene espera de 80 y termina en 30 segundos mas o menos, tengo una duda, la página está muy lenta, está cargando y hay un punto donde parece que va a "cambiar de pantalla" esto influye en que no se espere el tiempo estipulado?

15:08:10 - Web2 ElementExists in id="searchBarcode" save as "busqueda" timeout= 80000: Running
21/08/2020 03:08:42 p. m. - element existes
21/08/2020 15:08:42 - Se agrego una nueva variable : 
Var Name : busqueda
Value : false
21/08/2020 15:08:42 - Web2 ElementExists in id="searchBarcode" save as "busqueda" timeout= 80000 : Success

**Comment by RickProductivity** [comment]
@heber-solis ya lo estás revisando con Alguien?

**Comment by heber-solis** [comment]
@RickProductivity hola, no aún no he tenido respuesta, el código es muy simple, sin embargo la página es muy lenta y al paso de 30 segundos me dice que no existe

```
  #Web2 GoTo "http://sra<<tienda>>02/HEB.Star/"
Web2 GoTo "https://sca293202/HEB.Star/"
    #Ingresa usuario
    Web2 Type "testinguser1" in selector="main #UserName"
    #Ingresa Password
    Web2 Type "Jkl12345." in selector="main #Password"
    Web2 Key "Enter"
    Web2 Navigation
	Web2 Sleep 3000
Web2 Navigation
    Web2 ElementExists in id="searchBarcode" save as "busqueda" timeout= 80000
```

**Comment by rubenleal** [comment]
Equipo, ¿tenemos fecha planeada para solucionar/liberar este issue?, gracias

**Comment by gantonioid** [comment]
@rubenleal @heber-solis Adjunto mis resultados:

40 segundos de timeout
```
Web2 GoTo "https://www.google.com"
Web2 Navigation
Web2 ElementExists in id="idquenoexiste" save as "exists" timeout = 40000
```
![image](https://user-images.githubusercontent.com/9600868/93133410-cba2da00-f69c-11ea-81a4-7272094c42b6.png)

80 segundos de timeout
```
Web2 GoTo "https://www.google.com"
Web2 Navigation
Web2 ElementExists in id="idquenoexiste" save as "exists" timeout = 80000
```
![image](https://user-images.githubusercontent.com/9600868/93133665-32c08e80-f69d-11ea-9605-ff4d720b396a.png)


Como ves, el timeout parece estarse respetando, entonces asegúrate de tener el browpet actualizado e intentar de nuevo.

**Comment by heber-solis** [comment]
de acuerdo es que si tenía duda de que fuera error mio porque la página está muy lenta, y ni con 2 navigation y el elementexists con 80 funciona

```
Web2 Navigation: Running
14/09/2020 03:27:20 p. m. - DONE
14/09/2020 15:27:20 - Web2 Navigation : Success
14/09/2020 15:27:20 - Web2 Sleep 3000: Running
14/09/2020 03:27:23 p. m. - Slept correctly
14/09/2020 15:27:23 - Web2 Sleep 3000 : Success
14/09/2020 15:27:23 - Web2 Navigation: Running
14/09/2020 03:27:27 p. m. - DONE
14/09/2020 15:27:27 - Web2 Navigation : Success
14/09/2020 15:27:27 - Web2 ElementExists in id="searchBarcode" save as "busqueda" timeout= 80000: Running
14/09/2020 03:27:40 p. m. - element existes
14/09/2020 15:27:40 - Se agrego una nueva variable : 
Var Name : busqueda
Value : false
```
cuando parece que ya va a cargar la página como que pasa a la siguiente tienda, no sé si tengas algún consejo para esto? pensé que con los 2 navigation iba a quedar pero no, adjunto video de ejecución

[STAR Login_140920152635.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/5220882/STAR.Login_140920152635.zip)

**Comment by gantonioid** [comment]
No se ve error en tu script.

Sin embargo, tu log evidencia que no tienes browpet actualizado, te puedes dar cuenta por el typo en el mensaje que se arroja `element existes`
En el mío si te fijas dice `element exists`. Debe de ser que además de corregir la ortografía, tiene corregido el comportamiento del timeout.
A ti te responde en 13 segundos cuando indicaste una espera de 80. Como te mostré en mi comentario anterior, la versión actual de browpet es capaz de respetar el tiempo que se haya puesto en la instrucción.

Puedes hacer la actualización?

**Comment by heber-solis** [comment]
he actualizado varias veces, no sé por que actualizo y a la vuelta de uno que otro día  me pide actualizar de nuevo. Hasta bajé una instancia limpia, actualicé y me está haciendo lo mismo, lo mismo pasa en las máquinas que tienen los procesos calendarizados

**Comment by heber-solis** [comment]
16:42:09 - Web2 ElementExists in id="searchBarcode" save as "busqueda" timeout= 80000: Running
14/09/2020 04:42:36 p. m. - element exists
14/09/2020 16:42:36 - Se agrego una nueva variable : 
Var Name : busqueda
Value : false
ya actualicé y el comportamiento es el mismo, se esperó 27 segundos

**Comment by gantonioid** [comment]
Se comprobó en vivo el buen funcionamiento de la instrucción `Web2 ElementExists`

Queda por parte de @heber-solis diseñar alguna estructura de script que se adapte a la necesidad, ya que observamos que suceden algunos redireccionamientos después del login en el sistema.

Se propuso la posibilidad de implementar un Sleep de 2 minutos, o for 10 times/while que nos ayude a revisar si ya estamos en la página deseada

Sleep
```
Web2 Sleep 120000 # 2 minutos
Web2 ElementExists
```

While (si lo tienes en tu versión)
```
DefineVariable type string as notYet with the value true
while(notYet == true) {
    Web2 Sleep 20000
    Web2 Evaluate frame=main 'window.location.href'
    if ("<<<web2Output>>>" == "laURL_que_quieres")
        DefineVariable type string as notYet with the value false
    end
}
Web2 ElementExists
```
For X times
```
DefineVariable type string as notYet with the value true
for 10 times {
    Web2 Sleep 20000
    Web2 Evaluate frame=main 'window.location.href'
    if ("<<<web2Output>>>" == "laURL_que_quieres")
        break
    end
}
Web2 ElementExists
```

**Comment by heber-solis** [comment]
gracias Antonio, hice todos los casos que mencionas y el Sleep de 2 minutos y el script falla, creo que es lo que comentabas una vez que al hacer el cambio de pantalla el dom se invalida y en el sleep pasa esto
```
15/09/2020 10:08:42 - Web2 Navigation : Success
15/09/2020 10:08:42 - Web2 Sleep 120000: Running
15/09/2020 10:10:22 a. m. - A task was canceled.
15/09/2020 10:10:22 - Web2 Sleep 120000 : Error
```

**Comment by gantonioid** [comment]
Prueba un Titanium Sleep, es lo mismo pero lo maneja Turing directamente sin depender del navegador

**Comment by heber-solis** [comment]
si funcinó con el titanium sleep muchas gracias!
