### ISSUE TITLE
Cognitive testing no sube scripts adicionales (sql, powershell, batch)

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#103]
Al momento de hacer clic en save script version, se sube al repositorio la version actual del script, pero este se sube sin los scripts adicionales, necesarios para su funcionamiento y que a petición del cliente, la ausencia de estos afectan al correcto versionamiento de los scripts
![image](https://user-images.githubusercontent.com/54727278/94865876-f6629180-0403-11eb-9edd-40dd6c8cbb13.png)
![image](https://user-images.githubusercontent.com/54727278/94865909-02e6ea00-0404-11eb-9401-bb4482eabd24.png)

**Comment by jorgebibarra** [comment]
@heber-solis ya probó el cambio
