### ISSUE TITLE
Titanium GetLines no obtiene toda la información

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#105]
estamos usando la funcion de Titanium GetAllLines y lo vaciamos a un archivo de texto, pero notamos que hay información que no obtiene, hay forma de hacer que sea mas certero?

**Comment by gantonioid** [comment]
Siendo un OCR, hay un margen de error. En este caso, se han cambiado algunas letras por la similitud con otros caracteres... pero en general obtuvo todo.
Cuál es la falla en tu caso? nos puedes dar detalles?

![capture](https://user-images.githubusercontent.com/9600868/95871974-e7e57580-0d33-11eb-877b-517e1a152e02.png)

```
Var Name : lines
Value : System.Collections.Generic.List`1[System.String]
10/13/2020 9:06:21 AM - [0] : o
[1] : Titanium GetLines no obtiene to: X +
[2] : C github.com/FridaSupport/CognitiveTestingMX/issues/105
[3] : Q)) ENG
[4] : Search or jump to...
[5] : FridaSupport/ CognitiveTestingMX
[6] : Pull requests
[7] : @ Actions
[8] : Issues
[9] : Marketplace
[10] : Projects
[11] : Explore
[12] : Wiki
[13] : 4
[14] : < > Code O Issues 4
[15] : Pull requests
[16] : C) Security
[17] : Insights
[18] : @ Unwatch
[19] : Assignees
[20] : Star
[21] : Edit
[22] : Fork
[23] : New issue
[24] : Titanium GetLines no obtiene toda la informaci6n
[25] : 105
[26] : O Open
[27] : heber-solis opened this issue 8 days ago • 0 comments
[28] : heber-solis commented 8 days ago
[29] : estamos usando la funcion de Titanium GetAllLines y lo vaciamos a un archivo de texto, pero notamos que hay informaciön que no
[30] : obtiene, hay forma de hacer que sea mas certero?
[31] : Write
[32] : Preview
[33] : Leave a comment
[34] : Attach files by dragging & dropping, selecting or pasting them.
[35] : p Type here to search
[36] : No one—assign yourself
[37] : Labels
[38] : None yet
[39] : Projects
[40] : None yet
[41] : Milestone
[42] : No milestone
[43] : Linked pull requests
[44] : F
[45] : 906 AM
[46] : 10/13/2020
```

**Comment by heber-solis** [comment]
Hola, buen día, estamos intentando obtener el texto de esta imagen 
![prueba1](https://user-images.githubusercontent.com/54727278/95872875-f2ecd580-0d34-11eb-8345-a8c75f520d3e.jpg)
pero falla al obtener ciertos datos, la imagen viene de un pdf, entonces nos preguntabamos si podría haber algo que pudieramos hacer para ayudar a que la extracción sea mas certera

**Comment by gantonioid** [comment]
Sí, entiendo el caso de uso... extraer el texto de la imagen... pero qué es lo que se logra extraer? o qué es lo que hace falta? qué sección de la imagen te interesa más? para enfocarnos ahí.
Veo que la imagen no es excelente, pero se ve bastante bien. Tal vez las letras están muy gruesas y pudieran confundirse.

**Comment by andresCruzF** [comment]
Hola @rubenleal y @heber-solis ,

Veo que las imágenes son en blanco y negro por lo que podríamos aplicar algoritmos para reducir el ruido en la imagen y aplicar filtros de detección de bordes para tratar de mejorar la calidad de la imagen , el día de hoy estaré haciendo un par de pruebas y les comento mis resultados. Creen que me puedan mandar 5 imágenes con las cuales pueda probar?

Saludos , quedo al pendiente

**Comment by heber-solis** [comment]
Hola Andrés, no sé si estas te sirva, es la misma imagen pero en diferentes formatos
[imagenes.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/5374445/imagenes.zip)
Saludos!

**Comment by rubenleal** [comment]
Hola @andresCruzF, el documento que recibe el negocio es un PDF originalmente, nosotros lo convertimos a imagen con Ghostscript, quizás un tipo diferente de formato de imagen podría servir. Comparto documento e imágenes ejemplo.

Aquí el PowerShell que utilizamos para converir de PDF a Imagen.
#Aplicación para convertir PDF a Imagen (https://www.ghostscript.com/doc/current/Use.htm)
$Command = "C:\Tools\ConvertPDFtoImage\gs951w64\bin\gswin64c.exe"
$Parms = " -dNOPAUSE -dBATCH -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -sDEVICE=png16m -r300  -sOutputFile=""C:\Borradores\Pic-%d.tif"" ""C:\Borradores\Original.pdf"""
#Separamos los parámetros
$Prms = $Parms.Split(" ")
#Ejecutamos el programa con el PDF para convertirlo texto
& "$Command" $Prms

[ImágenesEjemplo.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/5379726/ImagenesEjemplo.zip)

**Comment by gantonioid** [comment]
Es un PDF con texto o un PDF con la imagen como foto?
Pregunto porque podría entonces usarse alguna función como `GetAllText` o `ReadPDFasText` en vez de usar OCR

**Comment by heber-solis** [comment]
es un PDF con imágenes

**Comment by andresCruzF** [comment]
Hola ,

Les mando los resultados de las pruebas que hemos realizado , se intentaron varias soluciones entre las cuales se encuentra el **rescalamiento de la imagen intentando con 1900 , 2000 y 2100 pixeles** (se mantiene la proporción de la imagen) de igual forma **se aplico el filtro de gaussian blur** (https://en.wikipedia.org/wiki/Gaussian_blur) para tratar de reducir el ruido presente en la imagen, intentodo por ultimo aplicar **algoritmos de detección de bordes** con la finalidad de mejorar la calidad de la imagen antes de aplicar el modelo de OCR, adjunto los resultados de aplicar estas lógicas al igual que el archivo excel con los resultados 

**Nota** :
Las dimensiones actuales de la imagen son : 4956 x 6456
El modelo de Titanium de OCR actualmente implementado en Turing hace un rescalamiento de la imágenes a 1900 pixeles (Manteniendo su proporción) por lo que se valido si cambiando el tamaño de la imagen se pueden lograr mejores resultados. 

Actualmente estamos reconfigurando el modelo OCR para ver si podemos incrementar su precisión en la lectura de datos en formato de tabla.

![Laplace_Test1](https://user-images.githubusercontent.com/49708627/96179818-19f30500-0ef7-11eb-9849-da9b2621da5d.png)
[Laplace_Test1.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5387479/Laplace_Test1.txt)
![Normal_1900_Test1](https://user-images.githubusercontent.com/49708627/96179823-1b243200-0ef7-11eb-8459-86534cfb1c13.png)
[Normal_1900_Test1.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5387480/Normal_1900_Test1.txt)
![Normal_2000_Test1](https://user-images.githubusercontent.com/49708627/96179824-1b243200-0ef7-11eb-8987-3282e5997e96.png)
[Normal_2000_Test1.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5387481/Normal_2000_Test1.txt)
![Normal_2100_Test1](https://user-images.githubusercontent.com/49708627/96179825-1bbcc880-0ef7-11eb-83f4-791bb74f4686.png)
[Normal_2100_Test1.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5387482/Normal_2100_Test1.txt)
![Normal_2200_Test1](https://user-images.githubusercontent.com/49708627/96179827-1c555f00-0ef7-11eb-8b26-b2da185912be.png)
[Normal_2200_Test1.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5387483/Normal_2200_Test1.txt)
![Normal_4000_Test1](https://user-images.githubusercontent.com/49708627/96179830-1c555f00-0ef7-11eb-8c17-bedffc24b26c.png)
[Normal_4000_Test1.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5387484/Normal_4000_Test1.txt)
![SmoothGaussian_Test1](https://user-images.githubusercontent.com/49708627/96179832-1cedf580-0ef7-11eb-82db-d8c858908aea.png)
[SmoothGaussian_Test1.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5387485/SmoothGaussian_Test1.txt)
[OCR Test.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/5387493/OCR.Test.xlsx)

**Comment by rubenleal** [comment]
Gracias por la actualización y el detalle Andrés, atentos al resultado final del esfuerzo que están realizando para mejorar el OCR.

**Comment by rubenleal** [comment]
Cómo andas @andresCruzF, ¿hay alguna novedad de esta función?

**Comment by rubenleal** [comment]
@andresCruzF , ¿han podido avanzar con este tema?, ¿se ve viable?

**Comment by gantonioid** [comment]
Se obtuvieron los resultados reportados por Andrés.
Además, una prueba con la nueva versión [preview] del OCR de Microsoft. Son los mismos resultados que con el API actual.
No conformes con eso, creamos un OCR local (dentro de Turing) utilizando tecnología diferente. 
[Titanium OCR_GetLines](https://frida-admin.web.app/Documentation/Readers/Titanium%20Reader/OCR_GetLines)
```
d
Certificate of Analysis
H-E-B, LP
HEB Milk And Culture Plant
47140 North Pan Am Expressway
San Antonio, Texas 78218
Phone (210) 938-5283
Fax (210) 938-5522
Product: LECHE SEMIDESCREMADA PASTEURIZADA ADICIONADA
CON VITAMINA D Y A
HCF 2% REDUCED MILK 128 oz
[Manufacturing Date : SuN Jul)20
Code & Exp. Date: ISAuglANO)20.
LOTE: 32
[TEME UPCE AAa3T9114A122008855
The Product is obtained from Grade A milk that has been legally processed and is free of any
objectionable odors or flavors. The product meets the standards as established in the Code of.
Federal Regulations (GFR). U.S. Title 21, part 131.110.
Physical / Chemical STANDARD ACTUAL RESULTS
Evaluation
Miktat [Maximum _1.82% 1.80%
imum 1.78%
(Solids Not Fat (SNF) Minimum _>8.25% 5.09%
[Appearance [Natural Miik White to Pale TYPICAL
[Cream Cotor
Microbiological STANDARD ACTUAL RESULTS
Specifications
(Conitorm |< 10cFUi m <10 CFU/ml
```

Conclusión: tendrían que ver ustedes si les es útil. La tecnología OCR depende de la calidad de la imagen (tamaño y dpi de resolución), fuente, negritas, etc. Ambas tecnologías utilizadas son consideradas TOP, por tener detrás a Microsoft y Google.

**Comment by rubenleal** [comment]
Me puedes enviar la versión para probar la función, ahorita obtengo:
06/12/2020 07:22:41 p. m. - Process Name: Academia FRIDA 2
06/12/2020 07:22:41 p. m. - Process ID: 1833314037
06/12/2020 07:22:41 p. m. - Turing Version: 20201202T1651
06/12/2020 07:22:41 p. m. - Hostname: MXLADM_2SYF9H2
06/12/2020 07:22:41 p. m. - Execution started: No Headless
06/12/2020 07:22:41 p. m. - Titanium OCR_GetLines file={C:\Users\L041409\Downloads\OCumplimiento\pag1.png} and save as {lines} : Running
**`06/12/2020 07:22:41 p. m. - Error : Could not load file or assembly 'Tesseract, Version=4.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`**
06/12/2020 07:22:41 p. m. - Titanium OCR_GetLines file={C:\Users\L041409\Downloads\OCumplimiento\pag1.png} and save as {lines} : Error
06/12/2020 07:22:41 p. m. - Execution ended
