### ISSUE TITLE
Función text to column en excel

### ISSUE THREAD

**Issue by RocioPina** [FridaSupport/CognitiveTestingMX#106]
Buen día, podrían implementar la función text to column para excel, ya que en ocasiones los archivos del usuario tienen formato texto y aunque apliquemos el format cell no los cambia, en ocasiones afecta en las formulas por ejemplo en si un número esta en formato texto no toma los valores para una suma o si las fechas se encuentran en texto no se pueden modificar hasta cambiarle en text to column el formato ya sea general o fecha.

**Comment by gantonioid** [comment]
Por favor danos un ejemplo del problema que tienes, screenshots, logs, o incluso el archivo que estás intentando procesar.

Ayúdanos con toda la información para primero entender, y luego poder pensar en una solución.

**Comment by RocioPina** [comment]
[prueba text to column.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/5387558/prueba.text.to.column.xlsx)

ahi puse en excel a que me referia con cuando es en texto y no toma las formulas o en fechas no filtra aquellas que sea formato texto y pues el texto to column nos ayuda a pasarlo a general, formato date, etc, en frida hay maneras de darle la vuelta en unas cosas pero a veces puede ser muy tardado

**Comment by ErlikC** [comment]
No te resuelve el uso de las instrucciones?
https://frida-admin-qa.web.app/Documentation/Readers/Excel%20Reader/LoadCSV
De ahi en especifico, esta instrucción que tiene funcionamiento como text to column.
LoadCSV "<filepath>" separated_by delimiter as <workbookKey> with format [Text,General,YMD,MDY,DMY]

https://frida-admin-qa.web.app/Documentation/Readers/Excel%20Reader/ApplyFormatFullColumn
https://frida-admin-qa.web.app/Documentation/Readers/Excel%20Reader/ApplyFormat
https://frida-admin-qa.web.app/Documentation/Readers/Excel%20Reader/Write

**Comment by ErlikC** [comment]
Se creó la función [TextToColumns](https://frida-admin-qa.web.app/Documentation/Readers/Excel%20Reader/TextToColumns ). Si gustas te puedo asignar una versión de Turing con ella.

**Comment by RocioPina** [comment]
si por favor!, igual ya esta en la documentación un ejemplo de como usar la función?

**Comment by ErlikC** [comment]
Vale, cual es el correo con el que estas registrada?
La documentación la puedes ver dando click en el link del comentario anterior.

**Comment by RocioPina** [comment]
rocio.pina@softtek.com , muchas gracias!

**Comment by ErlikC** [comment]
Listo, te asigné la versión 20201208T0029
