### ISSUE TITLE
Desactivar la comprobación de errores

### ISSUE THREAD

**Issue by marlen868** [FridaSupport/CognitiveTestingMX#107]
Buen día, hay una situación con la comprobación de errores para el excel , ya que en varias ocasiones  en los archivos de excel del usuario vienen comprobación de errores en los campos  nos causa un conflicto con las formulas de búsqueda de información porque no toma lo valores correctos al no poder distinguir el dato que trae la celda nos pone datos erróneos o luego nos devuelve un falso al no poder encontrar lo que uno utilizar para esto quisiera si pueden implementar algo que pueda desactivar la comprobación de errores.

**Comment by gantonioid** [comment]
Por favor danos un ejemplo del error o conflicto que mencionas. Cómo se hace (a mano) la desactivación de comprobación de errores.

Ayúdanos con todo el contexto para entender y poder pensar en una solución.

**Comment by marlen868** [comment]
Existe una función que es de C# que la desactiva comprobación de errores:
excel.ErrorCheckingOptions.NumberAsText = false; // este funciona para desactivar el error que aparece en excel donde un numero es texto.
Manual seria entrando:
 Pestaña Archivo.
En Ayuda, haga clic en Opciones .
En el cuadro de diálogo Opciones de Excel, haga clic en la categoría Fórmulas.
En Reglas de verificación de Excel, desactive la casilla Números con formato de texto o precedidos por un apóstrofo .
Haga clic en Aceptar.

**Comment by gantonioid** [comment]
Gracias por el código... A qué usuario(s) les mando la actualización?

**Comment by marlen868** [comment]
los usuarios es:
marlen.chavez@softtek.com 
rocio.pina@softtek.com

**Comment by gantonioid** [comment]
Han comprobado el funcionamiento? podemos cerrar el ticket?

**Comment by marlen868** [comment]
No, probado como puedo probar el funcionamiento?

**Comment by gantonioid** [comment]
En tu script, aplica la instrucción `SetErrorChecking`

`SetErrorChecking option={NumberAsText} value={false}`

https://frida-admin.web.app/Documentation/Readers/Excel%20Reader/SetErrorChecking

**Comment by marlen868** [comment]
Buen día, a la instrucción me mando un Error a la hora de ejecutarlo 

22/10/2020 10:00:26 a. m. - Excel SetErrorChecking option={NumberAsText} value={false} : Running
22/10/2020 10:00:26 a. m. - Error Instruction seterrorchecking wasn't found
22/10/2020 10:00:26 a. m. - Error Instruction seterrorchecking wasn't found
22/10/2020 10:00:26 a. m. - Excel SetErrorChecking option={NumberAsText} value={false} : Error
22/10/2020 10:00:27 a. m. - Execution ended
esto es lo que me manda el log de errores

**Comment by gantonioid** [comment]
Aceptaste la actualización? Hay que cerrar y abrir Turing, ahí te va a ofrecer la nueva versión si deseas actualizar.

> Gracias por el código... A qué usuario(s) les mando la actualización?



> los usuarios es:
> [marlen.chavez@softtek.com](mailto:marlen.chavez@softtek.com)
> [rocio.pina@softtek.com](mailto:rocio.pina@softtek.com)

**Comment by marlen868** [comment]
Buen día, instale la actualización pero me sigue mando el mismo error que te compartí.

**Comment by marlen868** [comment]
verifique esta correctamente la actualización esta funcionando bien,gracias
