### ISSUE TITLE
implementación de format painter en excel 

### ISSUE THREAD

**Issue by RocioPina** [FridaSupport/CognitiveTestingMX#108]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
El usuario solicito que en al momento de agregar una columna en una tabla de ellos quieren el mismo formato para su encabezado la cual no sabemos como vendrá ese formato, entonces ese format painter nos ayudaría a copiar el formato de una celda a otra sin necesidad de estar adivinando sus formatos 

**Describe la idea o solución ideal**
que se pudiera copiar el formato que tiene de celda a celda y de columna a columna 

![image](https://user-images.githubusercontent.com/65791721/96196711-b1ffe700-0f15-11eb-8838-17f16bea2c0a.png)

**Comment by gantonioid** [comment]
La instrucción [Excel CopyRangeFormat](https://frida-admin.web.app/Documentation/Readers/Excelium/CopyRangeFormat) no te sirve? por qué?

**Comment by gantonioid** [comment]
![image](https://user-images.githubusercontent.com/9600868/96469828-42c71300-11f3-11eb-9f44-7325364b7858.png)

```
##La tabla ya existía, vamos a poner un header nuevo
Excel Write "Nuevo Header" in hoja cell E2
##Ahora copiar el formato
Excel CopyRangeFormat from sheet hoja with range D2 to sheet hoja in the range E2
```
