### ISSUE TITLE
[BUG][Cognitive Testing]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#109]
**Describe the bug**
Tenemos un script que barre todas las apps y suites de cognitive para hacer el respaldo en git, pero hay algunos donde indica que si se guardó en git o que simplemente se queda trabado y solo indica que está cargando

**To Reproduce**
pueden correr el script con el id 730535900 o estos son algunos de los que nos causan el error
Comercial > Elvis, GS1, Planogramas
Finanzas > Cuentas por pagar> Complemento de pago1*,Opinion de cumplimiento correo*,cumplimiento valida*, Pago de agua visor*,ProdAplicacionesdePagosdeCuentasporCobrarenPSARconAplicacion*
Listeners > Mantenimiento Sat> Chatbot >

**Expected behavior**
Guardar el script en git

**Screenshots**
Screenshots o video del problema
![image](https://user-images.githubusercontent.com/54727278/96738388-45a53d80-1384-11eb-9e1b-fc98079c93af.png)

**Desktop (please complete the following information):**
 - Version de Turing 20190402T1259

**Additional context**
Máquina física

**Comment by jorgebibarra** [comment]
Puedes revisar, ya quedó corregido

**Comment by heber-solis** [comment]
buen día, el día de ayer se ejecutó el proceso y el problema volvió a pasar

**Comment by rubenleal** [comment]
@jorgebibarra, @gantonioid, se puede reabrir el ticket o se debe dar de alta uno nuevo en base al comentario de Heber?

**Comment by RickProductivity** [comment]
@jorgebibarra podris darle una revisada o buscar a @heber-solis 
Gracias a ambos.

**Comment by jorgebibarra** [comment]
Revisé el día de ayer con la app de perecederos que me comentó Heber que fallaba y todo funciona correctamente. Quedo a la espera de que vuelvan a probar.

**Comment by jorgebibarra** [comment]
Ya revisé, no es error de Cognitive. 
Al momento de crear un proceso por Cognitive siempre se valida que no puedan tener caracteres especiales.
Los procesos que involucraban el fallo tenían acentos y otros caracteres especiales. 
Github tampoco permite acentos entonces por eso fallaba, por el nombre de los procesos.
