### ISSUE TITLE
Navegador se abre con 2 pestañas

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#11]
Al ejecutar un script, chromium se abre con 2 pestañas

**Comment by gantonioid** [comment]
Esto es el _expected beavior_
Por qué es un issue? a ver si lo podemos resolver pero primero entendiendo el problema.

**Comment by heber-solis** [comment]
es mas como una sugerencia, ya que en versiones pasadas no pasaba esto

**Comment by gantonioid** [comment]
Pero no afecta la ejecución o sí?

**Comment by heber-solis** [comment]
de momento no
