### ISSUE TITLE
varios filtros en varias columnas al mismo tiempo[Mejora]

### ISSUE THREAD

**Issue by RocioPina** [FridaSupport/CognitiveTestingMX#110]
no se si ya exista esa función pero en las líneas que hay de aplicar filtro solo e podido aplicar un filtro a la vez, pero busco una instrucción de que pueda aplicar filtros en varias columnas al mismo tiempo porque es mas sencillo copiar información si solo se deja la que se ocupa, actualmente como le doy la vuelta es aplicar filtro por filtro y quita luego tiempo.

**Comment by gantonioid** [comment]
En tu script, aplicar la instrucción `SetErrorChecking`

`Excel SetErrorChecking option={NumberAsText} value={false}`

https://frida-admin.web.app/Documentation/Readers/Excel%20Reader/SetErrorChecking

**Comment by gantonioid** [comment]
Se puede hacer lo que necesitas con instrucciones existentes de FRIDA? Tu propuesta consiste en tener una especie de _atajo_ para lograr lo mismo?

Tienes un caso particular en el que aplicarlo? Adjunta archivos, el script que usas. La intención es que si sigues el template, aumentamos la posibilidad de que se entienda el caso a la primera.
