### ISSUE TITLE
Función para comparar dos fechas

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#112]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Muchas veces requerimos comparar fechas para tomar decisiones, ej: 
- Eliminar los archivos con fecha de creación mayor a 7 días.
- Crear un reporte de estatus cada 14 días posteriores a su fecha de creación.
- Cancelar una factura si ya pasaron +36hrs.

**Describe la idea o solución ideal**
Función que devuelva la diferencia entre dos fechas/horas dadas:
DATEDIFF(interval, date1, date2) save as "Variable"
Interval:
- year, yyyy, yy = Year
- month, mm, m = month
- day, dy, y = Day
- week, ww, wk = Week
- weekday, dw, w = Weekday
- hour, hh = hour
- minute, mi, n = Minute
- second, ss, s = Second
- millisecond, ms = Millisecond

**Describe alternativas que hayas considerado**
Calcular en PowerShell, Excel, SQL, etc

**Additional context**
DATEDIFF(hour, '25/08/2020 07:00', '25/08/2020 14:45') save as "DiferenciaHoras"
DATEDIFF(month, '25/08/2020', '16/10/2020') save as "DiferenciaMeses"

**Comment by gantonioid** [comment]
Aquí hay que pensar en cómo manejar que estén en distintos formatos... me refiero a que **no hay que asumir** que están ambas en el mismo formato de mes-día  o día-mes.


Dónde lo necesitas @rubenleal ? me imagino que sería una función general de Mixed Reader, no particular para Excel, cierto?

**Comment by rubenleal** [comment]
Correcto Toño, sugiero definir un formato fijo de fecha, si las traemos diferentes igual se puede utilizar la función [ParseExactDate](http://automationplatform.azurewebsites.net/Readers/Tools/Mix%20Reader/ParseExactDate) para cambiarla al formato requerido.

Correcto la función la veo en Mix Reader, para evitar abrir otras herramientas (como Excel), ahorita particularmente queremos ir depurando archivos viejos, con fecha de creación mayor a 7 días, nos apoyaremos con la función [FileInfo CreationTime](http://automationplatform.azurewebsites.net/Readers/Tools/Mix%20Reader/FileInfo) .

**Comment by gantonioid** [comment]
Listo, la función es [DateDiff](https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/DateDiff)

Te he asignado la versión: `20201028T0016`

**Comment by RickProductivity** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rubenleal** [comment]
Gracias Toño! Funciona, pero detecté los siguientes temas...
Ejecuté los 2 ejemplos de la documentación tal cual:
28/10/2020 08:39:13 a. m. - DateDiff {years} {21-Nov-1991} vs {27-Oct-2020} format={dd-MMM-yyyy} and save as {age} : Running
28/10/2020 08:39:13 a. m. - Se agrego una nueva variable : 
Var Name : age
**Value : -28.95**
**_El valor lo regresa negativo, la operación sugiero se haga al revés (como en Excel/SQL), se debe restar a la segunda fecha la primera._**

28/10/2020 08:39:13 a. m. - DateDiff {years} {21-Nov-1991} vs {27-Oct-2020} format={dd-MMM-yyyy} and save as {age} : Success
28/10/2020 08:39:13 a. m. - DateDiff {hours} {20/09/2020} vs {28/09/2020} and save as {time} : Running
**28/10/2020 08:39:13 a. m. - Error : Specified argument was out of the range of valid values.
Parameter name: i**
**_Al parecer al no especificar el formato genera este error._**

28/10/2020 08:39:13 a. m. - DateDiff {hours} {20/09/2020} vs {28/09/2020} and save as {time} : Error
28/10/2020 08:39:14 a. m. - Execution ended

**Comment by gantonioid** [comment]
La operación que se hace es fecha1 - fecha2... matemáticamente, un resultado negativo es correcto.

Propongo mejor incorporar a la sintaxis la palabra **absolute**, para obtenerlo en positivo si la situación lo requiere. (Aunque bastaría con invertir el orden de las fechas)
10/28/2020 9:57:29 AM - DateDiff **absolute** {days} {21/Nov/2020} vs {27/Oct/2020} and save as {countdown} : Running
**_10/28/2020 9:57:35 AM - Se agrego una nueva variable : 
Var Name : countdown
Value : 25_**

Te mando una nueva actualización para que lo tengas disponible. Además, debería de solucionar el otro error

> **28/10/2020 08:39:13 a. m. - Error : Specified argument was out of the range of valid values. Parameter name: i**

**Comment by rubenleal** [comment]
Muchas gracias Toño! Confirmo el funcionamiento (se cierra).
Favor de enviar la versión a los siguientes usuarios:
eva@hebmex.com
practicanteBI@hebmex.com
ipuente@hebmex.com
rodolfo.pallares@softtek.com
heber.solis@softtek.com
