### ISSUE TITLE
No se encuentra input dentro de iframe (evaluate, xpath, selector)[BUG][Browpet]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#113]
**Describe the bug**
al intentar insertar un valor en un input, no se encuentra el elemento, intenté con selector/xpath/evaluate (js) encontré en internet que esto se debe al same-origin policy, el frame padre tiene una url diferente al iframe 

https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame

**To Reproduce**
pueden correr el script con el id 1471981345

**Expected behavior**
cambiar el valor de un input

**Screenshots**
si intento hacerlo manualmente me pasa esto
![image](https://user-images.githubusercontent.com/54727278/97627272-bf76a000-19f0-11eb-8300-52da02e214ca.png)
pero si intento lo mismo, despues de darle click al elemento o buscarlo en el developer tools de chrome, si funciona
![image](https://user-images.githubusercontent.com/54727278/97627356-e59c4000-19f0-11eb-9e60-a55e22d59ef2.png)

**Desktop (please complete the following information):**
 - Version de Turing 20200817T0715

**Additional context**
Máquina física

**Comment by gantonioid** [comment]
No pones qué instrucción estás usando. En el título dice Evaluate... es esa? o con Type, InsertValue?

Cuál es el error que arroja Browpet? los screenshots son de la consola de chrome, con cosas que has probado manualmente

**Comment by heber-solis** [comment]
pues he usado evaluate, intenté con frame de main y del 0 al 10  nada, e insertvalue(selector/xpath)
con insertvalue pues me arroja que no la encontró y con evaluate lo mismo que ves en las capturas, por eso no puse que error me arrojaba, supuse que se entendía, perdón.

**Comment by gantonioid** [comment]
Por lo que veo, el issue apunta a que en la página web se manejan OOPIF.
https://www.chromium.org/developers/design-documents/oop-iframes

Son iframes que se (de fondo) manejan en otro thread del browser, y todavía no hay soporte para automatizarlos.

Es por eso que, aunque las instrucciones son correctas, Browpet "no puede ver" esos elementos.

**Comment by gantonioid** [comment]
Tuve una idea...

Se puede navegar dentro de los campos de Azure DevOps con tabulaciones? Es decir... ya cargada la página, presionar TAB (N veces) hasta llegar al campo que quieres. De ser posible, entonces con Titanium podrías hacer Ctrl+C y luego escribir el valor que quieres.

Es una solución no ideal porque es Titanium en el Browser... pero tenemos el problema de los OOPIF.

**Comment by heber-solis** [comment]
Hola, si así terminé haciendolo, muchas gracias :)
