### ISSUE TITLE
[BUG][Mail] Descarga de correos con anexos .MSG marcan error

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#114]
**Describe the bug**
Lectura de correos para descargar anexos truena cuando los correos cuentan con anexos de correos de outlook (.msg)

**To Reproduce**
Mail ReadMailNew and get parameters "sender,date,attachment" from the folder "ErrorCorreoQR" that fulfills the filter "Recordatorio Opinión de Cumplimiento Fiscal (32-D CFF)" in the "subject" save data as "ListaCorreo" and attachments in "C:\Borradores" finally move it to "ErrorCorreoQR"

**Expected behavior**
Descargar el anexo en la carpeta indicada.

**Screenshots**
Correo con el anexo MSG (otro correo):
![image](https://user-images.githubusercontent.com/54807268/98732293-92b57780-2364-11eb-810d-dfda50820a6d.png)
Log:
![image](https://user-images.githubusercontent.com/54807268/98732143-5e41bb80-2364-11eb-8b9a-f86b782b443a.png)

**Desktop (please complete the following information):**
 - Turing Version: 20201028T1625

**Additional context**
- Máquina física
- Dado que todos los correos se descargan en cascada, si la función se detiene en 1, el resto ya no se procesan y se detiene todo el procesamiento.
- Sugiero que no se validen las extensiones de los archivos (si acaso se está haciendo), que se descarguen los anexos en la carpeta indicada.

**Comment by Johhnn117** [comment]
Buen día @rubenleal,

El error se debe a que el archivo .msg tiene el carácter ":" en el nombre y al querer guardarlo en disco ese carácter está prohibido. Te mandé la versión 20201117T0548 que corrige ese error.

Saludos.
