### ISSUE TITLE
[BUG][Excel] Readcolumn without nulls considera celdas vacías

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#115]
**Describe the bug**
Lecutra de columna de Excel indicando la línea de inicio lee renglones vacíos aún y con opción without nulls

**To Reproduce**
Excel ReadColumn from the worksheet {Abarrotes} with the column index {9} start_at {2} and save its value as {correos} visible without nulls

**Expected behavior**
Que las celdas vacías se eliminen de la lista que se genera del ReadColumn

**Screenshots**
Excel:
[Planogramas_Solicitud Versionamiento.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/5527023/Planogramas_Solicitud.Versionamiento.xlsx)

Código:
```
Excel LoadWBook "C:\Borradores\Planogramas_Solicitud Versionamiento.xlsx" as VersionarPlan
Excel LoadWSheet VersionarPlan sheet_index 1 as Abarrotes
Excel ReadColumn from the worksheet {Abarrotes} with the column index {9} start_at {2} and save its value as {correos} visible
##Instrucción con problema
Excel ReadColumn from the worksheet {Abarrotes} with the column index {9} start_at {2} and save its value as {correos} visible without nulls
##Instrucción que si omite los nulos (pero no permite indicar el reglón de inicio)
Excel ReadColumn from the worksheet Abarrotes with the column index {9}  and save its value as {correos}

```

Log:
![image](https://user-images.githubusercontent.com/54807268/98870001-36238c80-2438-11eb-9a54-c30134ff31f7.png)

**Desktop (please complete the following information):**
 - Version de Turing 20201028T1625

**Additional context**
Máquina virtual

**Comment by RickProductivity** [comment]
@ErlikC le puedes dar una revisada ? Gracias

**Comment by ErlikC** [comment]
Hola Ruben.
Ya hice la corrección, te mando la versión 20201113T0016.

**Comment by rubenleal** [comment]
Funcionando, muchas gracias @ErlikC 
![image](https://user-images.githubusercontent.com/54807268/99015511-ccc87a00-251a-11eb-9856-8eb7fb5647c6.png)
