### ISSUE TITLE
[Mejora]Actualizar CustomLocals exes automáticamente

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#117]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Actualmente los procesos que tienen un custom local se tienen que actualizar manualmente en cada una de las máquinas donde se corren los procesos productivos que tenemos
**Describe la idea o solución ideal**
Sería posible que se actualicen automáticamente al correr el proceso? como ocurre cuando se cambia el código del proceso?

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Actualmente lo que hacemos es ir a a la carpeta del process id, checar si el exe tiene la ultima versión, se va a edit instructions a ver si eso actualiza la versión, al ver que no, cerramos la ventana, borramos la carpeta del process id, damos clic en edit instrutions nuevamente y de esa forma es que se descarga la versión nueva

**Comment by gantonioid** [comment]
Al ser elementos ZIP, que pueden pesar mucho y volver lenta la ejecución por su tiempo de descarga y descompresión, el diseño fue:
1. Revisar si ya se tiene descargado el ZIP del CustomLocal
      si no se tiene: conseguirlo
      si ya lo tenemos, entonces continuar
2. Ejecutar el CustomLocal

Las versiones de CustomLocal las tienen que seguir administrando así ustedes. Sin embargo... podrías aplicar un _hack_:
tener una variable de entrada true/false que controle la ejecución de un if que elimine los archivos de CustomLocal para que entonces se descarguen los más actualizados. De esa manera, la administración la haría el mismo RPA.

**Comment by gantonioid** [comment]
@andresCruzF se te ocurre otra forma? existe ya algo nuevo?

**Comment by rubenleal** [comment]
Gracias @gantonioid ! 

Los procesos los ejecutamos desde Azure en diversos agentes, no sabemos en cuál máquina se ejecutará cada proceso, por lo que tendríamos que hacer el procedimiento manual en todas las máquinas para estar preparados y que los Devs nos notifiquen de cada actualización.

El hack que comentas, podría implementarse en el RPA, sin embargo también queda a expensas de que cada Dev lo recuerde, ¿ves viable que esa validación la haga el mismo Turing previo a cada ejecución (como lo hace con los scripts) para garantizar que siempre se ejecuta la última versión de todo el proceso? 

En caso de que no sea viable (veremos cómo mitigar el riesgo), podrías confirmarnos, cómo volver a descargar el CustomLocal, o ¿sería solo borrarlo y cuando el script lo mande llamar al no tenerlo lo descargaría?

**Comment by gantonioid** [comment]
> podrías confirmarnos, cómo volver a descargar el CustomLocal, o ¿sería solo borrarlo y cuando el script lo mande llamar al no tenerlo lo descargaría?

Es correcto, al no tenerlo se descargaría automáticamente. Pero tienen que borrar toda la carpeta del CustomLocal, no solo el archivo .exe

Estoy trabajando en una mejor solución para que Turing compare la versión que se tiene localmente vs. la que esté en la nube, para entonces decidir automáticamente si hacer (o no) la descarga. NO se comparará el contenido de los CustomLocal, sino las fechas de creación y modificación de archivos y carpetas.

**Comment by gantonioid** [comment]
@heber-solis @rubenleal a quién mando el update?

**Comment by heber-solis** [comment]
al usuario eva@hebmex.com por favor, muchas gracias!

**Comment by gantonioid** [comment]
Listo
