### ISSUE TITLE
[BUG][Excel DeleteRows]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#118]
**Describe the bug**
la instrucción DeleteRows Cond Contains Value 0 Column 2 from_sheet pruebasSheet no borra las rows, termina la ejecución bien pero no borra nada
**To Reproduce**
Excel LoadWBook "C:\Users\MX02689\Desktop\pruebas.xlsx" as pruebas
Excel LoadWSheet pruebas sheet_index 1 as pruebasSheet
Excel DeleteRows Cond Contains Value 0 Column 2 from_sheet pruebasSheet
Excel Save pruebas
SystemNotify Type "Notification" with message "<Message>"

**Expected behavior**
que se borraran las rows con el valor cero en la columna 2

**Screenshots**
Screenshots o video del problema
![image](https://user-images.githubusercontent.com/54727278/101059306-baf35900-3553-11eb-9b76-94592a77fd47.png)

**Desktop (please complete the following information):**
 - Version de Turing [20201202T1651]

**Additional context**
Máquina física

**Comment by ErlikC** [comment]
Hola
La sintaxis posible para DeleteRows es
```
DeleteRows <Colored|All> from_sheet <worksheetKey>
DeleteRows Cond <Contains|All> Value "<value>" Column <columnIndex> from_sheet <worksheetKey>
```
Como se puede ver, te faltaron las comillas. Y curiosamente lo que sucedió es que se tomo la sintaxis como si fuera la primera. 
DeleteRows **Cond Contains Value 0 Column 2** from_sheet pruebasSheet
Y al no identificar Colored o All, si no el "parametro inexistente"  **Cond Contains Value 0 Column 2**. Se salio sin borrar algo.

Aparte de este error de uso de la sintaxis en esa instrucción. Lo que noté en la [documentación](https://frida-admin-qa.web.app/Documentation/Readers/Excel%20Reader/DeleteRows) es que el valor leído lo espera como texto forzosamente. Si gustas puedo revisar de que modo evitar esto y que se puedan considerar números de igual forma.

**Comment by eva-ti** [comment]
Hola, si, tomé el ejemplo de la documentación  y me regresaba este error 
Error : Cannot implicitly convert type 'double' to 'string'
es por eso que opté por quitarle las comillas y al ver que no regresaba error pensé que estaba correcto, pero no hacía lo que esperaba.
Si pudieras ponerle ese fix estaría bien, gracias!

**Comment by ErlikC** [comment]
Listo te asigne una versión. La sintaxis que puede leer los numeros es esta. Para no afectar bots anteriores que puedan estar usando algun workarround con el comportamiento actual.
`DeleteRows Cond Contains Value "<value>" Column <columnIndex> start at <rowIndex> from_sheet <worksheetKey>`
