### ISSUE TITLE
[Mejora] Imprimir log al cancelarse pipeline en Azure

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#119]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Actualmente los procesos que se tienen en HEB se corren en Azure, tenemos implementado que los pipelines corran un máximo de tiempo (5 hrs) pero hay veces que los procesos se quedan ciclados, esperando que un elemento aparezca o un archivo se descargue o algo, y pues se transcurren las 5 horas y se cancela el proceso, pero entra otro que obtiene el log de la ejecución, esto para saber, en qué falló.
pero al obtener el log me muestra esto
![image](https://user-images.githubusercontent.com/54727278/101513356-b22ec880-3941-11eb-80f4-076951c3fec7.png)

**Describe la idea o solución ideal**
no sé si se pudiera obtener el log hasta el punto en que se canceló

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**

la versión de turing que tenemos en las máquinas es 20201202T1651

**Comment by gantonioid** [comment]
No sé qué es lo que hagan esos scripts, pero en el caso de un while... yo pondría una lógica de máximo 50 intentos... para salir del ciclo y que no se quede "atorado" tu proceso.

En otros casos, te podría funcionar usar la instrucción [CommitLog](https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/CommitLog) en lugares clave de la ejecución, para que tengas siempre un logro.txt resultado de la ejecución...

**Comment by heber-solis** [comment]
hola! es que esto es independiente del bot, por ejemplo aunque yo le ponga commit log, si se cierra de golpe turing, me aparece eso en el log 🤔

**Comment by ErlikC** [comment]
Ejecute una prueba y se ve que ya esta resuelto este problema.
Podemos cerrar el ticket?
![image](https://user-images.githubusercontent.com/60276982/117730915-cc035e80-b1b2-11eb-86d6-f5f6aa046c22.png)
...
![image](https://user-images.githubusercontent.com/60276982/117730928-d45b9980-b1b2-11eb-814a-10494b659eb6.png)
