### ISSUE TITLE
Cambiar propiedades de objetos web

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#12]
Por ejemplo quitar opción de solo lectura a campo de fecha para evitar tener que abrir el calendario e insertar la fecha directamente ya que hay datepicker que no permiten que se escriba la fecha en el campo

**Comment by gantonioid** [comment]
Recomiendo usar `Evaluate` para resolver esta necesidad
[http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/Evaluate](url)
