### ISSUE TITLE
[Mejora] multifiltro

### ISSUE THREAD

**Issue by RocioPina** [FridaSupport/CognitiveTestingMX#120]
Hola¿ hay alguna función donde haga un multifiltro pero diciendo que sean diferentes a varias cosas o un multifiltro donde elimine aquellos que filtraste? lo que pasa es que estoy haciendo un 10  filtros y eliminando pero se tarda demasiado, entonces pensé que hacer un filtro donde me quite esos parámetros pero no hay un ejemplo o no se si el multifiltro tenga esa función para que le diga que sea diferente a los 10 parámetros que le estoy dando.

**Comment by ErlikC** [comment]
Hola.
Puedes usar la instrucción [KeepRows](https://frida-admin.web.app/Documentation/Readers/Excel%20Reader/KeepRows).
Por ejemplo aquí 
`Excel KeepRows from Libro1 where 1 not ["cinco", "siete", "cuatro"]`
borra todo lo que diga "cinco", "siete", "cuatro" en la columna A. Si quieres el resultado contrario en lugar de "not" usa "in".

**Comment by RocioPina** [comment]
pero borra lo de la columna o los renglones  que contienen esa información

**Comment by RocioPina** [comment]
ya lo probé y funciono, muchas gracias , pero me surge otra duda cual función puedo usar para solo filtrar las que no quiero, esta vez no quiero eliminar solo  quiero que me haga el filtro

**Comment by ErlikC** [comment]
Hola Rocio,
generé la siguiente sintaxis de MultiFilter
`MultiFilter from <worksheetKey> start_at <headerRow> <find|except> with_criteria [<columnHeader 1>, <criteria 1>, <criteria 2>,..., criteria n; <columnHeader 2>, <criteria 1>, <criteria 2>,..., criteria n;...; <columnName n>, <criteria 1>, <criteria 2>,..., criteria n]`

Aqui la parte clave es que puedes usar "find" si quieres un filtro normal y "except" si quieres que funcione al revés, es decir que "muestre todo menos tal".
Te recomiendo revisar la documentacion de [Advanced Filters](https://support.microsoft.com/es-es/office/filtrar-por-criterios-avanzados-4c9222fe-8529-4cd7-a898-3f16abdff32b) de Excel, que es en lo que está basado.
Se pueden hacer filtros del estilo "(Ventas >6000 Y Ventas <6500) O (Ventas <500)" y luego con "except" esconder eso y mostrar lo que había quedado excluido del filtro.

**Comment by ErlikC** [comment]
No se detectaron errores.
Pongo evidencia de la prueba.
Tabla original
![image](https://user-images.githubusercontent.com/60276982/104050079-a423d000-51ab-11eb-8f90-c4b37052f16a.png)

Instrucción:
`Excel MultiFilter from Input start_at 1 except with_criteria [cuentas,30,100]`
Resultado:
![image](https://user-images.githubusercontent.com/60276982/104049891-5a3aea00-51ab-11eb-84aa-216c02df44df.png)

Instrucción:
`Excel MultiFilter from Input start_at 1 find with_criteria [cuentas,30,100]`
Resultado:
![image](https://user-images.githubusercontent.com/60276982/104050001-87879800-51ab-11eb-9b57-97f40165be1f.png)
