### ISSUE TITLE
[Mejora] Manejo de zoom en páginas web

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#121]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Tenemos aplicaciones que se ejecutan en Tienda a pantalla completa y con resoluciones que nuestras máquinas no se soportan por lo que la pantalla se ve incompleta

**Describe la idea o solución ideal**
Poder subir o bajar el zoom en las páginas web

**Describe alternativas que hayas considerado**
Titanium conmbinando Ctrl + Minus (-) pero no me funcionó me abre los marcadores de Chromium:
**Titanium Type ^(OEMMINUS)**

**Additional context**
- No estoy seguro pero al parecer Puppeter cuenta con la opción de manejar el zoom en la función [ViewPort](https://github.com/puppeteer/puppeteer/issues/4419)
- Las aplicaciones no son responsivas, al al utilizar el ViewPort nos quedamos igual, sin parte de la pantalla:
![image](https://user-images.githubusercontent.com/54807268/103251421-36bba800-493e-11eb-98ed-51a7fa156a9a.png)

**Comment by gantonioid** [comment]
ya probaste [Web2 Viewport](https://frida-admin.web.app/Documentation/Readers/Browpet%20Reader/Viewport) ?

**Comment by rubenleal** [comment]
Sí, pero no me hace el resize la aplicación, siento que le falta otro parámetro como en la liga compartida:
```
await page.setViewport({
  width: 1920,
  height: 1080,
  deviceScaleFactor: 0.75
});
```

**Comment by gantonioid** [comment]
@rubenleal hice la prueba como comentas con deviceScaleFactor, pero no hay cambio en el nivel de zoom

Te sugiero hacerlo con `Web2 Evaluate`, tomando como referencia el [post ](https://stackoverflow.com/questions/52796635/how-to-zoom-in-out-page-in-javascript)

1- Evaluate para insertarle el `style="zoom: 100%"` al tag body
```
Web2 Evaluate frame="main" `Page.style.zoom="100%"`
```
2- Declarar las funciones `zoomIn` y `zoomOut` para hacerlo en FRIDA, tienes que pasar el JS en una sola línea, cuidado con eso.
```js
function zoomIn()
{
  var Page = document.getElementsByTagName('body')[0];
  var zoom = parseInt(Page.style.zoom) + 10 +'%';
  Page.style.zoom = zoom;
  return false;
}

function zoomOut()
{
  var Page = document.getElementsByTagName('body')[0];
  var zoom = parseInt(Page.style.zoom) - 10 +'%';
  Page.style.zoom = zoom;
  return false;
}
```
3- Ejecutarlas según requieras
```
Web2 Evaluate frame="main" `zoomIn()`
Web2 Evaluate frame="main" `zoomOut()`
```

## Atajo
Puedes hacer directamente el `Page.style.zoom="<porcentaje>%"` si ya sabes cómo lo necesitas.
