### ISSUE TITLE
[BUG][FRIDA] Error al ejecutar algunos procesos tras actualizar versión

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#123]
**Describe the bug**
Tras actualizar a versión de Turing, al ejecutar ciertos procesos semuestra el siguiente error:
04/01/2021 06:47:39 p. m. - Turing was unable to connect to https://automation-1713b.firebaseio.com/, please check your internet connection and retry (Error Code 0xCFBSCA1)

**To Reproduce**
Ejecutar alguno de estos scripts directo en FRIDA:
987546334
722215620
325611844

**Expected behavior**
Ejecutar script

**Screenshots**
![image](https://user-images.githubusercontent.com/54807268/103594826-5d8a5900-4ebf-11eb-8c8f-7f81f8d10f02.png)

**Desktop (please complete the following information):**
 - Version de Turing **20201228T2219 No Funciona**
 - Version de Turing 20201202T1651 Si Funciona

**Additional context**
Máquinas virtuales y físicas

**Comment by ErlikC** [comment]
Hola, y si se revisó que tuviera acceso a esa URL?

**Comment by rubenleal** [comment]
Sí, ejecutamos el mismo script con una copia de la versión anterior de Turing en la misma máquina y si se ejecuta con la versión 20201202T1651 (hay acceso a la liga).

**Comment by ErlikC** [comment]
Quizá falte otro acceso. Puedes revisar si entra a estas URLs porfa
1 http://automationplatform.azurewebsites.net
2 https://automation-1713b.firebaseio.com
3 https://innotekfilestore.file.core.windows.net/
4 http://automationtools.azurewebsites.net
5 https://cognitive-server-softtek.azurewebsites.net
6 https://login.microsoftonline.com/

**Comment by RickProductivity** [comment]
Puedes enviarle el FRIDA Tester?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/103949210-88afbb00-5100-11eb-87b3-ecca8d594ed6.png)
buen día, se hizo la prueba en las 4 máquinas donde corre eva y todas marcaron OK

**Comment by rubenleal** [comment]
Tengo una versión nueva y sigue marcando lo mismo: **20210113T2244**

Me comenta @heber-solis que algo habían detectado relacionado a la cantidad de ejecuciones de esos procesos y es lo que genera conflicto en las nuevas versiones, ej. este proceso corre cada 30mins los 7 días de la semana:
![image](https://user-images.githubusercontent.com/54807268/104765771-0a21d180-572f-11eb-9d06-88546abab776.png)

@andresCruzF entiendo nos estás apoyando en el tema, llevamos 2 semanas sin actualizar versión y hay procesos que requieren de las funciones nuevas, _**¿cuánto tiempo estiman para la solución?**_ 

No entiendo cómo se relaciona el histórico de ejecuciones con las nuevas, pero si es necesario depurar historia, conversemos al respecto, gracias por su apoyo.

**Comment by andresCruzF** [comment]
Hola Buenas tardes @rubenleal 

Te confirmo que ya quedo resuelto el problema, Heber me hizo favor de validarlo y ya se envió la versión 20210115T0903 con la solución a los usuarios  "eva@hebmex.com" , "rleal@hebmex.com" y "heber.solis@softtek.com".

Quedo al pendiente para poder dar por solucionado este problema.

**Comment by rubenleal** [comment]
Funcionando, muchas gracias @andresCruzF!
![image](https://user-images.githubusercontent.com/54807268/104788484-ddce7b00-5757-11eb-9270-fc0fa3dddec9.png)
