### ISSUE TITLE
imprimir log de errores cuando se usa SSH o CustomLocal[Mejora]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#124]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Actualmente cuando se usa cualquiera de las 2 funciones, cuando sucede un error, no se puede ver en el log de la ejecución

**Describe la idea o solución ideal**
que el error que ocurra en un customlocal o en las instrucciones de SSH aparezca en el log

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Agrega información adicional, screenshots, videos, archivos de ejemplo para reproducir el inconveniente.

**Comment by ErlikC** [comment]
Hola, tengo una versión para mostrar los mensajes que arroja SSH si hay error.

**Comment by heber-solis** [comment]
me la mandas para checarla porfa?

**Comment by gantonioid** [comment]
Heber este se resolvió con el update de #125 ??

**Comment by heber-solis** [comment]
Correcto, para SSH si, CustomLocal no sé 🤔  otra cosa, por ejemplo si ocurre un error no se detiene la ejecución, sería posible implementar esto? 🤔

**Comment by gantonioid** [comment]
No estoy seguro de entender... Si hay un error dónde?

En el Custom? tienes que cacharlo tú y regresarlo a FRIDA con una variable o mensaje de error... así en el script se podría manejar un flujo alterno.

No sé cómo cacharíamos un error en SSH... @ErlikC

**Comment by gantonioid** [comment]
@ErlikC  qué falta para cerrar?
