### ISSUE TITLE
Instrucciones SSH no toman variables de frida[BUG][Excel/Browpet/Titanium]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#125]
**Describe the bug**
Al ejecutar esta instrucción 
psql -d yellowbox svc_copient -c "select incentiveid,startdate,enddate,lastupdate,incentivename FROM incentives" > /tmp/pruebaeva<<<tienda[0]>>>.txt 
no me crea el archivo de texto, sin la variable de frida esto funciona sin problemas

**To Reproduce**
SSH {SSHWarRoom.txt} host={<<<tienda[1]>>>} user={eva} pass={pass}

**Expected behavior**
Qué esperabas como resultado?
crear un archivo que tiene por nombre el valor sacado de un excel
**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20201228T2219

**Additional context**
Máquina física

**Comment by ErlikC** [comment]
Hola ya tengo la mejora. Ahora los scripts ya pueden tomar en cuenta variables de Turing.

**Comment by ErlikC** [comment]
Había adicionalmente problemas cuando habían comentarios en el script de SSH o líneas vacías. Ya hice el cambio. Te mando una versión que incluye también la solución de #124

**Comment by ErlikC** [comment]
Hola ya te envié la versión de Turing con esto que mencionaba en el comentario anterior.

**Comment by heber-solis** [comment]
muchas gracias Erlik!

**Comment by RickProductivity** [comment]
@heber-solis nos confirmas ? 
Gracias

**Comment by heber-solis** [comment]
hola, si ya funcionan las variables de frida en SSH 👍
