### ISSUE TITLE
[BUG][Mixed] Función TRIM marca error al pasarle un valor de un array

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#126]
**Describe the bug**
Función [TRIM](https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/Trim) marca error al pasarle un valor de un array

**To Reproduce**
**Funciona correctamente (variable plana):**
```
AddValueToList "lista" value " EDGAR NUÑEZ ORTEGA "
DefineVariable type "string" as "test" with the value " <<<lista[0]>>> "
Trim test

```
**Marca error (variable de array):**
```
AddValueToList "lista" value " EDGAR NUÑEZ ORTEGA "
Message <<<lista[0]>>>
Trim lista[0]
```

**Expected behavior**
Permitir hacer TRIM de variables que vienen desde un array, leemos un Excel por ejemplo y se traen muchos valores en el array

**Log**
```
14/01/2021 03:46:34 p. m. - DefineVariable type "string" as "test" with the value "  EDGAR NUÑEZ ORTEGA  " : Success
14/01/2021 03:46:34 p. m. - Trim test : Running
14/01/2021 03:46:34 p. m. - Se actualizo la variable : 
Var Name : test
Value : EDGAR NUÑEZ ORTEGA
14/01/2021 03:46:34 p. m. - Trim test : Success
14/01/2021 03:46:34 p. m. - Message  EDGAR NUÑEZ ORTEGA  : Running
14/01/2021 03:46:34 p. m. - Message  EDGAR NUÑEZ ORTEGA  : Success
14/01/2021 03:46:34 p. m. - Trim lista[0] : Running
14/01/2021 03:46:34 p. m. - Error , The variable lista[0] does not exist
14/01/2021 03:46:34 p. m. - Trim lista[0] : Error
```

**Desktop (please complete the following information):**
 - Version de Turing 20210113T2244

**Additional context**
Como workaround estamos pasando la variable del array a una plana para hacer el trim

**Comment by gantonioid** [comment]
Sí, solo soporta strings.

Estás pensando en aplicarle un trim a todos los valores de la lista? Podemos hacerlo más fácil si creamos una instrucción que aplique un trim a todos los elementos. ¿Cómo ves?

**Comment by gantonioid** [comment]
Te mandé la `v.20210126T1657` con esta solución


> Podemos hacerlo más fácil si creamos una instrucción que aplique un trim a todos los elementos.

**Comment by gantonioid** [comment]
@heber-solis tienes chance de probar esto? te paso versión para cerrar el ticket

**Comment by heber-solis** [comment]
si claro 👍

**Comment by heber-solis** [comment]
1/26/2021 5:41:51 PM - TrimList lista : Running
1/26/2021 5:41:51 PM - Var Name : lista
Value : 
[0] : EDGAR NUÑEZ ORTEGA

1/26/2021 5:41:51 PM - TrimList lista : Success
1/26/2021 5:41:51 PM - Execution ended

si funciona

**Comment by rubenleal** [comment]
Funcionando, gracias!
![image](https://user-images.githubusercontent.com/54807268/105922614-95894580-6000-11eb-8e5c-498271ad052b.png)
