### ISSUE TITLE
[BUG][No reconoce valores de passwordvault]

### ISSUE THREAD

**Issue by practicanterpa** [FridaSupport/CognitiveTestingMX#127]
**Describe the bug**
Se dan de alta las variables con valor en el passwordvault pero al momento de ejecutar los scripts no trae el valor asignado a la variable, sucede tanto para ingresar texto como para tomar contraseña y conectarse a un correo 

**To Reproduce**
```
Mail Connect to mail service "<<<Correo>>>" with the password "<<evamaster>>" (no se conecta al correo)
Web2 InsertValue "<<pv_Raspi>>" in selector ="#app > div.col-md-offset-2.col-md-4 > div > div:nth-child(4) > input (escribe tal cual pv_Raspi)
```

**Expected behavior**
Que tomara el valor de la contraseña guardada en passwordvault y se conectara al correo. En el segundo escribiera en la pagina el valor guardado en pv_Raspi

**Screenshots**

**Desktop (please complete the following information):**
 - Version de Turing 20210119T1520

**Additional context**
![ERROR BIOTIME](https://user-images.githubusercontent.com/76222575/105865776-dd847a00-5fb8-11eb-8c3f-fb52dd6b6d61.PNG)
 VDI/Máquina virtual,

**Comment by FaustinoLechuga** [comment]
Me puedes indicar cual es el id del proceso en donde se te presenta este inconveniente?

**Comment by practicanterpa** [comment]
Hola buen día

Si, los ids de los procesos del reporte son 7830660 y 4479287

**Comment by practicanterpa** [comment]
Los ids de las suites donde se corren los procesos son Soporte L3 (id 7830660), Procesos EVA (id 6172852)

**Comment by FaustinoLechuga** [comment]
Hola, estuve haciendo unas pruebas con en las suites que me mencionas y pude usar las contraseñas de passwordvault sin problema. 

Para el caso del Insert de Web2 el bot escribe "pv_Raspi" por que es el valor que esta guardado en passwordvault, en otras palabras, el nombre de la variable y su valor es el mismo. Para solucionarlo solo habria que cambiar el valor de la variable.

Para el caso del correo tendrás el log de la ejecución donde no se conecto? Veo que el ejemplo que nos compartiste la variable correo tiene 3 `<>` y es una stepvariable que funciona solo con 2 `<>`. Es posible que al hacer el reempalzo de la las variables la instruccion quede de esta manera, por ejemplo:

`Mail Connect to mail service "<faustino.villarreal@softtek.com>" with the password "Password1"`

en lugar de quedar asi:

`Mail Connect to mail service "faustino.villarreal@softtek.com" with the password "Password1"`

Y que eso este ocasionando el error de conexión al correo, pero para estar seguro necesitaria ver el log de la ejecucion que marco el error.

**Comment by rubenleal** [comment]
@FaustinoLechuga , lo ejecuto en mi máquina y si funciona, tengo otra versión, quizás sea la versión de ese usuario:
[LogOneDrive.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/5882400/LogOneDrive.txt)

No hace la conversión de la variable:
![image](https://user-images.githubusercontent.com/54807268/106039474-c750e980-609e-11eb-947a-2a46a5172c55.png)
 
*Quise hacer la prueba en la misma máquina ingresando con mi usuario pero ahorita está apareciéndome para actualizar una v2019:
![image](https://user-images.githubusercontent.com/54807268/106039660-fcf5d280-609e-11eb-897a-cc47fa8281ff.png)

**Comment by FaustinoLechuga** [comment]
Ok, hare pruebas con esa versión. @rubenleal una pregunta, ¿Quién esta a cargo del usuario @practicanterpa?

**Comment by FaustinoLechuga** [comment]
Realice las pruebas con varias versiones y de igual manera funciono sin problemas. Hice unos cambios y agregue al usuario de eva y el de practicanterpa a la suite de Procesos Eva, posiblemente esto solucione el problema. 

En caso que no se solucione habria que forzar un update para validar que la version que esta en la maquina sea la que estamos probando.

Respecto al tema de tu versión te mande la version 20210119T1520 que es la misma que tiene el usuario practicanterpa.

**Comment by rubenleal** [comment]
Gracias Tino, comparto retro:
- Practicante RPA es Eliud Bernal, lo localizas así en el Teams de HEB <practicanterpa@hebmex.com>
- EVA y PracticanteRPA tenían acceso a la suite Procesos EVA, solo que los tienen asignados al nivel App.
- EVA y PracticanteRPA tienen versiones distintas, en la versión de EVA no funcionó y en la de RPA sí. 
- Ya me regresaste unas versiones :P, mejor mándame la que tenía 20210126T1657 que incluye ajustes que me mandaron Toño y Andrés, y por fa asígnala a (con esto verificamos nuevamente lo del Password Vault): 
rleal@hebmex.com
eva@hebmex.com
practicanterpa@hebmex.com
practicanteBI@hebmex.com
heber.solis@softek.com
ipuente@hebmex.com

**Comment by FaustinoLechuga** [comment]
Ok, les asigne la version 20210126T1657 a estos usuarios:
- rleal@hebmex.com
- practicanterpa@hebmex.com
- practicanteBI@hebmex.com
- heber.solis@softek.com
- ipuente@hebmex.com

A este usuario le deje la versión que tenia por que es mas nueva y puede impactar el cambiarlo a una versión anterior.
- eva@hebmex.com (20210127T0708)

**Comment by eva-ti** [comment]
Buenas tardes, se estuvieron realizando pruebas con la suite de Soporte L3 en el id 7830660 en la versión que se instalo en "eva@hebmex.com (20210127T0708)". Cuando se ejecuta de manera local el proceso si agarra las contraseñas del password vault pero al momento que se corre el proceso mediante la línea de comandos esta no hereda las contraseñas.

**Comment by practicantebi** [comment]
Buenas tardes, se estuvieron realizando pruebas con la suite de Soporte L3 en el id 7830660 en la versión que se instalo en "eva@hebmex.com (20210127T0708)". Cuando se ejecuta de manera local el proceso si agarra las contraseñas del password vault pero al momento que se corre el proceso mediante la línea de comandos esta no hereda las contraseñas.

**Comment by FaustinoLechuga** [comment]
Con linea de comandos se refieren a ejecutarlo desde el CMD o por medio de Turing Watcher?

**Comment by eva-ti** [comment]
La ejecutamos por medio de powershell en la máquina con la versión (20210127T0708)  y con respecto al proceso en el que estamos trabajando sería la siguiente:
![image](https://user-images.githubusercontent.com/72475466/106194613-afe43000-6174-11eb-9776-1dc100a3fc99.png)

**Comment by FaustinoLechuga** [comment]
Realizare pruebas de manera similar verificar si al ejecutar turing de esta manera se omite la consulta de PasswordVault

**Comment by eva-ti** [comment]
Buenos días, ¿alguna novedad con las pruebas del PasswordVault?

**Comment by practicantebi** [comment]
Buenos días, ¿alguna novedad con las pruebas del PasswordVault?

**Comment by FaustinoLechuga** [comment]
Aun no, sigo intentado replicar el error de la manera que lo comentas.

**Comment by FaustinoLechuga** [comment]
Ya detecte la falla y estoy desarrollando una solución. Haré pruebas para verificar que este cambio no impacte el funcionamiento ya establecido y les hago llegar esta nueva versión al usuario de eva@hebmex.com para que pruebe.

**Comment by FaustinoLechuga** [comment]
Se creo la versión 20210203T2350 que incluye la solución a la problemática, indíquenme cuando les puedo mandar un update con esta versión para que puedan probar. 

Para que el bot imprima las contraseñas correcta es necesario especificar el area en la misma linea de comandos con la que se ejecuta por ejemplo:
C:\Users\...\Turing\App\TuringExpo.exe 7830660 -areaid 7830660

**Comment by practicantebi** [comment]
Buenas tardes, si por favor, mándanos el update y cualquier novedad te comentamos de esta.

**Comment by FaustinoLechuga** [comment]
Listo, ya se les mando el update a estos usuarios:
- rleal@hebmex.com
- eva@hebmex.com
- practicanterpa@hebmex.com
- practicanteBI@hebmex.com
- heber.solis@softek.com
- ipuente@hebmex.com

Quedo a la espera de que prueben y confirmen que funciona correctamente.

**Comment by practicantebi** [comment]
Gracias! Solo me podrías hacer el favor y mandar el update nuevamente a "practicanterpa@hebmex.com" ya que se instalo otra versión que previamente ya estaba en el instalador.

**Comment by FaustinoLechuga** [comment]
La versión que tiene practicanterpa@hebmex.com actualmente incluye un cambio nuevo sobre el ApplyRegex y este cambio de las contraseñas. Asi que no tiene problema al tener esa versión mas reciente.

**Comment by practicantebi** [comment]
Disculpame, era con la de "practicanteBI@hebmex.com"

**Comment by FaustinoLechuga** [comment]
Ok, ya se la acabo de mandar.

**Comment by RickProductivity** [comment]
Ya lo cerramos?

**Comment by eva-ti** [comment]
Buenas tardes, el día de hoy se realizo una pruebas del password vault con el proceso de "Monitoreo One Drive (4479287) que se encuentra dentro de la suite de procesos eva, al momento de llamar el proceso de azure con la linea de comando de "C:\Turing\App\TuringExpo.exe 4479287-areaid 6172852| Out-Null
$LASTEXITCODE"  Nos marca el siguiente error 
![image](https://user-images.githubusercontent.com/72475466/107269444-3dded700-6a0f-11eb-8506-fe7605773533.png)

Este script se usa para 5 ejecuciones con nombres diferentes dentro de azure, sera esa la causa del problema?

**Comment by RickProductivity** [comment]
No valdría la pena que usáramos el scheduler de procesos de Frida en Este escenario ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FaustinoLechuga** [comment]
Creo que es un espacio que falta en el comando para correr el programa. En el ejemplo que me compartiste viene de esta manera: "C:\Turing\App\TuringExpo.exe 4479287-areaid 6172852| Out-Null
$LASTEXITCODE"

No hay espacio entre "4479287" y "-areaid" podrías verificar que exista un espacio en esa linea al momento de ejecutarla? Ese espacio es necesario para identificar los parametros de entrada, en este caso el process id y el area.

**Comment by practicantebi** [comment]
Ya validamos y el problema era como lo comentas, en el espacio que había entre "4479287" y "-areaid" y queda resuelto el problema.
