### ISSUE TITLE
Error al enviar un correo [BUG][Excel/Browpet/Titanium]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#128]
**Describe the bug**
Un script con el id 1624993 lanza este error al enviar un correo si pongo la misma linea en otro proceso y la ejecuto, corre sin problemas
```
02/02/2021 11:04:27 - Mail SendMail to "cgrimaldo@hebmex.com,ojgutierrez@hebmex.com,acolorado@hebmex.com,jghernandez@hebmex.com" with the subject "EVA - HEB Card Dispersión" and the body "Buen día,<br><br>Acabo de enviar dispersiones a HEBCard.<br><br><a href="https://hebmex1.sharepoint.com/sites/EVA-AsistenteVirtual-Sharepoint/Shared%20Documents/Sharepoint/Finanzas/N%C3%B3minas/HEBCard/Archivo%20Dispersi%C3%B3n">Por favor haz click aquí para consultar los documentos.</a><br><br><i>NOTA: Este es un mensaje automatizado, favor de no responder.</i>" : Error
```

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
02/02/2021 11:04:27 - Error : The request failed. The underlying connection was closed: An unexpected error occurred on a send.
02/02/2021 11:04:27 - System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.Management.Automation.PSInvalidOperationException: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was: $CurrentSession.ignoreCert
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.Exchange.WebServices.Data.EwsHttpWebRequest.Microsoft.Exchange.WebServices.Data.IEwsHttpWebRequest.GetResponse()
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.GetEwsHttpWebResponse(IEwsHttpWebRequest request)

**Expected behavior**
enviar el correo

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
20210127T0708

**Additional context**
 Scheduling

**Comment by ErlikC** [comment]
Hola, se ha presentado este problema nuevamente? 
Encontré que el proveedor reportó fallas ese día que se levantó el ticket.
![image](https://user-images.githubusercontent.com/60276982/108234145-23d97e80-710a-11eb-8ecd-8b54d4a92ad5.png)

**Comment by heber-solis** [comment]
ha estado fallando todos los días :/

**Comment by rubenleal** [comment]
El proceso sigue fallando, sin embargo no es el tema del correo, ya que lo quitamos, ahora al concluir con la ejecución del script, siempre muestra el siguiente error:

`Turing was unable to connect to https://automation-1713b.firebaseio.com/, please check your internet connection and retry (Error Code 0xCFBSCAC1)` 

Debe haber algo que le está generando conflicto al código, su apoyo para ayudarnos a identificarlo, se anexa log de ayer:
[LogDispersiones.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6102862/LogDispersiones.txt)

**Comment by gantonioid** [comment]
Sugiero ejecutar el FRIDA_Tester, los tests de HTTP y TLS (1, 5)
![image](https://user-images.githubusercontent.com/9600868/110355483-e5dfc400-7ffe-11eb-8625-8ad60f4081db.png)


![image](https://user-images.githubusercontent.com/9600868/110357949-74554500-8001-11eb-927a-5f7783e9e914.png)

**Comment by heber-solis** [comment]
descargué el frida tester y me sale diferente a como lo tienes ahí,  me muestra esto
![image](https://user-images.githubusercontent.com/54727278/110361301-6f929000-8005-11eb-8017-c1bcf221d2df.png)

**Comment by RickProductivity** [comment]
@Podría haber habido una intermitencia del internet ?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by heber-solis** [comment]
no lo creo, ningún otro proceso marca este error, y este proceso lo marca todos los días sin importar la máquina en la que se ejecute

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/110392422-84374e00-802e-11eb-84b5-de2053718db7.png)
se actualizó Frida Tester y marca todo ok con las pruebas 1,5

**Comment by heber-solis** [comment]
hola, la oportunidad sigue presente, solo falla con el proceso (1624993) hace todo correcto, pero despues del finish hace esto
```
7/03/2021 11:56:19 - Progress : 100 


17/03/2021 11:56:20 a. m. - Turing was unable to connect to https://automation-1713b.firebaseio.com/, please check your internet connection and retry (Error Code 0xCFBSCAC1) 


17/03/2021 11:56:20 a. m. - Error : 


17/03/2021 11:56:20 a. m. - The calling thread must be STA, because many UI components require this. 

```

**Comment by gantonioid** [comment]
@ErlikC

**Comment by ErlikC** [comment]
Lo que identifico es que el reporte con SendMail se ve el codigo asi
![image](https://user-images.githubusercontent.com/60276982/117731654-1e914a80-b1b4-11eb-84ef-b9a682cfa740.png)

Es decir, se ejecuta RunBatch RemotePS y luego la instrucción SendMail.

Este RemotePS es  a fin de cuentas un llamado a Powershell que ejecuta otro llamado a Powershell.
![image](https://user-images.githubusercontent.com/60276982/117731771-4f717f80-b1b4-11eb-83a0-3cee05d53dff.png)

Tanto el error "There is no Runspace available to run scripts in this thread..." como "The calling thread must be STA..." hablan de la necesidad de manejar el hilo en que se ejecuta.


Quiero entender la necesidad de ejecutar el script de powershell de ese modo y no con el código del script en local. 
Se puede cambiar?
Y de no ser así, ya revise como generar el runspace que indica, para controlar la ejecución de powershell, si quieres podemos ponerlos de acuerdo para revisarlo.

**Comment by heber-solis** [comment]
correcto, perdón, esto se solucionó con el fix que me ayudaste la otra vez Erlik del batch que corre el powershell, muchas gracias!

**Comment by ErlikC** [comment]
Ok, que bien. Bueno, entonces ya cierro el ticket

Saludos
