### ISSUE TITLE
[BUG]No se puede conectar a MYSQL[DB Reader]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#129]
**Describe the bug**
No se puede conectar a MYSQL a menos que tenga el dll adjuntado 
[MySql.Data.dll.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/5933336/MySql.Data.dll.zip)

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20210126T1657

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by gantonioid** [comment]
Dónde dices que debe de estar?

**Comment by heber-solis** [comment]
no sé si era tema de versión pero actualizamos las máquinas a la versión 20210217T1634 y el tema ya no está presente, hicimos el workaround que les mencionaba en nuestras máquinas para que nos dejara conectarnos
