### ISSUE TITLE
Grabar videos de evidencia de la ejecución de los scripts

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#13]
Grabar video a la par que se ejecuta el script

**Comment by ErlikC** [comment]
Recientemente el equipo liberó una versión que permite esto que solicitas. Puedo mandar update, si gustas.

![image](https://user-images.githubusercontent.com/60276982/79783436-42ae8f00-8306-11ea-98ae-b8223235d68e.png)

**Comment by heber-solis** [comment]
hola, si por favor, se puede especificar la ruta donde se guardará el video?

**Comment by ErlikC** [comment]
Tenías la versión 20200312T0609 y se actualizó por la versión 20200420T0632. 
Es correcto, si tiene donde especificar la ruta. Al prender la opción de Recorder, se habilita la flecha ">" en donde se ubican esos settings específicos de la grabación.

**Comment by heber-solis** [comment]
muchas gracias
