### ISSUE TITLE
Index was outside the bounds of the array. en ReadRows [BUG][Excel]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#130]
**Describe the bug**
en el process id  1553824927 al ejecutarlo en la versión 20201211T2242 termina sin problemas, pero al ejecutar ese mismo en la versión 20210217T1634 falla con este error

```
Excel ReadRows from {PreListaGrupos} start_at {1} as {ListaCodigos} without nulls : Running
24/02/2021 04:29:00 p. m. - Error : Index was outside the bounds of the array.
24/02/2021 04:29:00 p. m. - Excel ReadRows from {PreListaGrupos} start_at {1} as {ListaCodigos} without nulls : Error
24/02/2021 04:29:00 p. m. - If Block End
24/02/2021 04:29:01 p. m. - Execution ended
```

**Comment by ErlikC** [comment]
me podrias compartir ese excel?

**Comment by heber-solis** [comment]
[ile.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/6069829/ile.zip)
hola! aquí están 👍

**Comment by ErlikC** [comment]
Hola, hice una prueba con esa versión y no me lanzó error. Imagino que alguna edicion al excel provoca las condiciones para que salga el error.
![image](https://user-images.githubusercontent.com/60276982/109733958-c885a280-7b85-11eb-88a6-d2de6193edb5.png)

Servirá poner un systemNotify justo antes de cuando falla esta instrucción para tener la versión exacta del excel antes del fallo?

**Comment by heber-solis** [comment]
Version 2102 build 13801.20266 esta es la versión de Excel, lo raro es que lo único diferente es la versión de turing, si intentamos el mismo script con la versión 20201211T2242 en la misma máquina termina sin problemas

**Comment by ErlikC** [comment]
Se entregó la versión
![image](https://user-images.githubusercontent.com/60276982/114588327-2eb51900-9c4c-11eb-8a01-8bfd033be58d.png)
