### ISSUE TITLE
Error en Cancelaciones SAT

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#131]
Estamos teniendo problemas con el script de cancelaciones SAT, dentro del log de ejecución se identifican  errores en el proceso que han sido constantes 

*Primer error
16/03/2021 05:00:59 a. m. - Web2 Dispose : Running
16/03/2021 05:00:59 a. m. - Running browpet-engine
16/03/2021 05:01:10 a. m. - An error occurred while sending the request.
16/03/2021 05:01:10 a. m. - Web2 Dispose : Success

Segundo error
16/03/2021 05:05:27 a. m. - Web2 Extract from selector="#ctl00_MainContent_tblResult > tbody > tr:nth-child(58) > td:nth-child(2) > span" save as "FolioFiscal58" : Running
16/03/2021 05:05:48 a. m. - {"error":"Element not found"}
16/03/2021 05:05:48 a. m. - Web2 Extract from selector="#ctl00_MainContent_tblResult > tbody > tr:nth-child(58) > td:nth-child(2) > span" save as "FolioFiscal58" : Error

Tercer error (en este es donde truena el script)
3/16/2021 5:07:09 AM - ApplyRegex "\b(?<month>\d{1,2})/(?<day>\d{1,2})/(?<year>\d{2,4})\b" to the string "########" and save as "Fecha2" : Running
3/16/2021 5:07:09 AM - Error regex generate a null result creating an error
3/16/2021 5:07:09 AM - ApplyRegex "\b(?<month>\d{1,2})/(?<day>\d{1,2})/(?<year>\d{2,4})\b" to the string "########" and save as "Fecha2" : Error
3/16/2021 5:07:09 AM - Dispose failed, killing Excel.exe
3/16/2021 5:07:10 AM - Execution ended

El problema se viene presentando desde el miércoles 10 de marzo 

![image](https://user-images.githubusercontent.com/72475466/111332152-278ff080-8637-11eb-9c69-014ee3c52c71.png)

En el error se ha presentado en diferentes Agentes, no en uno en especifico Turing Version: 20210310T0032

**Comment by FaustinoLechuga** [comment]
¿El string que analiza el regex depende del valor que se obtenga del valor que deberia guardar el Extract?

¿Se realizo alguna actualización a Frida antes de que se comenzara a presentar el error?

**Comment by eva-ti** [comment]
Se revisó con Alberto Betancourt
