### ISSUE TITLE
[BUG][Excel] Excel nos cambia puntos por comas

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#133]
**Describe the bug**
Excel de la nada, nos está cambiando puntos por comas, al usar la función Excel ReadRows, la info en el excel no tiene comas
![image](https://user-images.githubusercontent.com/54727278/113019210-92b0eb00-913e-11eb-9fac-91ac8a1fb87f.png)

**To Reproduce**

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
un log es de una ejecución pasada donde no ponía comas y tomaba la info bien, no se han hecho cambios de versión de turing ni cambios a la configuración del excel como para que algo impactara en el script
![image](https://user-images.githubusercontent.com/54727278/113019003-5ed5c580-913e-11eb-8217-f5bfa888c65e.png)

**Desktop (please complete the following information):**
 - Version de Turing 20210310T0032

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by FaustinoLechuga** [comment]
Hola Heber, lo estuve revisando y parece ser configuración de cultura pero no lo pude replicar en mi maquina. La falla la hace en tu maquina o en algún servidor? Recuerdo que me llego a pasar algo similar en un servidor de HEB intentare replicarlo en uno al que tengo acceso para ver de que manera se puede manejar este tema.

**Comment by heber-solis** [comment]
hola Faustino, la falla la hace en mi máquina y en las virtuales, pero no se les ha hecho algún cambio ni a mi máquina ni a las virtuales donde corre FRIDA, el workaround que hicimos fue Replacefromvariable  , to .

**Comment by ErlikC** [comment]
Hola voy a continuar con la revisión de este ticket. Me puedes compartir el ID de ese proceso porfavor.

**Comment by ErlikC** [comment]
El proceso ya esta productivo y no ha tenido problemas. Se cierra el ticket tomando en cuenta que se uso el workarround.
