### ISSUE TITLE
Problemas con Listeners de agentes 08 y 09 

### ISSUE THREAD

**Issue by practicantebi** [FridaSupport/CognitiveTestingMX#134]
**Describe the bug**
Se perdió la conexión con el listener de los agentes 

**To Reproduce**

**Bug information**
Nos aparece que no se pudo realizar la conexión en los agentes 08 y 09 

**Expected behavior**
No hay una alerta que nos indique que el agente está apagado

**Screenshots**
![ee](https://user-images.githubusercontent.com/76496880/115263713-42a0c500-a0fb-11eb-9133-efb5832c8aa7.png)

**Desktop (please complete the following information):**
 - Version de Turing 20210409T1720

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by ErlikC** [comment]
Antes tenia conexión y en algún punto se desconecto? o siempre esta lanzando ese mensaje?

**Comment by eva-ti** [comment]
Sí, tenía conexión, en algún punto marcó eso, desconozco si fue tema de HEB o Softtek. Simplemente se reinició la aplicación de Turing Watcher y funcionó nuevamente. Requerimos una consola que nos indique si el los listeners están encendidos y/o una alerta cuando suceda algo con ellos.

**Comment by ErlikC** [comment]
Lo voy a comentar con el equipo para ver si es viable.

**Comment by rubenleal** [comment]
Hoy tuvimos otra oportunidad, la máquina simulaba estar conectada, sin embargo no le estaban llegando los procesos, tuvimos que reiniciar el listener por que nos notificaron, ¿cómo podemos visualizar esa consola?
![image](https://user-images.githubusercontent.com/54807268/116470738-6f5e8600-a839-11eb-947d-d3cd75bab27b.png)

**Comment by ErlikC** [comment]
Esa consola la puedes ver desde 
https://frida-admin.web.app/
Platique opciones con el equipo respecto a las alertas, aun se definirán próximamente de que modo se puede dar aviso de Turing Watchers desconectados.

**Comment by rubenleal** [comment]
No tenemos permisos para ver esa consola con nuestros usuarios:
![image](https://user-images.githubusercontent.com/54807268/118157957-cbe8a600-b3e0-11eb-986a-0dc505a56a2c.png)

La liga que compartes se queda cargando y solo veo esos menús. Ingreso con mi usuario de FRIDA (rleal@hebmex.com)

**Comment by RickProductivity** [comment]
Gracias Rubén , revisamos el tema de permisos.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ErlikC** [comment]
Cuando te logeas, lo haces con "Login with microsoft?"
![image](https://user-images.githubusercontent.com/60276982/118194765-8abbba80-b40f-11eb-95d5-a73fea7db86e.png)

**Comment by rubenleal** [comment]
Me había metido con credenciales abajo, ya inicié sesión con Microsoft y ya veo más menús, pero las pantallas se quedan cargando:
![image](https://user-images.githubusercontent.com/54807268/118197628-f3f1fc80-b414-11eb-9b5c-3907bfe7dd0a.png)

En el caso de Schedule y Password Vault, me muestra este mensaje: 
![image](https://user-images.githubusercontent.com/54807268/118198046-c5c0ec80-b415-11eb-9abb-23b84b98fa5a.png)

Pero al intentar la reconexión, igual se queda cargando, quizás sea algo relacionado a mi dominio.
![image](https://user-images.githubusercontent.com/54807268/118198100-d96c5300-b415-11eb-9d93-bd13794bfbec.png)

**Comment by ErlikC** [comment]
Hola, ya agregaron lo necesario para que puedas entrar. Podrías darle log out y volver a logearte por favor. Hay que darle el tiempo de realizar el registro.

![image](https://user-images.githubusercontent.com/60276982/118297049-4679fa00-b4a3-11eb-92da-65e22919dd2b.png)

**Comment by rubenleal** [comment]
Gracias Erlik, ya me dejó ingresar y termina de cargar las páginas, sin embargo no veo nada cargado en ellas:
![image](https://user-images.githubusercontent.com/54807268/118317912-49361880-b4be-11eb-8acc-78ea312f88f8.png)

**Comment by gantonioid** [comment]
Solo verías aquellos procesos que te correspondan (suites y apps a las que tengas acceso).

En este momento debería de estarse ejecutando algo de heb?

Como administradores nosotros podemos ver que están estos en cola:
![image](https://user-images.githubusercontent.com/9600868/118318779-7800be80-b4bf-11eb-9a32-32a58ad572af.jpeg)

Recuerda que esta consola es para ver los procesos en ejecución que fueron invocados a través de RunProcess (Turing Listener). Aquellos lanzados de otra forma no se ven aquí.

Podemos ayudarte a lanzar un proceso que tengas de prueba mediante RunProcess para comprobar que puedes verlo en la consola. @ErlikC

**Comment by rubenleal** [comment]
Gracias, platiqué con Erlik, corrimos un proceso y apareció el mismo:
![image](https://user-images.githubusercontent.com/54807268/118341117-8e207600-b4e3-11eb-89d3-10b27c1df2ad.png)
Se puede cerrar el ticket.
