### ISSUE TITLE
ReadRows no respeta el formato[BUG][Excel]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#136]
**Describe the bug**
Al usar la instrucción readrows no respeta el formato de la celda 

![image](https://user-images.githubusercontent.com/54727278/116282205-1961e380-a750-11eb-957f-b44d2115a76d.png)
en el log aparece así 
![image](https://user-images.githubusercontent.com/54727278/116282465-6ba30480-a750-11eb-91dd-e0a089cb64fa.png)

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
obtener las cantidades en formato $5,700.00 y $10,800.00

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20210409T1720

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by ErlikC** [comment]
Buscando opciones, parece ser que ReadCellText es mejor opción que crear una sintaxis nueva. 
Anteriormente se observo que ReadCellText puede ser un poco lento, por la forma en que accede al texto formateado de la celda. 

La razón de no crear una nueva sintaxis es que no hay modo directo de obtener el texto mas que meter en un ciclo la forma como lo hace ReadCellText, pero la desventaja es que dado que ReadRows, va a leer todas las columnas indicadas, y normalmente no se procesan todas las columnas de información. Esto va a implicar que se tome demasiado tiempo para identificar el texto en el formato en que viene, para al final no procesarlo. Lo mejor seria desde Turing hacer un ciclo buscando leer la columna C (o las que se vayan a procesar).
