### ISSUE TITLE
[BUG][Titanium Sleep]

### ISSUE THREAD

**Issue by practicantebi** [FridaSupport/CognitiveTestingMX#137]
**Describe the bug**
En algunos procesos al momento de utilizar el titanium sleep, esta arrojando el siguiente error 
![image](https://user-images.githubusercontent.com/76496880/116623231-8c638980-a90b-11eb-8b4e-6cd9a1d97b82.png)
Contamos con un script (Elvis 265218920 ) el cual trabaja con esa imagen pero el error nos esta apareciendo con otros scripts como el de Linea Raat 272888295  los cuales no utilizan nada de información de este y al ejecutar sleep marcan lo de arriba 

**To Reproduce**
Fallas en la sentencia Titanium Sleep

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
El usar titanium sleep sin interferencia de otro proceso

**Desktop (please complete the following information):**
 - Version de Turing 20210409T1720

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by rubenleal** [comment]
Ya no se ha presentado este tema en las últimas versiones, sugiero cerrarlo.
