### ISSUE TITLE
[BUG][DB] Problema de memoria al ejecutar ciclo de querys con +700mil registros en Oracle

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#138]
**Describe the bug**
FRIDA marca error de memoria al ejecutar múltiples querys en Oracle

**To Reproduce**
[Scripts.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/6480818/Scripts.zip)

**Bug information**
Se obtienen los resultados de un query en Oracle por semana (700K por semana) en un ciclo, **_la primer semana concluye bien_**, pero al no depurarse la memoria, en la segunda marca el error.

**Expected behavior**
Mecanismo para limpiar la memoria utilizada por DB y continuar trabajando con las demás semanas

**Desktop (please complete the following information):**
Turing Version: 20210409T1720

**Additional context**
Se agregó un CommitLog para ver si ayudaba en algo aunque el log realmente no pesa.
El log sugiere utilizar la función QueryToCsv, sin embargo al utilizar esta indica que no está disponible para Oracle (caso actual).

**Logs**
[Log.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/6480817/Log.zip)

**Comment by jorgergarciaf** [comment]
Se asigno nueva version con mejoras en memoria en RunOutputQuery y función QueryToCsv para oracle.

**Comment by rubenleal** [comment]
@jorgergarciaf me aparece una versión del 2019, me podrías ayudar a verificar:
![image](https://user-images.githubusercontent.com/54807268/118834419-d3e49200-b887-11eb-92b2-51957f410d8d.png)

**Comment by jorgergarciaf** [comment]
Se asignó nueva version con mejoras en memoria en RunOutputQuery y función QueryToCsv para oracle

**Comment by rubenleal** [comment]
Con ambas funciones siguió marcando error de memoria, QueryToCsv falló en la primer ronda del ciclo, RunOutputQuery falló en la segunda como en un inicio:
**QueryToCsv** 
`20/05/2021 05:56:10 p. m. - Exception of type 'System.OutOfMemoryException' was thrown.
20/05/2021 05:56:10 p. m. - DB QueryToCsv {MySQL.txt} in {DBPMM} save as {C:\Users\eva\Downloads/ResultadoQueryPMM.csv} : Error
`

**RunOutputQuery** 
20/05/2021 05:36:07 p. m. - We ran out of memory, you could try exporting the query result directly to CSV using DBReader's "QueryToCsv" instruction.
20/05/2021 05:36:07 p. m. - DB RunOutputQuery {MySQL.txt} in {DBPMM} as {ResultadoQueryPMM} : Error
```

Comparto los logs:
[logRunOutputQuery.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6519192/logRunOutputQuery.txt)
[logQueryToCsv.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6519193/logQueryToCsv.txt)

**Comment by jorgergarciaf** [comment]
Estamos atendiendo los comentarios que nos envias, danos oportunidad de realizar algunas pruebas mas y respondemos a la brevedad.

**Comment by jorgergarciaf** [comment]
La version de turing esta creada para una compilacion de 32bits, esto tiene una restriccion de 2GB en memoria, y esto hace que en Querys del tamaño de tu proceso no sea lo suficiente. Para solucionar esto se creo una version de 64bits y esto ya no tiene restriccion en memoria mas que lo que tiene el equipo como tal. Esta version la puedes descargar en el siguiente enlace: 

https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/64

**Comment by rubenleal** [comment]
Funciona @jorgergarciaf, buen trabajo!
Dudas:
- Las funciones en las versiones 32b y 64b, ¿son las mismas?
- ¿Qué hay que hacer para que todas las nuevas versiones que me mandan se generen en la versión 64b?
- ¿Podrían hacerme llegar la actualización vía Turing? Ahorita me dice que si quiero actualizar pero entiendo que ofrece regresar a la versión de 32bits.

**Comment by jorgergarciaf** [comment]
* Si son las mismas versiones.
* Si tienes algun nuevo error y necesitas una nueva version, por el momento tendrias que solicitar la de 64 bits.
* Se esta trabajando para que todas las versiones sean de 64 bits y se envien las actualizaciones via Turing, por el momento se estan enviando para casos especiales como el tuyo.  No tienes que actualizar porque efectivamente te regresa a la de 32 bits.

**Comment by rubenleal** [comment]
Gracias Jorge, tienen alguna fecha estimada para estandarizar a la versión de 64bits?
Por lo pronto colocaremos la misma en uno de los equipos de producción para ver cómo se comportan los procesos actuales.

**Comment by jorgergarciaf** [comment]
Aun no hay una fecha exacta, pero se esta trabajando arduamente para que sea lo antes posible. De momento, los que tienen esta version, se estan enviado las actualizaciones por el enlace de appcenter.

**Comment by jorgergarciaf** [comment]
Pueden descargar nuevamente la version en el siguiente enlace:

https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/65

**Comment by ErlikC** [comment]
podemos cerrar el ticket?

**Comment by rubenleal** [comment]
Se cierra, pero nos urge estandarizar a la versión de 64b, ya que corremos el riesgo de en algún punto actualizar a la de 32 y comenzar a tener oportunidades.
