### ISSUE TITLE
Procesos Calendarizados marcan terminar con error pero terminan bien[BUG]

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#139]
**Describe the bug**
hay ciertos procesos 9239359, 363896850  que al terminar el proceso, marcan que terminaron con error pero al revisar el log no hay alguno, saben que pudiera estar pasando? 

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
![image](https://user-images.githubusercontent.com/72475466/118740841-73673d80-b812-11eb-9051-c92cfa0c3d23.png)
Sale este error, y el 0 al final es el exitcode o sea que termina sin errores el proceso pero creo que por todo el output anterior al cero lo marca como error :/ 

**Desktop (please complete the following information):**
 - Version de Turing [20210409T1720]

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by gantonioid** [comment]
En el caso de 363896850 yo sugeriría cambiar `Web Sleep` por `Titanium Sleep` ya que no es necesario abrir browpet si solo necesitas la instrucción de Sleep

En el caso de 9239359 me parece raro que intentes hacer un `Web Dispose` en la línea 8 del archivo `Actions.txt`, si no has hecho antes un GoTo. Yo creo que Dispose falla porque intenta cerrar un browser que **aún no existe** (tienes que hacer un GoTo primero)

**Comment by heber-solis** [comment]
hola, el proceso 363896850  tenía un Titanium Sleep pero a causa del issue #137 se cambió a Web Sleep 
del Web2 Dispose deja lo intento y te confirmo si ese fue el problema, muchas gracias!
