### ISSUE TITLE
Excel WriteVariable Value Visible[Mejora]

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#140]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Estoy tratando de escribir una columna de una hoja a otra pero no puedo por que la hoja destino está filtrada entonces no le puedo indicar que escriba en una row en especifico
 
**Describe la idea o solución ideal**
se puede implementar una funcionalidad como al de WriteAll -visible pero para la de WriteVariable Value?

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Agrega información adicional, screenshots, videos, archivos de ejemplo para reproducir el inconveniente.

**Comment by ErlikC** [comment]
Se agrego la funcionalidad para copiar la lista de valores que leiste de una columna a otra columna en la hoja que quieras.
[WriteListOnColumn](https://frida-admin.web.app/Documentation/Readers/Excel%20Reader/WriteListOnColumn)
