### ISSUE TITLE
Powershell no marca error [BUG][Powershell]

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#141]
**Describe the bug**
Al correr un powershell, si ocurre un error en la ejecución el script de frida no termina la ejecución

**To Reproduce**
Correr un powershell y que ocurra un error

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
que se detenga el proceso

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing [20210409T1720]

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by gantonioid** [comment]
Supongo que te refieres a errores no controlados... como que el script solo fuera:
```ps1
$variable = 5/0
```
Esperarías que marcara un error porque 
![image](https://user-images.githubusercontent.com/9600868/120682791-7db84700-c462-11eb-84a3-ce3349f042ea.png)


Sin embargo... puedes arreglarlo en tu script con try/catch
```ps1
try{
    $variable = 5/0
}catch{
    Write-Output "error : Ha ocurrido un error en el powershell"
}
```

Eso te marcaría el error en el log así:
```
6/3/2021 11:58:11 AM - RunPowerShell ps.txt : Running
6/3/2021 11:58:12 AM - Error in the Powershell fileps.txt : error : Ha ocurrido un error en el powershell
6/3/2021 11:58:12 AM - RunPowerShell ps.txt : Error
```

Entonces en tu script frida podrías decidir qué hacer así:
```
try
    RunPowerShell ps.txt
    Message Terminó bien
    # Hacer algo
catch
    Message Terminó mal
    # Hacer otra cosa
end
```

**Comment by gantonioid** [comment]
Tengo una actualización que ya maneja estos errores no controlados, registrándolos en el log
```
6/3/2021 12:28:28 PM - RunPowerShell ps.txt : Running
6/3/2021 12:28:34 PM - Attempted to divide by zero.
6/3/2021 12:28:34 PM - Error thrown in the Powershell file ps.txt
6/3/2021 12:28:34 PM - RunPowerShell ps.txt : Error
```
Además de lanzar un error internamente que puedes cachar en el script principal como se comentó anteriormente

> ```
> try
>     RunPowerShell ps.txt
>     Message Terminó bien
>     # Hacer algo
> catch
>     Message Terminó mal
>     # Hacer otra cosa
> end
> ```


Favor de compartirme los emails de los usuarios para mandarles la actualización de Turing, si lo desean. De cualquier forma, queda resuelto el problema y cerraré el issue.
