### ISSUE TITLE
Descargar archivos FTP[Mejora]

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#143]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
actualmente usamos un script de powershell para descargar los archivos de un FTP podría integrarse esta funcionalidad a FRIDA?

**Describe la idea o solución ideal**
Descargar los archivos que se encuentran en cierta carpeta de un FTP 
[PSHEBCardDescargar Archivos FTP.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6565497/PSHEBCardDescargar.Archivos.FTP.txt)

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Agrega información adicional, screenshots, videos, archivos de ejemplo para reproducir el inconveniente.

**Comment by gantonioid** [comment]
Por el script creo que se requiere descargar el directorio completo, cierto?

**Comment by heber-solis** [comment]
correcto

**Comment by gantonioid** [comment]
Implementado en la versión `20210601T1941`

Función **FTP_Download**
https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/FTP%20Download

Sintaxis:
`FTP_Download strict={<isStrict:true|false>} url={<host>} credentials={<user>,<pass>} out={<destinationFolder>}`

Ejemplo:
`FTP_Download strict={false} url={ftp://waws-prod-bay-041.ftp.azurewebsites.windows.net/site/wwwroot/someDir} credentials={frida,innovation} out={C:/Users/gilberto.isida/Documents/FTPTests}`

**Comment by gantonioid** [comment]
Se le asignó la nueva versión a heber en heber.solis@softtek.com

**Comment by gantonioid** [comment]
Se generó otra versión para intentar que funcione con más servidores FTP. v `20210602T1411`

**Comment by gantonioid** [comment]
Resuelto en v.`20210602T1616`
