### ISSUE TITLE
Mover Archivos a otra carpeta, dentro de un FTP[Mejora]

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#144]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Actualmente, movemos un archivo de una carpeta a otra dentro del mismo FTP

**Describe la idea o solución ideal**
Agregar esta funcionalidad a FRIDA para no depender de un powershell
[PSHEBCardMoverArchivo.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6572451/PSHEBCardMoverArchivo.txt)

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Anexo script de PS

**Comment by gantonioid** [comment]
Implementado en la versión `20210601T1941`

Función **FTP_Rename**
https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/FTP%20Rename

Sintaxis:
`FTP_Rename overwrite={<isOverwrite:true|false>} source={<sourcePath>} destination={<destinationPath>} credentials={<user>,<pass>}`

Ejemplo:
`FTP_Rename overwrite={true} source={ftp://waws-prod-bay-041.ftp.azurewebsites.windows.net/site/wwwroot/TonyTest/frida.png} destination={ftp://waws-prod-bay-041.ftp.azurewebsites.windows.net/site/wwwroot/TonyTest/Move/fridamoved.png} credentials={frida,innovation}`

**Comment by gantonioid** [comment]
Se le asignó la nueva versión a Heber en heber.solis@softtek.com

**Comment by gantonioid** [comment]
Resuelto en v.`20210602T1616`
