### ISSUE TITLE
Error al usar CopyPaste[BUG][Excel]

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#145]
**Describe the bug**
Al querer copiar una columna me marca el siguiente error

 Excel CopyPaste tarifasSheet C2:lastC to tarifasSheet D2 : Running
31/05/2021 16:21:55 - Error in CopyPaste
31/05/2021 16:21:55 - Error : You can't change part of an array.
31/05/2021 16:21:55 -    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.Copy(Object Destination)
   at ExcelReader.ExcelExecute.CopyPaste(String action) in C:\Users\erlik.corona\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 6368
31/05/2021 16:21:55 - Excel CopyPaste tarifasSheet C2:lastC to tarifasSheet D2 : Error

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
process id 614405538

**Expected behavior**
Copiar el rango de celdas a otra columna

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20210512T1546

**Additional context**
Máquina física

**Comment by ErlikC** [comment]
La instrucción
`Excel CopyPaste tarifasSheet C2:lastC to tarifasSheet D2`
es usada por mucha gente, y tenia una falla que aparentemente en lugar de leer información de "C", agarraba campos de las siguientes columnas, por alguna razon no habia sido reportado este comportamiento antes, así que para no afectar esos bots que ya usan last`<columna>` en esta instrucción, se hizo la sintaxis.

`Excel CopyPaste tarifasSheet C2:lastC to tarifasSheet D2 optimized`

**Comment by ErlikC** [comment]
cerramos el ticket?

**Comment by heber-solis** [comment]
si por favor
