### ISSUE TITLE
Error ApplyFilter [BUG][Excel]

### ISSUE THREAD

**Issue by eva-ti** [FridaSupport/CognitiveTestingMX#146]
**Describe the bug**
Al querer aplicar filtro en una columna me marca el siguiente error 

```
Excel ApplyFilter to the worksheet tarifasSheet to the column with the index {9} with the criteria "si" : Running
31/05/2021 16:36:16 - Error applying filter
31/05/2021 16:36:16 - Error : AutoFilter method of Range class failed
31/05/2021 16:36:16 -    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.AutoFilter(Object Field, Object Criteria1, XlAutoFilterOperator Operator, Object Criteria2, Object VisibleDropDown)
   at ExcelReader.ExcelExecute.ApplyFilter(String action) in C:\Users\erlik.corona\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 4980
31/05/2021 16:36:16 - Excel ApplyFilter to the worksheet tarifasSheet to the column with the index {9} with the criteria "si" : Error

```
**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20210512T546

**Additional context**
Máquina física

**Comment by ErlikC** [comment]
Este error ocurría por que se trataba de una tabla de excel.
Se agregó la sintaxis para indicar el nombre de la tabla y poder considerarla al realizar el filtro.
`ApplyFilter to the worksheet <worksheetKey> in table {<tableName>} to the column with the index {<columnIndex>} with the criteria "<criteria>"`

**Comment by ErlikC** [comment]
cerramos el ticket?

**Comment by heber-solis** [comment]
si por favor :)
