### ISSUE TITLE
No se pueden remover filtros de tabla[BUG][Excel]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#147]
**Describe the bug**
al usar la insrucción Remove Filters, me marca que si los quita, pero al abrir el excel, sigue filtrado

**To Reproduce**
Excel RemoveFilters from tarifasSheet

**Bug information**
process id 237735818

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing [e.g. 20210602T1616]

**Additional context**
Máquina física

**Comment by ErlikC** [comment]
Hola, como nota adicional para @jorgergarciaf  La instrucción removeFilters no está funcionando cuando se trata de Tablas de excel con filtros.

**Comment by gantonioid** [comment]
@heber-solis Pueden compartir el Excel en cuestión? si es información sensible, por favor mándala por mail.

**Comment by heber-solis** [comment]
[Verificacion Tarifas 2019.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/6592744/Verificacion.Tarifas.2019.xlsx)
una disculpa jaja, actualicé un par de datos

**Comment by jorgergarciaf** [comment]
Se creo una nueva version con la funcion para remover los filtros en tablas. Requieres se asigne esta version?

https://frida-admin.web.app/Documentation/Readers/Excel%20Reader/RemoveAllTableFilters

**Comment by heber-solis** [comment]
si por favor, muchas gracias!

**Comment by jorgergarciaf** [comment]
Se asignó nueva version con la funcion mencionada.
