### ISSUE TITLE
[BUG][Excel] ReadColumn agrega valores en el array cuando se tiene solo 1 línea

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#148]
**Describe the bug**
Al aplicar ReadColumn sobre un Excel con una línea, el valor se agrega en la 4ta posición del array en lugar de la primera.

**To Reproduce**
```
Excel LoadWBook "C:\Users\eva\Documents\HEB RPAs\Aplicaciones de Pago\Archivos de proceso\deposNuevo(1).xlsx" as ActualDeposBook1
Excel LoadWSheet ActualDeposBook1 sheet_index 1 as ActualDeposSheet1
Excel ReadColumn from the worksheet ActualDeposSheet1 with the column index {4} and save its value as {IdPagosNuevos} with nulls

Excel LoadWSheet ActualDeposBook1 sheet_index 2 as ActualDeposSheet2
Excel ReadColumn from the worksheet ActualDeposSheet2 with the column index {4} and save its value as {IdPagosNuevos} with nulls
```

**Bug information**
Se realizó el ejercicio en un Excel con 2 pestañas, una tiene 1 registro y la otra 2, en la pestaña con 1 registro aparecen 4 posiciones en el array (incorrecto), mientras que en la 2, aparecen solo 2 (correcto), se comparte log:
[log-2021061114453363.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6639339/log-2021061114453363.txt)
[deposNuevo(1).xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/6639366/deposNuevo.1.xlsx)

**Expected behavior**
Agregar solo un valor al array

**Screenshots**
![image](https://user-images.githubusercontent.com/54807268/121707524-42d69480-ca9c-11eb-910f-0e41b5fcd4a1.png)

**Desktop (please complete the following information):**
 - Version de Turing 20210521T0000 64b

**Additional context**
Se requiere la nueva versión en 64bits

**Comment by jorgergarciaf** [comment]
Se revisa y se informa la brevedad

**Comment by jorgergarciaf** [comment]
Se corrigió función para que tome correctamente cuando sea solo un registro.
Favor de descargar la versión desde el siguiente enlace:

https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/69

**Comment by practicanterpa** [comment]
Hola, se hicieron pruebas con la versión del enlace pero el problema se sigue presentando 

La version que se instala al descargar el enlace es: 20210512T1546 
![image](https://user-images.githubusercontent.com/76222575/122438032-e671ea00-cf5f-11eb-94cb-8a363775837a.png)
![image](https://user-images.githubusercontent.com/76222575/122438081-f4276f80-cf5f-11eb-836a-aa7c4b2d9650.png)

**Comment by jorgergarciaf** [comment]
Por favor descargar la siguiente version:

https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/70

![image](https://user-images.githubusercontent.com/50213195/122478532-2ef4cc00-cf8f-11eb-9fe0-fc5a7d8ea685.png)

**Comment by rubenleal** [comment]
Funcionando, se cierra ticket:
![image](https://user-images.githubusercontent.com/54807268/122800188-416d4f00-d288-11eb-9479-34abc02bcc5a.png)
