### ISSUE TITLE
Filtrar una tabla y borrar las rows[Mejora]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#149]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Actualmente existe esta funcionalidad pero no está implementado cuando se trabaja con tablas

**Describe la idea o solución ideal**
Al momento de filtrar la info en una tabla, borrar esas rows 

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Agrega información adicional, screenshots, videos, archivos de ejemplo para reproducir el inconveniente.

**Comment by ErlikC** [comment]
Hola, ya se generó la instrucción de ApplyFilter para tablas
