### ISSUE TITLE
Cargar archivo TXT con guión bajo ( _ )

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#15]
al momento de cargar un archivo txt a FRIDA y este tiene  guion bajo "_" turing bota el error de que no encuentra el archivo y muestra el nombre pero sin el guion bajo

**Comment by gantonioid** [comment]
Lo que vamos a hacer es desplegar un mensaje indicando que la herramienta no acepta ese caracter (_)
