### ISSUE TITLE
New WB con 3 pestañas en vez de una[BUG][Excel]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#150]
**Describe the bug**
al crear un nuevo Workbook se crea con 3 pestañas en vez de una, esto causa un problema cuando se trata de crear un sheet con el key Sheet2 o Sheet3

**To Reproduce**
Excel NewWB in {path}

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
que se cree con un solo sheet 

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - 20210520T2155

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/128354771-1948a5c7-cc1a-4bb7-934d-15980127b546.png)

**Comment by gantonioid** [comment]
Esa es la máquina que saca 3 hojas en vez de una?

**Comment by heber-solis** [comment]
perdón es que creí que en mi máquina también me había pasado, ya entré a las máquinas y si, en efecto todas tenían 3 en ese ajuste muchas gracias, con eso ya quedaría resuelto?

**Comment by gantonioid** [comment]
correcto, eso lo resolvería.

Saludos
