### ISSUE TITLE
Mejora de reemplazar espacios en blanco para versión de 64 bits

### ISSUE THREAD

**Issue by practicanterpa** [FridaSupport/CognitiveTestingMX#152]
Reemplazar espacios en del valor de una variable por cierto valor especifico

La idea es poder reemplazar los espacios en blanco que puedan venir dentro del valor de una variable, por ejemplo una variable que almacena una fecha como "19 Julio 2021" reemplazar esos espacios por otro cierto valor que se necesite

Se intento usar esta función pero manda error porque dice que esta en blanco el espacio 
ReplaceFromVariable {fecha} this { } for {%20}

**Comment by AlanArteche** [comment]
Qu[e tal, @practicanterpa , se estará revisando ya que la instrucción sí permite remplazar algún texto por espacio en blanco, más no reemplazar los espacios en blanco por algún texto.

Al momento se permitiría:

```
DefineVariable as "MiNombre" with the value "Alan Mauricio González Arteche"
ReplaceFromVariable {MiNombre} this {Alan} for { }
```

Se buscaría que se permitiera hacer:

```
DefineVariable as "MiNombre" with the value "Alan Mauricio González Arteche"
ReplaceFromVariable {MiNombre} this { } for {,}
```

**Comment by AlanArteche** [comment]
@heber-solis Correcto, con la instrucción RegexReplace podría hacerse sin problema este reemplazo de los espacios en blanco. RegexReplace es más poderosa y no funciona de la misma manera que ReplaceFromVariable ya que la búsqueda de texto a reemplazar puede definirse con una expresión regular tan compleja como sea necesaria, pero también puede ser simple o llegar a funcionar igual si el RegEx a buscar es tal cual un match con cierto texto en especial.

Yo creo que podríamos considerar el uso de RegexReplace como un workaround.

**Comment by AlanArteche** [comment]
Como comentario, la instrucción tampoco funciona en este sentido ya que no está reemplazando por un espacio en blanco sino por un caracter vacío, así que tambíen debe corregirse.

```
DefineVariable as "MiNombre" with the value "Alan Mauricio González Arteche"
ReplaceFromVariable {MiNombre} this {Alan} for { }
```

**Comment by AlanArteche** [comment]
@practicanterpa @heber-solis Listo, ya se aplicó el cambio y estaría disponible en las próximas versiones de 32 bits y 64 bits.
