### ISSUE TITLE
[BUG][DB] Oracle no permite ejecución de múltiples queries en una corrida

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#154]
**Describe the bug**
Se requiere forzar el lenguaje y formato de fecha para no depender de la configuración del equipo donde se ejecuta

**To Reproduce**
[CódigoFRIDA.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6859058/CodigoFRIDA.txt)
**Oracle.txt:**
```
alter session set nls_date_format = 'yyyy-mm-dd';
alter session set nls_date_language = 'English';

select sysdate, next_day(sysdate,'monday') "next mon" from dual;
```

**Bug information**
- Al incorporar los puntos y coma (;) a las sentencias, se produce error: ORA-00922: falta la opción o no es válida
- De no indicar el lenguaje, en algunas máquinas se tiene que ejecutar: select sysdate, next_day(sysdate,'**lunes**') "next mon" from dual

**Expected behavior**
- Permitir ejecutar varias sentencias para poder indicar el formato de fecha y lenguaje predefinido
- En SQL se permite insertar varios querys y obtenerlos todos de una sola vez, resolver esto ayudará a que también en Oracle se puedan tener varios queries separados por cada ";" y evitar múltiples conexiones hacia la BD

**Screenshots**
Así funciona directo en Oracle (SQL Developer):
![image](https://user-images.githubusercontent.com/54807268/126567315-138421b7-060b-4b68-8359-c6058580eacb.png)
Comparto el log de la ejecución:
[log-2021072122202538.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6859090/log-2021072122202538.txt)

**Versión**
20210521T0000 (es la 65 de 64bits)
(Solución se requiere en versión de FRIDA de 64bits)

**Comment by jorgergarciaf** [comment]
Se agregó a la función RunOutputQuery el poder realizar multiples querys de un .txt o .sql separados por ; , además de poder asignar un formato en especifico.

La doumentación es la siguiente:

https://frida-admin.web.app/Documentation/Readers/DBReader/RunOutputQuery
https://frida-admin.web.app/Documentation/Readers/MixReader/SetCulture

Para descargar la nueva version de 64 bits:
https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/78

Las variables cuando sean mas de un resultado las arroja de esta manera, igual que la instruccion para sql:

queryResult (tabla Plants)
query_field_names (encabezados Plants)
queryResult2 (tabla Persons)
query_field_names2 (encabezados Persons)

Ejemplo:
![image](https://user-images.githubusercontent.com/50213195/128577440-212fef2e-ff8a-4c42-876f-d6edf497f63c.png)

![image](https://user-images.githubusercontent.com/50213195/128577284-5306c9cf-6a85-48e9-8f03-b6eb91a167fe.png)

**Comment by rubenleal** [comment]
@jorgergarciaf tengo problemas con las versiones 78 y 79, marcan error al tratar de imprimir los encabezados en el Excel, el script solo se detine no da detalles del error, al parecer hay algo chueco con query_field_names. Ejecuté solo un query, no llegué a intentar con más de 1 consulta.

Ejecuté el siguiente script en la v75 y funciona correctamente:
[FRIDAConexiónBD.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6961877/FRIDAConexionBD.txt)

En SQL.txt tengo lo siguiente:
`select 123 as N, 'ABC' as L from dual`

Log:
[log-2021081013090396.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6961890/log-2021081013090396.txt)
![image](https://user-images.githubusercontent.com/54807268/128872670-d511b271-0496-404c-b9f4-18f5fcf2d84d.png)

**Comment by jorgergarciaf** [comment]
Se revisa y se da respuesta a la brevedad.

**Comment by rubenleal** [comment]
Gracias @jorgergarciaf ya lo probé con 1 y 2 querys y funciona, pero estoy viendo que truena en los querys donde tenemos el operador UNION, ej:
```
select 123 as N, 'ABC' as L from dual
union
select 456 as N, 'ABC' as L from dual;
```

Eso debe devolver la combinación de los 2 querys en un 1 solo resultado, pero al escribir la variable truena:
```
10/08/2021 02:38:13 p. m. - Excel WriteVariableValue {query} in {ResultadosQuery} start_at_row {2} start_at_column {1} : Running
10/08/2021 02:38:14 p. m. - Error Writing the Variable Value
10/08/2021 02:38:14 p. m. - Error : The given key was not present in the dictionary.
10/08/2021 02:38:14 p. m. -    at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ExcelReader.ExcelExecute.WriteVariableValue(String action) in C:\Users\jorger.garcia\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 5879
10/08/2021 02:38:14 p. m. - Excel WriteVariableValue {query} in {ResultadosQuery} start_at_row {2} start_at_column {1} : Error
10/08/2021 02:38:15 p. m. - Execution ended

```

**Comment by jorgergarciaf** [comment]
@rubenleal por favor descargar la version:
https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/81

Se modificó RunOutputQuery para hacer consultas simples, multiconsultas separadas por ; y consultas union. 

Tambien se agregó la instruccion ShowQueryInfo para mostrar por log el resultado de los querys, nombre de campos y nombre de variables.
https://frida-admin.web.app/Documentation/Readers/DB%20Reader/ShowQueryInfo

![image](https://user-images.githubusercontent.com/50213195/129109143-dc1d5911-f737-4dd9-b5be-5e03aa70efcb.png)

**Comment by rubenleal** [comment]
Me muestra el siguiente error:
11/08/2021 07:13:24 p. m. - DB RunOutputQuery {SQL.txt} in {DBPMM} as {query} : Running
11/08/2021 07:13:24 p. m. - **Error : Could not find a part of the path 'C:\Turing\App\Local\0\0\SQL.txt'.**
11/08/2021 07:13:24 p. m. - DB RunOutputQuery {SQL.txt} in {DBPMM} as {query} : Error

**Comment by jorgergarciaf** [comment]
Ok, gracias, envio a la brevedad nueva version

**Comment by jorgergarciaf** [comment]
@rubenleal  por favor descargar version 82

https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/82

**Comment by rubenleal** [comment]
Estoy ejecutando el query pero tengo oportunidades:
     - Versión 75 (Oracle) > Funciona y devuelve 84K resultados en 1min
     - Versión 75 (SQL) > Desde SQL me conecté vía openquery a Oracle, Funciona y devuelve 84K resultados en 1min
     - Versión 82 (Oracle) > No funciona, marca error: Rollback executed - ORA-00923: FROM keyword not found where expected
     - Versión 82 (SQL) > Funcionó pero los resultados tardan +45mins en depositarse en el Excel 

[QueryPS.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6984261/QueryPS.txt)

**Comment by rubenleal** [comment]
@jorgergarciaf cabe mencionar que la **versión 82 con consultas simples si funciona** para los 3 casos:
**Sencilla:**
`select 123 as N, 'ABC' as L from dual`
**Combinada:**
```
select 123 as N, 'ABC' as L from dual
union
select 456 as N, 'ABC' as L from dual;
```
**Doble:**
```
select 123 as N, 'ABC' as L from dual;
select 456 as N, 'ABC' as L from dual;
```

Pero al parecer con la lógica interna se impacta el performance y por otro lado supongo que los comentarios internos en el query están generando algún tipo de problema en el query

**Comment by jorgergarciaf** [comment]
@rubenleal por favor descargar la siguiente version:
https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/83

En esta versión se valida los comentarios y espacios entre lineas para que no afecte al query que se ingresa a la base de datos. Se descarta instruccion ShowQueryInfo y se deja original ShowLogInfo

Ejemplo:
![image](https://user-images.githubusercontent.com/50213195/129641881-c632de0f-2a68-4992-a36e-91bbaebe7766.png)
Resultado:
![image](https://user-images.githubusercontent.com/50213195/129642063-07ab8bde-904a-4e62-8a12-6af1b59eead5.png)

**Comment by rubenleal** [comment]
Ya estamos del otro lado Jorge, está genial! 
Tengo un escenario donde sigo obteniendo: **ORA-00923: FROM keyword not found where expected**
```
select 123 as N, 'ABC' as L from dual
union
select 456 as N, 'DEF' as L--, 987 as 'Col2'
from dual;
```
Mi sentir es que se ejecuta como una sola línea y el from se va como comentario junto a Col2:
select 456 as N, 'DEF' as L--**, 987 as 'Col2' from dual**;

Por lo pronto ya pondré productiva esta versión, eliminaré el comentario de mi query para encontrar el FROM (esperando que no haya otro query en la misma situación), ojalá pueda resolverse, gracias!

**Comment by rubenleal** [comment]
@jorgergarciaf se instaló la versión 83 en productivo y no nos está funcionando con consultas de SQL (Oracle parece funcionar bien), me reporta el equipo que se quedaron los procesos ciclados, estos procesos corren en menos de 1hr y no avanzaron de la consulta en BD:
![image](https://user-images.githubusercontent.com/54807268/130286754-457fe018-0cff-4c4e-82ab-d0c4a3a400f7.png)

Realicé una prueba con una consulta simple en las versiones 74 y 84 y en la última se quedó detenido hasta que detuve el proceso:
![image](https://user-images.githubusercontent.com/54807268/130286637-f586bd1d-e6d0-4e00-8c9a-c98f235a01ba.png)

*Si la consulta devuelve pocos resultados, funciona la versión 84, en el log menciona algunos temas de buffer y memoria:
[log84.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7023856/log84.txt)

**Comment by jorgergarciaf** [comment]
@rubenleal  Pueden descargar la siguiente version por favor

https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/85

**Comment by rubenleal** [comment]
Ya funciona con 50K resultados de manera rápida con múltiples queries en SQL y Oracle en una sola corrida. 
Sin embargo, al parecer algo se queda en memoria, si se re-intenta ejecutar el mismo script por segunda ocasión (SQL), se queda pasmada la aplicación y no concluye su ejecución.

**Comment by eva-ti** [comment]
Se mantuvo constante comunicación con Jorge y se resolvió en la versión 20210831T0133, se tiene 2 días funcionando en producción la misma, se puede cerrar el ticket.
