### ISSUE TITLE
especificar puerto en la instrucción SFTP Upload

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#155]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Actualmente tenemos el problema de que ciertos scripts de powershell marcan error, hay uno en el que subimos un archivo a un SFTP, quise reemplazarlo por la funcion SFTP Upload, pero me marca error, creo que hace falta especificarle el puerto ya que este es por medio del puerto 22 si no no se puede conectar

**Describe la idea o solución ideal**
SFTP Upload host={<host>} user={<UserName>} password={<Password>} location={DestinationFolder} file={<FiletoUpload>} Port={22}

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Agrega información adicional, screenshots, videos, archivos de ejemplo para reproducir el inconveniente.

**Comment by gantonioid** [comment]
SFTP Upload actualmente ya usa el puerto 22.

Qué error te marca?

**Comment by heber-solis** [comment]
hola, me marca esto error en las credenciales pero los datos son los mismos que usamos en un script de PS :/

```
SFTP Upload host={sftpvendor.heb.com.mx} user={rappi} password={oNaLZ7CA} location={/incoming} file={C:\Users\eva\Downloads\rappi-2021-07-13.csv} : Running 

13/07/2021 11:15:49 - Error uploading the file by SFTP 

13/07/2021 11:15:49 - Error : Permission denied 

13/07/2021 11:15:49 - at Renci.SshNet.Sftp.SftpSession.RequestOpen(String path, Flags flags, Boolean nullOnError) 

 at Renci.SshNet.SftpClient.InternalUploadFile(Stream input, String path, Flags flags, SftpUploadAsyncResult asyncResult, Action`1 uploadCallback) 
```

 at Renci.SshNet.SftpClient.UploadFile(Stream input, String path, Action`1 uploadCallback) 

 at MixedReader.MixedExecute.SFTP(String action) in C:\Users\erlik.corona\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 3195 

13/07/2021 11:15:49 - SFTP Upload host={sftpvendor.heb.com.mx} user={rappi} password={oNaLZ7CA} location={/incoming} file={C:\Users\eva\Downloads\rappi-2021-07-13.csv} : Error

**Comment by gantonioid** [comment]
Pero dices que también el PS da error, entonces no será que las credenciales están equivocadas, caducaron o hay otro problema?

**Comment by heber-solis** [comment]
aaa no o sea nos marca error pero si hace lo que debe hacer, esto de marcar error FRIDA lo hace con muchos procesos que corren un powershell, lo reporté en el ticket #151

**Comment by heber-solis** [comment]
Cerraré el ticket, Mariano Hernandez me ayudó, me faltaba un / al final de la ruta
