### ISSUE TITLE
[BUG][Mix Reader] Dice que no existe la instrucción CopyDirectory 

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#156]
**Describe the bug**
Se quiere copiar el contenido de una carpeta a otro lado con la función CopyDirectory pero FRIDA dice que no existe

**To Reproduce**
CopyDirectory source={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio} destination={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rect-Tec-Test\06 junio} recursive={true} overwrite={true}

**Bug information**
```
26/07/2021 17:57:34 - CopyDirectory source={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio} destination={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rect-Tec-Test\06 junio} recursive={true} overwrite={true} : Running
26/07/2021 17:57:34 - Counter operation of wrong type or inexistent variable
26/07/2021 17:57:34 - Instruction copydirectory wasn't found
26/07/2021 17:57:34 - CopyDirectory source={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio} destination={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rect-Tec-Test\06 junio} recursive={true} overwrite={true} : Error

```
**Expected behavior**
Copiar la carpeta al destino con sus archivos

**Desktop (please complete the following information):**
 - Version de Turing 65 de 64bits

**Additional context**
- Realicé la prueba con una ruta local en la máquina en lugar de una de red (\\eva) pero el comportamiento fue el mismo: Instruction copydirectory wasn't found
- La instrucción se obtuvo de los [Readers](https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/CopyDirectory) 
- Se requiere solución en una versión de 64bits

**Comment by jorgergarciaf** [comment]
Se resuelve la instrucción CopyDirectory para version de 64 bits.

Para descargar la nueva version de 64 bits:
https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/78

Ejemplo:
![image](https://user-images.githubusercontent.com/50213195/128578238-6fe00e7a-1d15-414f-850b-086ce7616c9e.png)

![image](https://user-images.githubusercontent.com/50213195/128578308-311580b3-119f-4b85-8fb4-d6994f2031a3.png)

**Comment by rubenleal** [comment]
Funcionando en la versión 79, muchas gracias:
```
10/08/2021 09:32:51 a. m. - Process Name: Academia FRIDA 2
10/08/2021 09:32:51 a. m. - Process ID: 1833314037
10/08/2021 09:32:51 a. m. - Turing Version: 20210804T2034
10/08/2021 09:32:51 a. m. - Hostname: EVA
10/08/2021 09:32:51 a. m. - Execution started: No Headless
10/08/2021 09:32:51 a. m. - CopyDirectory source={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio} destination={\\eva\files\TestImpuestos3} recursive={true} overwrite={true} : Running
10/08/2021 09:32:51 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio
10/08/2021 09:32:51 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio\Ctas IEPS Acreditable
10/08/2021 09:32:52 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio\Ctas IEPS Trasladado
10/08/2021 09:32:52 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio\Ctas Impuestos
10/08/2021 09:32:52 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio\Ctas IVA Acreditable
10/08/2021 09:32:53 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio\Ctas IVA Intercompañía
10/08/2021 09:32:53 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio\Ctas IVA Trasladado
10/08/2021 09:32:53 a. m. - Copying \\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio\Ctas Retenciones
10/08/2021 09:32:54 a. m. - CopyDirectory source={\\eva\files\TestImpuestos\Informacion_Fiscal\2021\SIH\Rec-Tec\06 junio} destination={\\eva\files\TestImpuestos3} recursive={true} overwrite={true} : Success
10/08/2021 09:32:54 a. m. - Execution ended
```

![image](https://user-images.githubusercontent.com/54807268/128886698-31f62926-283c-479b-ae15-5b7e31301206.png)
