### ISSUE TITLE
[Mejora] AddValueToBiList - Para generar arreglos bidimensionales y consolidar variables

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#158]
**Problema actual:**
Tengo que descargar 5 archivos distintos en una pantalla revisando varios atributos, los mismos son distintos entre cada archivo y quiero evitar copiar y pegar el código o generar 15 variables para trabajar en un ciclo

**Describe la idea o solución ideal**
Función que permita dar de alta listas de listas (arreglo bidimensional) como el que se genera con [Excel ReadRows](https://frida-admin.web.app/Documentation/Readers/Excel%20Reader/ReadRows) para en una sola línea definir todos los valores necesarios. Ej. 
```
AddValueToBiList "ArchivosDescarga" values {"Balance Cia Meses","BGCIAM05","//span[contains(text(),'Enviado')]/preceding::a[contains(text(),'Balance por Cía Meses')])[1]"
AddValueToBiList "ArchivosDescarga" values {"Balance Consolidado Periodos","BGCONP08","//span[contains(text(),'Enviado')]/preceding::a[contains(text(),'Balance Consolidado Periodos.XLSX')])[1]"

```

La lógica para su uso sería:
```
foreach item in ArchivosDescarga {
    Web2 Type "<<<item[0]>>>" in id = "TXT_CAMPO_6"
    Web2 Type "<<<item[1]>>>" in id = "TXT_CAMPO_9"
    Web2 ElementExists in xpath="(<<<item[2]>>>" save as "BalancePeriodosProcesado" timeout = 5000
}

```
**Describe alternativas que hayas considerado**
- Copiar y pegar las líneas 5 veces
- Generar las 3 variables que necesito por archivo (total 15) y meterlas al ciclo
- Generar un Excel y aplicar el ReadRows

**Comment by AlanArteche** [comment]
Se revisará si se puede implementar en la sintáxis existente de AddValueToList o si debe generarse una nueva.

**Comment by AlanArteche** [comment]
La propuesta sería permitir que la instrucción `AddValueToList "<listName>" value "<newValue>"` pudiera recibir de parámetro en `<newValue>` una lista ya existente de una dimensión. Adjunto un ejemplo de cómo se estaría utilizando:

**Código en FRIDA**

```
##Primero creamos unas listas de una dimensión.

AddValueToList "MiListaNombres" value "Rubén"
AddValueToList "MiListaNombres" value "Alan"
AddValueToList "MiListaNombres" value "Gilberto"

AddValueToList "MiListaCiudades" value "Monterrey"
AddValueToList "MiListaCiudades" value "México"
AddValueToList "MiListaCiudades" value "Monterrey"

AddValueToList "MiListaCodigos" value "jygs1u3jf14"
AddValueToList "MiListaCodigos" value "kjhfe800ysf"
AddValueToList "MiListaCodigos" value "25tq6wy73"

##Ahora creamos una lista de dos dimensiones, agregándole las listas anteriores.

AddValueToList "MiLista2D" value "MiListaNombres"
AddValueToList "MiLista2D" value "MiListaCiudades"
AddValueToList "MiLista2D" value "MiListaCodigos"
```

**Resultado en el log**

![image](https://user-images.githubusercontent.com/48565879/128071531-01512614-5978-48d9-9186-2c7343b94aaf.png)

![image](https://user-images.githubusercontent.com/48565879/128071467-b2d5e5e1-a3d5-46df-8f02-7ae9a6c84612.png)

Es decir, primero habría que crear la lista normal de una dimensión y ya después que exista podremos agregarla a una lista que se creará nueva ya de 2 dimensiones.

Qué opinas de esta solución, @rubenleal , ¿te funciona así?

**Comment by gantonioid** [comment]
@rubenleal solicita agregar filas, es decir, a la tabla usuarios (Nombre, Ciudad, Codigo) irle agregando usuarios. igual que Excel ReadRows saca una lista de filas.

Me parece que tu propuesta serviría, pero está al revés el ejemplo. No es una lista de nombres, otra de ciudades y otra de códigos... sino una por usuario.

De cualquier forma, también lo que hay que considerar es la sintaxis para agregar la 'fila' a la tabla de usuarios, pero que no requiera que se arme la lista previamente... similar a SQL donde le dices

INSERT INTO dbo.Users VALUES ( 'Antonio', 'Monterrey', '1234444')

Sería una sola línea, en vez de 4:
```
AddValueToList "usuarioNuevo" value "Antonio"
AddValueToList "usuarioNuevo" value "Monterrey"
AddValueToList "usuarioNuevo" value "1234444"

AddValueToList "TablaUsuarios" value "usuarioNuevo"
```

**Comment by rubenleal** [comment]
Gracias @gantonioid, @AlanArteche. Perdón, me perdí un poco, pero sí, sería algo similar al insert a una tabla para tenerla disponible en una variable (array) y como comenta Toño, en una línea crearla.

Ejemplo:
AddValueToBiList "DatosPersonales" values {"Rubén","Monterrey","78"}
AddValueToBiList "DatosPersonales" values {"Toño","San Pedro","56"}
AddValueToBiList "DatosPersonales" values {"Alan","Saltillo","25"}

Para no obviar, la cantidad de columnas y líneas es N, como en ReadRows de Excel

**Comment by AlanArteche** [comment]
Ok, entonces se agregará la posibilidad de crear una lista 2D con valores explícitos con una nueva instrucción AddValueTo2DList. También se añadirá esta posibilidad a la instrucción existente AddValueToList para que se puedan crear listas con valores explícitos en una sola línea.

**Comment by AlanArteche** [comment]
Buenas tardes, @rubenleal , ya se aplicaron los nuevos cambios mencionados y se canceló lo primero que había comentado para que AddValueToList pudiera llegar a crear listas de 2 dimensiones si se le pasaba de valor otra lista, ahora en estos casos lo que sucede es que se agregan los valores de la otra lista.

A continuación un pequeño ejemplo operando con listas 1D y una 2D. Cabe mencionar que recientemente igual se desarrolló el cambio para poder acceder directamente a los elementos de listas de dos dimensiones utilizando dos índices [X,Y].

**Código en FRIDA**

```
##Definimos unas variables
DefineVariable as "Nombre1" with the value "Rubén"
DefineVariable as "Ciudad2" with the value "San Pedro"

##Definimos una lista 1D y agregamos valores de distintas formas
AddValueToList "DatosRuben" value {"<<<Nombre1>>>", "Leal"}
AddValueToList "CiudadYNumeroRuben" value {"Monterrey","78"}
AddValueToList "DatosRuben" value {CiudadYNumeroRuben}

##Definimos una lista 2D y agregamos valores y otras listas ya existentes.
AddValueTo2DList "DatosPersonales" value {"Gilberto", "Isida", "<<<Ciudad2>>>", "56"}
AddValueTo2DList "DatosPersonales" value {DatosRuben}
AddValueTo2DList "DatosPersonales" value {"Alan", "Gonzalez", "México", "15"}

##Accedemos directamente a los valores de la lista de 2 dimensiones.

Message Datos combinados : <<<DatosPersonales[0,0]>>> <<<DatosPersonales[1,1]>>> <<<DatosPersonales[2,1]>>>
```

**Resultado en el Log**

![image](https://user-images.githubusercontent.com/48565879/128246379-27a50a41-9c71-4d45-bd43-b168e30be6a7.png)

![image](https://user-images.githubusercontent.com/48565879/128246513-62e499ca-063d-479f-8201-70e87b944cc4.png)


Como se puede observar, se ampliaron las opciones para la creación de listas. Se actualizarán las documentaciones de la instrucción AddValueToList y AddValueTo2DList.

¿Requieres que te envíe una nueva versión de Turing para probar estos cambios?

**Comment by rubenleal** [comment]
Gracias @AlanArteche, sí por favor, pásame liga para descargar versión de 64bits.

**Comment by AlanArteche** [comment]
Buenos días, @rubenleal , te comparto el enlace de descarga de la versión de Turing de 64 bits que ya incluye los nuevos cambios desarrollados por este ticket: https://install.appcenter.ms/orgs/innovation-softtek/apps/turing-expo/distribution_groups/softtek/releases/79

Así mismo, te comparto la documentación actualizada de ambas instrucciones:

https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/AddValueTo2DList

https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/AddValueToList

Favor de confirmar si la nueva instrucción AddValueTo2DList funciona como es esperado para cubrir la necesidad. 

Saludos.

**Comment by gantonioid** [comment]
@AlanArteche será que esta versión incluirá también la solución para el tema de #157 ?

**Comment by AlanArteche** [comment]
Correcto, sí incluye el cambio en la instrucción Send SMTP para indicar el Host, el cual también ya está doucmentado: https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/SendSMTP

**Comment by rubenleal** [comment]
Gracias @AlanArteche la nueva instrucción funciona aquí un log:
[log-2021081013444217.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/6962165/log-2021081013444217.txt)

Por favor **_cambia tú contraseña_** de Turing, la versión 79 trae tus credenciales y es posible ingresar con tu usuario.
