### ISSUE TITLE
Colocar un buscador (CTRL+F) y un reemplazar texto (CTRL+H) en Turing para trabajar con el código

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#16]
implementar un buscador para encontrar en el codigo palabras clave e ir mas rápido a la sección que se tiene en mente

**Comment by Johhnn117** [comment]
La función CTRL+F se liberará está semana, en cuanto a CTRL+H seguimos trabajando

**Comment by gantonioid** [comment]
Se les compartió la extensión de VSCode, la cual tiene esa funcionalidad.
