### ISSUE TITLE
[BUG] Frida Comparaciones ">" "<" no válidas para números con decimales

### ISSUE THREAD

**Issue by practicantebi** [FridaSupport/CognitiveTestingMX#160]
**Describe the bug**
El Script nos arroja un error cuando estamos conparando don números diferentes en este caso menor que que donde los cada nuemero tiene 9 digitos y segundo es decimal lo cual frida lo identifica como String y este signo"<" no valida sino nos arroja el error siguiente.

**To Reproduce**
         DefineVariable  as "VariableNumero" with the value "425340234"
         Message Ingresa un numero mayor a 425340234
	if (<<<VariableNumero>>> < 8753345.65)                                             
	Message  es menor
	else
      Message es mayor 
	end

**Expected behavior**
   "Message es mayor"

**Screenshots**

![image](https://user-images.githubusercontent.com/76496880/132725495-84bf8886-eb3f-4679-af10-48efd478b1e7.png)
![image](https://user-images.githubusercontent.com/76496880/132725679-bc1dbdfd-f9e0-40c9-bfa2-5740c62eb98c.png)

**Desktop (please complete the following information):**
 - Version de Turing [e.g. 20190402T1262]

**Additional context**
 VDI/Maquina Virtual

**Comment by AlanArteche** [comment]
Qué tal, @practicantebi , confirmo que el versiones más recientes de Turing el mismo comportamiento se presenta:

![image](https://user-images.githubusercontent.com/48565879/134058035-6ad5d514-fd6f-461d-a6fe-e88812edaf49.png)

Mientras se revisa la razón y cómo se le puede dar solución, te comparto un workaround que es utilizar el comparador de powershell -lt (less than) con el cual se obtiene el resultado esperado como se muestra a continuación.

![image](https://user-images.githubusercontent.com/48565879/134057792-fe8f35e5-56b4-43ad-b36c-440248c562f7.png)

**Comment by AlanArteche** [comment]
Qué tal, ya se hicieron modificaciones para que no se presente este problema, el cual radicaba en la comparación de números con punto decimal, lo cual no estaba permitido hasta el momento. El número límite a utilizar sería **(1.7976931348623157 x 10^308) - 1** , por lo que se espera no ocurra problema por usar números mayores a este.

Cuando haya algún problema con los operandos, se mostrará algún mensaje pertinente sobre cuál es el problema.

Incluyo un ejemplo donde se podrán ver distintos escenarios.

```
DefineVariable as "VariableNumero" with the value "425340234"
Message Ingresa un numero mayor a 425340234

if (<<<VariableNumero>>> < 8753345.65)
	Message Es menor
else
	Message Es mayor
end

DefineVariable as "VariableNumero2" with the value "8753345.65"

if (<<<VariableNumero2>>> == 8753345.65)
	Message Son iguales
else
	Message Son diferentes
end

DefineVariable as "NumeroLimite" with the value "179769313486231569999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999"
DefineVariable as "VariableNumero3" with the value "42534023400"
DefineVariable as "VariableNumero4" with the value "1797693134862315700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"


if (<<<VariableNumero3>>> < <<<NumeroLimite>>>)
	Message Número debajo del límite
else
	Message Número encima del límite
end

if (<<<VariableNumero4>>> < <<<NumeroLimite>>>)
	Message Número debajo del límite
else
	Message Número encima del límite
end
```

En el último caso al estar utilizando un número mayor al límite, se genera un error indicándolo.

[LogResultados.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7198901/LogResultados.txt)

**Comment by AlanArteche** [comment]
@practicantebi ¿Requieres de un update de Turing para verificar este cambio o te basta el workaround que te presenté anteriormente?

La versión utilizada está muy desactualizada, si se está utilizando en productivo, podría ser mejor opción el workaround ya que hay muchos cambios desde esa versión y alguna podría generar algún problema ocasionando que requieran mantenimiento o revisión los bots; si no se está utilizando de esta forma, sí recomendaría un update.

**Comment by practicantebi** [comment]
Este podrias pasarme el update para hacer pruebas pero por el momento en productivo usaremos workaround

**Comment by AlanArteche** [comment]
Listo, @practicantebi , ya te asigné la versión más reciente de Turing donde ya no debería presentarse el mismo problema en las comparaciones utilizando los comparadores **<, >, >=, <=, ==, !=** . Favor de confirmar para que se pueda dar cierre al ticket. ¡Saludos!

**Comment by AlanArteche** [comment]
Buenos días, @practicantebi , ¿has podido realizar pruebas con este cambio? ¿Se puede dar cierre al ticket? ¡Saludos!

**Comment by practicantebi** [comment]
Que tal Alan a un no dej me ver si en la tarde puedo hacer las para dar por cerrado el ticket.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by AlanArteche** [comment]
Buenas tardes, @practicantebi , ¿de casualidad se ya se pudo verificar en uso la mejora? Saludos.

**Comment by practicantebi** [comment]
Muy buenos días disculpen la demora ala probar la nueva versión haciendo las pruebas concluyo que esta funcionando correctamente la versión que me proporcionaron gracias se puede cerrar el ticket.

Prueba realizada
![image](https://user-images.githubusercontent.com/76496880/135641612-2f40f759-e81a-41b7-aa68-30d3d5287d27.png)

Saludos,
Marco Guerrero.
Gracias....
