### ISSUE TITLE
convertir string a Title Case

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#161]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Quisiera convertir en mayúscula la primera letra de un string

**Describe la idea o solución ideal**
input
septiembre
output
Septiembre

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Agrega información adicional, screenshots, videos, archivos de ejemplo para reproducir el inconveniente.

**Comment by gantonioid** [comment]
@jorgergarciaf 
Sugiero una instrucción como Uppercase/Lowercase que ya existen en frida, pero con más párámetros para control del casing
- Titlecase
- Snakecase
- Pascalcase
- Camelcase
- Kebabcase

https://betterprogramming.pub/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

algo como
StringCase input={varName_in} case={title|pascal|camel|pascal|kebab} out={varName_out}

Documentar con extra-docs

@ErlikC

**Comment by ErlikC** [comment]
Generé la versión y se la asigné a Heber, junto con otros pendientes.
