### ISSUE TITLE
[BUG][Excel] RemoveDuplicates

### ISSUE THREAD

**Issue by mireyna** [FridaSupport/CognitiveTestingMX#162]
**Describe the bug**
Necesito remover duplicados de una tabla en una hoja de excel pero la hoja tiene 4 tablas , al momento de ejecutar me marca error

use la siguiente instrucción  
 Excel RemoveDuplicates from wsChargeOpen at [23] 

Process ID: 18129375
Hostname: LSTKMY232015

Marca el siguiente error

9/29/2021 11:37:20 PM - Excel RemoveDuplicates from wsChargeOpen at [23] : Running
9/29/2021 11:37:20 PM - Error in RemoveDuplicates
9/29/2021 11:37:20 PM - Error : Exception from HRESULT: 0x800A03EC
9/29/2021 11:37:20 PM -    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.RemoveDuplicates(Object Columns, XlYesNoGuess Header)
[Conciliación Afirme_2021_8_27092021_0843_RemoveDuplicates.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/7261110/Conciliacion.Afirme_2021_8_27092021_0843_RemoveDuplicates.xlsx)
[log-2021093004302938.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7261116/log-2021093004302938.txt)

   at ExcelReader.ExcelExecute.RemoveDuplicates(String action) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 24896
9/29/2021 11:37:20 PM - Excel RemoveDuplicates from wsChargeOpen at [23] : Error

![image](https://user-images.githubusercontent.com/91275783/135493643-a225b966-6b4e-4b5e-b506-f2751bf85f81.png)

**Comment by jorgergarciaf** [comment]
@mireyna se creó la instrucción RemoveTableDuplicates para eliminar las filas duplicadas cuando se trata de tablas. Se te asignó esta versión para tu validación.

https://frida-admin.web.app/Documentation/Readers/Excel%20Reader/RemoveTableDuplicates

Hay 3 sintaxis.
* **RemoveTableDuplicates from wsChargeOpen**
 Remover todas las filas duplicadas de todas las tablas existentes en una hoja de trabajo.

* **RemoveTableDuplicates from wsChargeOpen in table tblDepositosConciliados**
 Remover todas las filas duplicadas de una hoja y tabla especifica.

* **RemoveTableDuplicates from <worksheetKey> in table tblDepositosConciliados at [<columnIndex1,columnIndex2,...,columnIndexn>]**
 Remover las filas duplicadas de una hoja y tabla especifica, asi como el indice de las columnas especificadas. El indice comienza en 1 por cada tabla.

En la instruccion que estabas usando 
Excel RemoveDuplicates from wsChargeOpen at [23]
deber ser reemplazada por:
Excel RemoveTableDuplicates from wsChargeOpen in table tblDepositosConciliados at [2]

![image](https://user-images.githubusercontent.com/50213195/135555521-69ee314b-30e0-4467-a235-ba872af58f51.png)

**Comment by mireyna** [comment]
Listo, muchas gracias
