### ISSUE TITLE
[BUG]|Cognitive| Download FIle Error TXT Blank

### ISSUE THREAD

**Issue by practicantebi** [FridaSupport/CognitiveTestingMX#164]
**Describe the bug**
El Problema ocurre cuando entro https://cognitive-testing.firebaseapp.com/ y quiero **Descargar cualquier script** y le doy clic al botón de Download File

Cuando le doy clic al botón Download FIle no me baja el texto con la información del script

Se consulta desde la interfaz web de cognitive

Esperaba que estuviera la informacion del script

![image](https://user-images.githubusercontent.com/76496880/135642637-73fce2bc-a6bf-46a7-a378-f8854d64145a.png)
me descarga el .TXT  pero me lo da vacío.

![image](https://user-images.githubusercontent.com/76496880/135643689-aa6a1bbe-966a-442e-856b-77e7ced29aa4.png)

![image](https://user-images.githubusercontent.com/76496880/135643818-cfeba37a-a477-4b36-b27f-0d2a324b3c78.png)

PD. Por favor checar ala brevedad.

Máquina física, VDI

**Comment by jorgebibarra** [comment]
Corregido.

**Comment by practicantebi** [comment]
Puedes corroborarlo es que me sigue bajando los archivos en blanco

**Comment by jorgebibarra** [comment]
Hay que hacer un hard reload
CTRL+shift+R

**Comment by practicantebi** [comment]
Listo muchas gracias

**Comment by practicantebi** [comment]
Tengo una duda casi todos los scripts tiene archivos adicionales esos por que no los descarga

**Comment by jorgebibarra** [comment]
Solo se puede descargar ese script.
