### ISSUE TITLE
[BUG][Frida]Problemas Versiones

### ISSUE THREAD

**Issue by mireyna** [FridaSupport/CognitiveTestingMX#166]
**Describe the bug**
El viernes pasado hice una modificación a mi script lo valide y salió bien, eso fue en la noche , por eso ya decidí terminar por ese día, el lunes en la mañana que ejecuto para otro periodo me salen varios errores y al revisar el codigo con es el mismo que deje el viernes, y no era la primera vez que me pasaba pero como antes solo era una linea o algo asi, pues no le daba la importancia, le comente a Erlik porque si revisaba el log del viernes no tenia nada que ver con el del lunes.

**Bug information**
Process Id = 18129375

**Expected behavior**
Pues la versión que había dejado el viernes

[log-2021100416040913.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7307183/log-2021100416040913.txt)
[log-2021100203541238.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7307184/log-2021100203541238.txt)

**Comment by ErlikC** [comment]
En la revisión que hicimos, se tiene la siguiente cronología.
- Viernes 7:57 PM corre el respaldo de Azure
![image](https://user-images.githubusercontent.com/60276982/136471133-23b4283c-5ed5-4a93-bbad-9768ee91f60c.png)

- Viernes antes de 10:54 se guarda versión final.
- Viernes 10:54 inicia ejecución de proceso. 
![image](https://user-images.githubusercontent.com/60276982/136471383-7d070710-b871-431c-84b5-0dc3e30a4ad3.png)

- Viernes 11:38 PM se guarda el script con alguna versión atrasada a la que se estaba ejecutando. (Esto se va al respaldo realizado en sábado).
![image](https://user-images.githubusercontent.com/60276982/136471246-fea930bc-6f3f-4d52-bd2d-f51c1b28b4d6.png)

- Viernes 11:58 PM acaba la ejecución de la ultima prueba realizada.
![image](https://user-images.githubusercontent.com/60276982/136471476-fe7535ae-8b58-4310-b5b7-10120c783189.png)

- Lunes temprano, se descarga versión de las 11:38 con lo cual se pierden los cambios.

**Comment by ErlikC** [comment]
Hola, se ha repetido este comportamiento?
Podemos decir que fue un problema resuelto?

**Comment by mireyna** [comment]
Hola, buenas tardes, si continuaba pero solo pequeños cambios pero hoy me borro todo el código, lo raro es que en mi maquina dice que la ultima vez que se grabo fue a las 3:33 y lo ejecute a las 6:44 y termino a las 6:51, le di editar porque iba a realizar un cambio pero el proceso esta vacio. Anexo pantallas

![image](https://user-images.githubusercontent.com/91275783/141031486-ab304457-5cd6-4576-af79-b5fceabd032a.png)
![image](https://user-images.githubusercontent.com/91275783/141031509-3833dc75-6d55-4bf9-9292-ec87b5b2e777.png)
![image](https://user-images.githubusercontent.com/91275783/141031518-f8a524ae-8de9-4d8a-9546-41407cbc52ff.png)

**Comment by ErlikC** [comment]
Encontramos el escenario que provoca esto.
En códigos grandes, Turing tiene un comportamiento de "carga en background" del código. Entonces al abrir Turing se abre inicialmente lo que tengas descargado localmente mientras inicia la descarga de los cambios en la nube.
Adicional el procesamiento que se hace para mostrarlo en pantalla, tenía algunos temas y provocaba una carga mas lenta de lo necesario, por lo que podían pasar 30, 50 segundos en lo que se refrescaban los cambios.
Eso es tiempo suficiente para por ejemplo, abrir turing hacer unas modificaciones rápidas antes de que el proceso de refresh se complete y al guardar por lo tanto planchar sin querer el código que estaba en la nube.

Hice unos cambios que en lugar de cargar en ~1 minuto, se carga el script en 5 segundos. Eso debe evitar estos problemas que te ocurrían.
Cuando gustes te mando update.
