### ISSUE TITLE
[BUG][Excel] Uso de WriteList Repite el primer registro de la lista

### ISSUE THREAD

**Issue by practicantebi** [FridaSupport/CognitiveTestingMX#167]
**Describe the bug**
Usando el comando de Excel WriteList la lista la escribe pero cuando llega al final de la lista repite el primer registro de esta.

**To Reproduce**
Se produce cuando queremos agregar una lista en excel usando AddtoList y WriteList toma el valor y  se repite el primer registro en el ultimo

**Expected behavior**
El resultado esperado es que la lista se escribiera de manera correcta sin que se llegara repetir algún registro de ella
Captura de Codigo
![image](https://user-images.githubusercontent.com/76496880/137212884-eca421aa-c215-4495-b5f4-4239494706af.png)
Log
![image](https://user-images.githubusercontent.com/76496880/137213094-39dc104e-b485-4b98-a942-6c472975fe09.png)
Excel
![image](https://user-images.githubusercontent.com/76496880/137213168-c7cc13fc-507c-4552-a19b-5210bed442e2.png)

**Desktop (please complete the following information):**
 - Version de Turing [e.g. 20211008T1604]

**Additional context**
, VDI/Máquina virtual

**Comment by ErlikC** [comment]
Hola, se puede cerrar el ticket?

**Comment by practicantebi** [comment]
Buenas Días

Me puedes asignar la versión de nuevo.

**Comment by AlanArteche** [comment]
Qué tal, @practicantebi , ¿tu versión actual sigue presentando la falla?

**Comment by practicantebi** [comment]
Asi es

**Comment by AlanArteche** [comment]
Listo, @practicantebi , se te asignó una nueva versión 20211103T1749 que contiene el cambio. A la espera de tus comentarios.

**Comment by practicantebi** [comment]
Con esta versión funciona bien

***@***.***
