### ISSUE TITLE
Browpet Web Extract

### ISSUE THREAD

**Issue by RocioPina** [FridaSupport/CognitiveTestingMX#168]
Buen día podrían apoyarme con la instrucción   Web Extract,  ya que a la hora de usar me quita un cero cuando extraigo un valor numérico.
En el ejemplo que muestro a continuación, yo obtengo un valor numérico pero a la hora de actualizar la variable me quita el cero y esto me esta afectando, necesito el cero

Web Extract from selector="#row > tbody > tr > td:nth-child(12)" save as "montoneto2" : Running
24/10/2021 03:00:35 a. m. - 805.640
10/24/2021 3:00:35 AM - Variable updated: 
Var Name: montoneto2
Value: 805.64

**Comment by ErlikC** [comment]
Hola, con eso se puede cerrar el ticket?

**Comment by RocioPina** [comment]
si, gracias!
