### ISSUE TITLE
Excel ExportImage falla después de 10 intentos  [BUG][Excel]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#169]
**Describe the bug**
la función de ExportImage falla después de 10 intentos y a veces lo hace a la primera a veces después de 3 ejecuciones, la instrucción está dentro de un ciclo y un try catch
si hay error se limpia el clipboard y se vuelve a intentar, se cambia el nombre de la imagen, se cierra y abre el excel en los nuevos intentos y de todos modos falla

**To Reproduce**
Excel ExportImage

**Bug information**
507917636 a partir de la linea 84

**Expected behavior**
exportar la imagen del workbook 

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20210831T0133

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Scheduling

**Comment by AlanArteche** [comment]
Qué tal, ¿tendrán alguna evidencia de que este problema se ha presentado como algún archivo Log?

**Comment by AlanArteche** [comment]
Utilizan la instrucción de la siguiente manera:

Excel ExportImage from the worksheet <<<eFC>>>Sheet<<<i>>> from the cell {1,1} up to the cell {<<<<<<eFC>>>LRow>>>,<<<<<<eFC>>>LCol>>>} and save in the file "<<<RutaTrabajo>>>\<<<eFC>>>_<<<i>>>.jpg"

Si falla, dentro del catch incrementan la variable i en 1 unidad, por lo que la hoja sobre la que se intenta hacer la captura ya no es la misma, por lo que las condiciones en cada ejecución son diferentes.

**Comment by heber-solis** [comment]
Hola Alan, pero mas arriba se hace el load de la sheet correspondiente
 Excel LoadWSheet <<<eFC>>>Book<<<i>>> sheet_index 1 as <<<eFC>>>Sheet<<<i>>>
 y esto se hizo por que lo teníamos de la siguiente manera
 try
 for 10 times{
Excel ExportImage from the worksheet <<<eFC>>>Sheet<<<i>>> from the cell {1,1} up to the cell {<<<<<<eFC>>>LRow>>>,<<<<<<eFC>>>LCol>>>}
}
catch
end
este es un ejemplo de la imagen que se anexa cuando logra correr exitosamente la instrucción
![image](https://user-images.githubusercontent.com/54727278/140386142-713dab11-a5ad-4417-a9a2-b057ba994731.png)

**Comment by AlanArteche** [comment]
Ok, ¿tendrán alguna evidencia de que este problema se ha presentado como algún archivo Log?

**Comment by heber-solis** [comment]
[log.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7478790/log.txt)
[Monitoreo_KPI_Por_Hora_2910_04_11.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/7478792/Monitoreo_KPI_Por_Hora_2910_04_11.xlsx)
aquí está el log después de intentar 10 veces sin exito y en otras corridas, a la primera o después de 4 veces si puede hacerlo

**Comment by AlanArteche** [comment]
Revisando ese único caso que se visualiza en el log, se tienen valores comunes para filas y columnas. Realicé una larga prueba de 1000 iteraciones para ejecutar la instrucción abriendo y cerrando el libro y todo de la misma manera como lo realizan en ese script utilizando la misma versión de Turing y todas se ejecutaron correctamente a la primera, es decir, la instrucción nunca resultó en error.

Debe investigarse más a fondo las posibles causas de este error ya que no es reproducible en nuestro ambiente.

¿Se ejecuta algún otro proceso al mismo tiempo mientras se ejecuta este?

¿Se ejecuta de manera manual o a través de Turing Watcher / MailWatcher + Turing Watcher / Scheduling?

**Comment by heber-solis** [comment]
que raro! cabe mencionar que no falla seguido, y hemos buscado hacer dispose del excel, volverlo a abrir, limpiar el clipboard etc y no nos funciona, este proceso se ejecuta de manera calendarizada, desde azure  y solamente se atiende a este proceso cuando llega la hora de ejecutarlo no sé si tengas algún tip de qué pudieramos hacer para asegurar que funcione? no sé si tenga algo que ver pero pues esas máquinas rara vez se reinician

**Comment by AlanArteche** [comment]
Buenos días, @heber-solis , implementé un pequeño cambio a la instrucción ExportImage buscando evitar que suceda el error, el cual es un problema como tal de Excel y no nuestro. 

¿Está bien si te asignó una nueva versión de Turing con este cambio para probar si de esta manera reducimos o se elimina la incidencia del error?

_Incluyo para futuras referencias el foro donde encontré el consejo implementado_ (http://www.vbaexpress.com/forum/showthread.php?55263-CopyPicture-method-of-Range-class-failed)

**Comment by heber-solis** [comment]
hola, mil gracias! podrías mandarmelo a heber.solis@softtek.com, eva@hebmex.com, rleal@hebmex.com, practicantebi@hebmex.com y practicanterpa@hebmex.com por favor

**Comment by AlanArteche** [comment]
Listo, los usuarios mencionados ya tienen asignadas la versión que incluye este cambio. Favor de utilizarla y comentar si en alguna ejecución se vuelve a presentar el error de "CopyPicture method of Range class failed", esperemos que el cambio lo evite ya que es un tema interno de Excel.

**Comment by AlanArteche** [comment]
Buenas tardes, @heber-solis , sólo como monitoreo y seguimiento, ¿ya no se ha presentado el problema  con ExportImage? Alguien más estaba teniendo el mismo problema, se le compartió esta misma versión y lleva una semana sin presentarse el problema, lo cual parece ser una buena señal.

**Comment by heber-solis** [comment]
hola Alan buen día! no ya no se ha presentado este error, yo creo que el fix si sirvió  muchas gracias! 👍🏽
