### ISSUE TITLE
[BUG][Excel] CopyPaste

### ISSUE THREAD

**Issue by mireyna** [FridaSupport/CognitiveTestingMX#171]
**Describe the bug**
Realizo un filtro en la hoja por un campo, después hago un copypaste tomando el inicio y fin donde se encuentra la información filtrada, pero cuando lo filtro por Charge me copia información aunque no cumpla el filtro, pero después filtro por Credit y si me copia solo lo de Credit aunque haya información de Charge intermedio no me la copia que es lo correcto

**To Reproduce**
Escribo esta formula 
Excel WriteFormula wsConta in Z30:LastRow formula =IF(AND([@[Comparar Journal ID vs Source]]=FALSE,AND([@[Primeros digitos Journal ID]] <> "AA",[@[Primeros digitos Journal ID]] <> "CA",[@[Primeros digitos Journal ID]] <> "PA"),[@Pesos]>0),"Charge",(IF(AND([@[Comparar Journal ID vs Source]]=FALSE,AND([@[Primeros digitos Journal ID]] <> "AA",[@[Primeros digitos Journal ID]] <> "CA",[@[Primeros digitos Journal ID]] <> "PA"),[@Pesos]<0),"Credit","No")))

Después filtro y saco el inicio y fin donde esta la información
Excel ApplyFilter to the worksheet wsConta in table {Table2} to the column with the index {26} with the criteria "Charge"
Excel GetSpecial {wsConta} appearance {first} of {Charge} in_index_column {26} and_save_as {FCopiar} start_at {30}
Excel GetSpecial {wsConta} appearance {last} of {Charge} in_index_column {26} and_save_as {LCopiar} none

posteriormente hago el copiado de la información
Excel CopyPaste values wsConta D<<<FCopiar>>>:O<<<LCopiar>>> to wsChargeConta J<<<LRowQueryU>>>

Después hago el otro filtro por Credit y saco el inicio y fin de la información
Excel ApplyFilter to the worksheet wsConta in table {Table2} to the column with the index {26} with the criteria "Credit"
Excel GetSpecial {wsConta} appearance {first} of {Credit} in_index_column {26} and_save_as {FCopiar} start_at {30}
Excel GetSpecial {wsConta} appearance {last} of {Credit} in_index_column {26} and_save_as {LCopiar} none
Se copia la información
Excel CopyPaste values wsConta D<<<FCopiar>>>:O<<<LCopiar>>> to wsCreditsConta N<<<LRowQueryU>>>

**Bug information**
El process id es 18129375

**Expected behavior**
Se espera que se copie solo la información filtrada

**Screenshots**
Se anexa Screenshots

**Desktop (please complete the following information):**
 - Version de Turing [20211001T0128]

![image](https://user-images.githubusercontent.com/91275783/139963985-84a09fa4-e338-4f3e-a055-ea89cfaec88b.png)

copio todo esto cuando deben de ser solo 7 reg

![image](https://user-images.githubusercontent.com/91275783/139964105-12337ff7-fdc9-4513-ae1a-bedb26981043.png)

Para credit si copio solo lo filtrado
![image](https://user-images.githubusercontent.com/91275783/139964280-705eccb2-fe35-4ac7-bc9a-39278dcc2f3f.png)

**Comment by jorgergarciaf** [comment]
Podrias compartir el archivo en Excel por favor.

**Comment by mireyna** [comment]
[Conciliación Afirme_2021_1_02112021_0552.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/7464737/Conciliacion.Afirme_2021_1_02112021_0552.xlsx)
Es de la hoja Conta con esta formula en la columna Z =IF(AND([@[Comparar Journal ID vs Source]]=FALSE,AND([@[Primeros digitos Journal ID]] <> "AA",[@[Primeros digitos Journal ID]] <> "CA",[@[Primeros digitos Journal ID]] <> "PA"),[@pesos]>0),"Charge",(IF(AND([@[Comparar Journal ID vs Source]]=FALSE,AND([@[Primeros digitos Journal ID]] <> "AA",[@[Primeros digitos Journal ID]] <> "CA",[@[Primeros digitos Journal ID]] <> "PA"),[@pesos]<0),"Credit","No")))

despues filtro y los copio a Charge Conta y Credit Conta

**Comment by jorgergarciaf** [comment]
@mireyna se asigno nueva version en donde se toma en cuenta solo los registros visibles al momento de filtrar, solo tienes que agregar al final de la sintaxis de CopyPaste la palabra opcional "visible"

Excel CopyPaste values wsConta D<<<FCopiar>>>:O<<<LCopiar>>> to wsChargeConta J9191 **visible**

Ejemplo de ejecución:

![image](https://user-images.githubusercontent.com/50213195/140167018-c593904f-e0d7-436e-977e-9c0a0bb54eb0.png)

![image](https://user-images.githubusercontent.com/50213195/140167636-0fb3fd0a-ac47-4e8d-89f2-0e503eba23ab.png)

![image](https://user-images.githubusercontent.com/50213195/140167806-f63b1b85-248c-49ec-8a95-70ea76b5ea73.png)

**Comment by mireyna** [comment]
Me marco error al tratar de actualizar
![image](https://user-images.githubusercontent.com/91275783/140235699-a04c55ff-b061-46b4-8ba3-e2e184186e84.png)

**Comment by mireyna** [comment]
Muchas gracias, ya se actualizó, lo volví a cerrar y abrir

**Comment by jorgergarciaf** [comment]
@mireyna tuviste algun problema con la solucion para filtrar y copiar los registros? se puede cerrar el ticket?

**Comment by jorgergarciaf** [comment]
Como lo vimos por teams, el problema fue solucionado, por lo que se cierra ticket.
