### ISSUE TITLE
mandar acentos en función REST [BUG][Mix Reader]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#172]
**Describe the bug**
Necesito enviar este string en el body de una petición REST 
"SOLICITUD DE DEVOLUCIÓN"
no me deja hacerlo en postman a menos que envíe esto en el header desde postman
Content-Type:application/json; charset=utf-8
 pero al implementarlo en FRIDA me marca lo siguiente
```
REST POST url=https://openapi.uat.heb.com/REST/v1/hpsm/incidents/create headers(source:hebmex,apikey:<<APIKeyPV>>,Content-Type:application/json;charset=utf-8) body { "HEBICCIncident": { "AffectedService":"CI20695", "Area":"SOLICITUD DE DEVOLUCIÓN", "Assignee":"m043940", "AssignmentGroup":"TESORERIA", "Category":"service request", "Contact":"m043940", "Description":"PRUEBA EVA NO ATENDER Forma de Pago Paypal Nombre o dato del cliente:Juan Jesús Bueno Devolución total Importe a devolver: Numero de Pedido: 2910000002787", "Impact":"3", "Location":"2910", "Status":"Transferred", "Title":"PRUEBA EVA NO ATENDER Forma de Pago Paypal Nombre o dato del cliente:Juan Jesús Bueno Devolución total Importe a devolver: Numero de Pedido: 2910000002787", "Topic":"PAYPAL", "Urgency":"3", "Vertical":"TESORERIA"} } : Running
05/11/2021 14:38:59 - Error in the call
05/11/2021 14:38:59 - Error : Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
05/11/2021 14:38:59 - at System.Net.Http.Headers.HttpHeaders.CheckHeaderName(String name)
at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
at MixedReader.MixedExecute.REST(String action) in C:\Users\jorger.garcia\source\repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 13898
```

**To Reproduce**
REST con el header Content-Type:application/json;charset=utf-8

**Bug information**
process id 9324641

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing [e.g. 20211029T1510]

**Additional context**
Máquina física

**Comment by AlanArteche** [comment]
Qué tal, @heber-solis , estaré revisando este detalle.

**Comment by AlanArteche** [comment]
@heber-solis , revisando, la solución inmediata sería que quites el header de Content-Type, la instrucción por default asignaría un header de Content-Type application/json;charset=utf-8 .

Favor de relizar este cambio para confirmar que el llamado se realiza sin problema.

Se aplicará un cambio para evitar el error que muestras si se especifica el header como lo tienes, el problema es un error externo de un proveedor pero podemos hacer algo al respecto nosotros.

**Comment by AlanArteche** [comment]
![image](https://user-images.githubusercontent.com/48565879/140811835-90f33d43-d17a-4482-9240-099405db974c.png)

Incluso en la documentación se menciona que por default el contenido se toma como application/json, aunque no se menciona el detalle de UTF-8, así que también se actualizará ese detalle en la documentación.

**Comment by AlanArteche** [comment]
Ya se aplicaron cambios a la instrucción para detectar cuando se incluye en los headers Content-Type (ya que este no debería estar incluído aquí) y que no cause problemas. Si no se define el RequestType, se puede tomar de esos headers, en caso de que se defina en los headers un Content-Type diferente el de RequestType, se tomará el de RequestType y se avisará en el log.

![image](https://user-images.githubusercontent.com/48565879/140962661-78866e4d-e55c-438b-b215-51d61554c090.png)

Adicionalmente, ya se toma en consideración en Charset Encoding tanto si viene en los headers como parte del Content-Type o como parte del RequestType. Al momento los Charsets permitidos son utf-8 (por default), utf-7 y utf-32.

También se modificó la redacción de la documentación de la instrucción:

https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/REST

No considero que sea necesario un update para que puedas continuar con el uso de la instrucción, pero favor de confirmar si removiendo **Content-Type:application/json;charset=utf-8** de los headers en la instrucción ya no tienes problema.

Saludos.

**Comment by heber-solis** [comment]
Muchas gracias si me funcionó :D
