### ISSUE TITLE
La función "DeleteAll" elimine también imagenes en la hoja de trabajo[Mejora]

### ISSUE THREAD

**Issue by luisvalencia95** [FridaSupport/CognitiveTestingMX#173]
Añadirle el funcionamiento que la función "DeleteAll" verdaderamente elimine todo el contenido de una hoja de Excel tanto imagenes como el texto

**Comment by luisvalencia95** [comment]
Hola @jorgergarciaf.

Ya probé lo que liberaron para que delete all también elimine imagenes, sin embargo no me funcionó la imagen no se borró.

**Comment by luisvalencia95** [comment]
@jorgergarciaf me puedes buscar por teams por favor para pasartelo por ahí ya que tiene información confidencial

**Comment by jorgergarciaf** [comment]
Se realizó DeleteAll para borrar el contenido de toda la hoja incluyendo imagenes. Se reviso por teams funcionando correctamente, por lo que se cierra ticket.
