### ISSUE TITLE
ReplaceTextVisible no funcionan en tablas [BUG][Excel]

### ISSUE THREAD

**Issue by luisvalencia95** [FridaSupport/CognitiveTestingMX#174]
**Describe the bug**
Las Funciones de remplace no funcionan en tablas. Intento reemplazar parte de la formula de una tabla y no funciona, sale el error:

**To Reproduce**
Usar cualquier funcion "Replace" para cabiar algo de la formula de una celda de una tabla. 

**Bug information**
Adjunto Log con el error

**Desktop (please complete the following information):**
 - Version de Turing 20211103T1757

**Additional context**
[log-2021111121412704.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7523429/log-2021111121412704.txt)

**Comment by AlanArteche** [comment]
Buenas tardes, @luisvalencia95 , después de realizar pruebas, se detectó un bug en la instrucción ReplaceTextVisible el cual no tenía relación con la presencia de tablas en la hoja a modificar, sino que hacía falta una validación para celdas vacías.

Se probaron también las instruccion ReplaceText y ReplaceCharacter y no se presentaron problemas.

A continuación muestro el libro de Excel original con el que se realizó la prueba.

![image](https://user-images.githubusercontent.com/48565879/142294344-2a9d021e-ec9f-4b96-b5eb-fcdebd06777b.png)

El script de FRIDA ejecutado fue el siguiente:

![image](https://user-images.githubusercontent.com/48565879/142294483-31a9643f-82d1-4647-9f16-8750a14748eb.png)

Finalmente, una captura del libro de Excel después de haber sido modificado por las instrucciones:

![image](https://user-images.githubusercontent.com/48565879/142294623-17e15182-f483-4e39-a82f-fb27295a8651.png)

¿Requieres que te envíe un update que tenga este cambio aplicado?

**Comment by luisvalencia95** [comment]
Si, por favor. 

Para probarlo, aunque hablando con @jorgergarciaf creo que funcionaría mejor en este caso la funcion replace all ya que lo que necesito es reemplazar parte de las formulas de toda la hoja, cuando la aplico manualmente me dice que hubo como 180,000 coincidencias.

**Comment by AlanArteche** [comment]
Listo, ya te asigné una nueva versión, favor de confirmar para dar cierre al ticket.

**Comment by luisvalencia95** [comment]
Listo, gracias
