### ISSUE TITLE
[BUG][Mail] Se leen correos previamente procesados con el cambio de versión

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#176]
**Describe the bug**
Función ReadMailNew con parámetro **unread mails** comenzó a leer correos previamente procesados aún y cuando estaban marcados como leídos

**To Reproduce**
```
GetHome
Mail Connect to mail service "correo@dominio.com" with the password "******"
Mail ReadMailNew and get "attachment" from unread mails in the folder "Reembolso Vales" that fulfills the filter "Reembolso_Edenred" in the "subject" and save as "<<<home>>>Downloads\Reembolso" finally marked as read

```

**Bug information**
Migramos de la versión 2021**0831**T0133 a la 2021**1109**T1854 y comenzó este comportamiento

**Expected behavior**
No procesar correos/transacciones que ya previamente habían sido procesadas

**Screenshots**
![image](https://user-images.githubusercontent.com/54807268/141386031-294f3269-7ee9-4808-8288-085f69804809.png)

**Desktop (please complete the following information):**
 - Version de Turing 2021**1109**T1854

**Comment by AlanArteche** [comment]
Qué tal, Rubén, lo estaré revisando, hubieron cambios recientes pero no deberían estar impactando comportamientos anteriores.

**Comment by AlanArteche** [comment]
Qué tal, @rubenleal , se aplicó una modificación para este detalle y ya debería estar funcionando en próximas versiones de Turing, ¿requieres que envíe un update a tu usuario para probar el resultado?

**Comment by rubenleal** [comment]
Hola @AlanArteche, sí, mándamela por favor y al usuario eva@hebmex.com

**Comment by AlanArteche** [comment]
Disculpa, @rubenleal , olvidé avisar que ya se asignó una nueva versión, así que favor de confirmar el funcionamiento para poder dar cierre a este ticket. Saludos.

**Comment by rubenleal** [comment]
Se confirma funcionamiento de la nueva versión, gracias.
![image](https://user-images.githubusercontent.com/54807268/143052343-79c906ec-f12e-4844-a9b1-5ff81dc57ebe.png)
