### ISSUE TITLE
Añadir funcion de getlast Row de una tabla específica[Mejora]

### ISSUE THREAD

**Issue by luisvalencia95** [FridaSupport/CognitiveTestingMX#177]
Me pueden ayudar a crear una instruccion de GetSpecial lasRow pero de una tabla específica. Actualmente no hay una funcion que me diga el ultimo renglon de una tabla más corta que otra, solo puedo saber el último renglon de toda la hoja. @jorgergarciaf

**Comment by jorgergarciaf** [comment]
Se creó instrucción TableGetSpecial para obtener ultima fila y ultima columna.

Sintaxis
Excel TableGetSpecial lastRow from WS table Table2 and save as UltimoReg
Excel TableGetSpecial lastCol from WS table Table1 and save as UltimoReg

https://frida-admin.web.app/Documentation/Readers/ExcelReader/TableGetSpecial

Se asignó version con instruccion.

**Comment by luisvalencia95** [comment]
No está funcionando como lo esperado, me regresa 19 cuando el último renglon de la tabla es 22.

Creo que l doucumentación en frida-admin está mal. Ahí pone el comando: 

"TableGetSpecial lastRow from wsheet and save as LRow" sin especificar el nombre de la tabla a analizar.
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/LUIS~1.VAL/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/LUIS~1.VAL/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<title>Project Valuation Tool - V 6.3 - Multicurrency &lt; 50 Rows</title>
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



$ USD | ######## | ######## | ######## | $      67.27 | 3,550 | $      20.41 | $      59.93
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**Comment by jorgergarciaf** [comment]
Documentacion modificada

![image](https://user-images.githubusercontent.com/50213195/142918616-bb8563ea-e4c6-435e-a861-d07b32ac5793.png)

**Comment by luisvalencia95** [comment]
Ya lo cierro, gracias.
