### ISSUE TITLE
ReplaceAll para formulas[Mejora]

### ISSUE THREAD

**Issue by luisvalencia95** [FridaSupport/CognitiveTestingMX#178]
Me pueden ayudar a crear una nueva funcion de Replace All pero que pueda actuar en todas las formulas de las tablas de una hoja, de tal forma que pueda remplazar parcialmente las formulas por algo más o por vacío por favor. @jorgergarciaf

**Comment by jorgergarciaf** [comment]
Se creó ReplaceAllText para reemplazar texto de toda la hoja de calculo, un rango en especifico o las tablas existentes, ya sea en valores o formulas

https://frida-admin.web.app/Documentation/Readers/ExcelReader/ReplaceAllText

Se valida con @luisvalencia95 y se confirma correcto funcionamiento

**Comment by luisvalencia95** [comment]
Validado, gracias
