### ISSUE TITLE
 Eliminar información en celdas 

### ISSUE THREAD

**Issue by RocioPina** [FridaSupport/CognitiveTestingMX#179]
¿Cómo puedo borrar información de celdas sin que se me mueva las columnas y renglones en excel? , me habian dicho que usara el write y vacio pero a veces lo hacia y otras no,¿ hay alguna otra manera de hacer eso?

**Comment by ErlikC** [comment]
Hola Rocio. Con ClearCells.
La documentación está mal, pero ya en un rato la corregimos.

**Comment by jorgergarciaf** [comment]
Se actualiza documentacion para la instruccion ClearCells

https://frida-admin.web.app/Documentation/Readers/ExcelReader/ClearCells

![image](https://user-images.githubusercontent.com/50213195/143657035-8562f7f6-5391-4a18-951d-df9455faca52.png)

**Comment by ErlikC** [comment]
Hola @RocioPina, te sirvió la instrucción?

**Comment by ErlikC** [comment]
Quedamos atentos si surge algo mas
