### ISSUE TITLE
FRIDA no guarda después de un tiempo[BUG][Excel/Browpet/Titanium]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#181]
**Describe the bug**
Al intentar hacer un guardado de algún cambio, FRIDA se queda colgado intentando guardar

**To Reproduce**
la verdad no sé cual es el "trigger" de esto, de repente se quiere guardar y se queda colgado

**Bug information**
no hay un process id en espécifico

![00d9c7d2-fd66-419c-b0de-f9eb811b686f](https://user-images.githubusercontent.com/54727278/149369725-acc1eff6-20fe-43e1-ae69-d3eb20ccb5c3.jpg)

**Expected behavior**
Guardar sin problemas

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20211209T0555

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by ErlikC** [comment]
Ya se anda trabajando en unos cambios en UI que parece resuelven este tema entre otros. En cuanto estén listas las pruebas y sea liberado les informamos para hacer el update.

**Comment by ErlikC** [comment]
Se cambio la interfaz. En la nueva versión quedó resuelto esto.
