### ISSUE TITLE
[BUG][Excel]

### ISSUE THREAD

**Issue by mireyna** [FridaSupport/CognitiveTestingMX#183]
**Describe the bug**
En el Proccess Id **18129375** con la versión de Frida **20211117T1317** 
en HEB produce el siguiente error:
2022-01-18T15:26:01.8864092Z 1/18/2022 9:13:30 AM - Excel CopyPaste values_and_number_formats wsEdoCta B10991:J52508 to wsPayments K130 visible : Running
2022-01-18T15:26:01.8865804Z 1/18/2022 9:13:31 AM - Error in CopyPaste
2022-01-18T15:26:01.8867960Z 1/18/2022 9:13:31 AM - Error : No cells were found.
2022-01-18T15:26:01.8869882Z 1/18/2022 9:13:31 AM -    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
2022-01-18T15:26:01.8870913Z    at Microsoft.Office.Interop.Excel.Range.SpecialCells(XlCellType Type, Object Value)
2022-01-18T15:26:01.8872546Z    at ExcelReader.ExcelExecute.CopyPaste(String action) in C:\Users\erlik.corona\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 6745
2022-01-18T15:26:01.8873638Z 1/18/2022 9:13:31 AM - Excel CopyPaste values_and_number_formats wsEdoCta B10991:J52508 to wsPayments K130 visible : Error

Pero mi local no marca error, si se ejecuta correctamente 
1/19/2022 10:58:56 AM - Excel CopyPaste values_and_number_formats wsEdoCta B10991:J52508 to wsPayments K130 visible : Running
1/19/2022 10:58:57 AM - Excel CopyPaste values_and_number_formats wsEdoCta B10991:J52508 to wsPayments K130 visible : Success

**To Reproduce**
```
if (("<<<Periodo>>>" -eq "0") -OR ("<<<Periodo>>>" -eq "3"))
	Excel FilterHeader {wsEdoCta} column_index {1} range {Table7} criteria {No procesado}
end
Excel FilterHeader {wsEdoCta} column_index {7} range {Table7} criteria {Pago}
## Se copia informacion de la hoja EDO CTA a Payments
Excel CopyPaste values_and_number_formats wsEdoCta B<<<FPagos>>>:J<<<TRegEdoCta>>> to wsPayments K<<<LastRegPayment>>> visible	
```				

**Bug information**
En el Proccess Id **18129375** con la versión de Frida **20211117T1317** 

**Expected behavior**
Se espera que se copie la información visible

**Screenshots**

**Desktop (please complete the following information):**
 - Version de Turing [20211117T1317]

**Additional context**
[](url)

**Comment by mireyna** [comment]
[](url)[
[log-2022011916521977.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7899754/log-2022011916521977.txt)
[log afirme (1) (1).txt](https://github.com/FridaSupport/CognitiveTestingMX/files/7899756/log.afirme.1.1.txt)
[Conciliación Afirme_2022_0_15012022_1052 - Copy.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/7899757/Conciliacion.Afirme_2022_0_15012022_1052.-.Copy.xlsx)
](url)

**Comment by ErlikC** [comment]
Probamos mismo turing (20211117T1317), mismo archivo pero una en tu local, en mi local y el de heb.
Solo en heb muestra el error de "No cells were found."
Me suena a que la version de excel tiene que ver. Y también el hecho de que se trabaje con Tables puede ser la causa.

Voy a investigar si hay reportes de cambio de comportamiento debido a la versión de excel.

**Comment by ErlikC** [comment]
Adicional a esto... puedes probar esto porfa en heb. Solo para comprobar que no hayan factores externos (otros xlsx) que provoquen la diferencia.
<<arc>> es mi variable del proceso donde le mando el archivo, pero puedes ponerlo directo si prefieres.

```

Excel LoadWBook "<<arc>>" as wb

Excel LoadWSheet wb sheet "EDO CTA" as wsEdoCta
Excel LoadWSheet wb sheet "Payments" as wsPayments

Excel GetSpecial lastRow  from wsEdoCta and save as TRegEdoCta
Excel GetSpecial {wsEdoCta} appearance {first} of {Pago} in_index_column {7} and_save_as {FPagos} start_at {20}
Excel GetSpecial lastRow from wsPayments and save as LastRegPayment
LastRegPayment++

Excel FilterHeader {wsEdoCta} column_index {7} range {Table7} criteria {Pago}
Excel CopyPaste values_and_number_formats wsEdoCta B<<<FPagos>>>:J<<<TRegEdoCta>>> to wsPayments K<<<LastRegPayment>>> visible
```

**Comment by ErlikC** [comment]
Hola seguimos con este problema?
Pudiste correr el script que mandé para validar que se repita el comportamiento?

**Comment by mireyna** [comment]
Se solucionó poniendo validaciones antes de aplicar el filtro y copypaste, se valida que hay información con el filtro a aplicar antes de aplicarlo
