### ISSUE TITLE
Obtener usuario que ejecuta script [Mejora]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#185]
**Es una idea de mejora relacionada a un problema actual? por favor descríbe.**
Hay bots que se ejecutan bajo demanda, y a veces fallan, entonces para dar soporte o informar al usuario no tenemos forma de saber quien lo ejecutó

**Describe la idea o solución ideal**
sería posible una función que nos regrese quien ejecutó el bot

**Describe alternativas que hayas considerado**
Hay otras alternativas de solución para el problema?

**Additional context**
Agrega información adicional, screenshots, videos, archivos de ejemplo para reproducir el inconveniente.

**Comment by gantonioid** [comment]
a qué te refieres bajo demanda? estamos hablando de que tienes Turing Watchers atendiendo peticiones externas por medio de RunProcess?

**Comment by heber-solis** [comment]
hay procesos que no se pueden calendarizar en azure, entonces se ejecutan cuando el usuario lo necesite, para esto, el usuario instala FRIDA en su máquina le damos acceso a un script, donde el script manda una petición REST a la API de Azure y ejecuta el pipeline, pero en el log no nos aparece quien lo ejecutó

**Comment by eva-ti** [comment]
@gantonioid hay procesos que se ejecutan por varios usuarios, ahorita no sabemos quién los ejecuta, tenemos que entrar a Cognitive y ver qué usuario hizo la última ejecución. Se nos ocurría que podía aparecer el usuario (correo) que lo ejecutó en la parte superior del log, sin embargo, hay procesos que ejecutan los usuarios bajo demanda y lo que hacemos es enviar la petición hacia un servidor para evitar que el bot se ejecute en la máquina del usuario y el continúe con sus actividades.

Por lo anterior, queremos una variable con el usuario (ej. GetUser) que ejecuta para que cuando el usuario ejecute el proceso bajo demanda, desde ahí podamos trasladar la variable como parámetro de entrada al proceso que corre en el servidor.

**Comment by gantonioid** [comment]
pero lo ejecutan con sus pipelines, no me queda claro si quedaría en nuestro control con FRIDA... cómo obtenemos ese dato?

Erlik está viendo detalles con heber y si quieren coordinamos una llamada.


De pronto, se me ocurre que el pipeline deje un archivo txt local con el nombre del usuario y Turing lo lea como parte del RPA... 

de casualidad usan FRIDA TASK? https://marketplace.visualstudio.com/items?itemName=FridaPlatform.FridaTask

**Comment by ErlikC** [comment]
Se creo la instrucción GetUser as "<varame>" que guarda en la variable el correo del usuario.
