### ISSUE TITLE
Error al intentar cambiar script SQL[BUG]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#187]
**Describe the bug**
Explicación clara y concisa del error.
Al querer modificar un script de sql en la linea 32, al cambiar un 59 por 60 y guardar marca "logical structure not correct" y al intentar guardarlo otra vez, marca "There's nothing to be saved" y al cerrar el script y volverlo a abrir, no se guardó el cambio que se quería hacer, el script al correrlo directamente en SQL funciona correctamente
[script SQL.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/8081336/script.SQL.txt)

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
![image](https://user-images.githubusercontent.com/54727278/154302834-09394c09-eb46-441f-aede-d2486bd55c63.png)

**Desktop (please complete the following information):**
 - Version de Turing 20220215T1100

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by gantonioid** [comment]
debe de ser que como es txt no se sabe que el script dentro es SQL... en la línea 21 y 22 tienes IF, lo cual creo que causa el problema

@ErlikC se puede guardar el archivo como tipo .sql ? y que eso evite el analizador de sintaxis para estructuras lógicas

**Comment by ErlikC** [comment]
voy a revisar que implica esto

**Comment by ErlikC** [comment]
Hola, ya generé una versión que puede guardar archivos como .sql
![image](https://user-images.githubusercontent.com/60276982/155199346-a8a42d2a-99a0-41aa-b79d-df764cd450fd.png)

**Comment by heber-solis** [comment]
muchas gracias Erlik, se la puedes enviar a rleal, practicantebi,practicanterpa  @hebmex.com y a mi por favor? :D
