### ISSUE TITLE
No se pueden editar scripts en sección "Your automations"[BUG]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#188]
**Describe the bug**
Al querer editar un script en la sección your automations los botones aparecen deshabilitados

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
![image](https://user-images.githubusercontent.com/54727278/155014471-49738f10-3ba9-4d67-a858-c5a6723893d5.png)

**Desktop (please complete the following information):**
 - 20220215T1100

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by ErlikC** [comment]
Listo Heber. Te mandé el update a ti y a Ruben.

Saludos

**Comment by heber-solis** [comment]
muchas gracias!
