### ISSUE TITLE
No existe forma de acceder a Password Vault[BUG][Excel/Browpet/Titanium]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#189]
**Describe the bug**
en versiones anteriores podíamos acceder a la password vault desde el menú lateral pero ahora no se ve alguno 

**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
![image](https://user-images.githubusercontent.com/54727278/155014599-4ee0a8b0-452a-44cd-8149-d065119ad660.png)

**Desktop (please complete the following information):**
20220215T1100

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by ErlikC** [comment]
El acceso ahora es únicamente por Cognitive.
