### ISSUE TITLE
No se puede acceder al password Vault[BUG][Password Vault]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#190]
**Describe the bug**
Al correr un proceso, este no puede acceder a la password vault 

**To Reproduce**
Correr un proceso desde la linea de comandos, por ejemplo
:\Turing\App\TuringExpo.exe 4479287 -areaid 7830660| Out-Null
$LASTEXITCODE

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
![image](https://user-images.githubusercontent.com/54727278/156024397-73f1f2f0-1493-4505-8ce6-b54883f1a498.png)

**Desktop (please complete the following information):**
 - Version de Turing 20220225T1413

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by ErlikC** [comment]
Ya tengo el cambió, te lo asigno a ti para que valides y luego me dices a que otras cuentas lo asignamos.
