### ISSUE TITLE
[Mejora]Crear función para grabar de excel a PDF

### ISSUE THREAD

**Issue by mireyna** [FridaSupport/CognitiveTestingMX#191]
Buenos días se solicita crear la instrucción save as de excel a pdf, ya que se nos solicitó un bot para grabar de excel a pdf, y revisando las instrucciones de excel si se puede grabar a Pdf

Saludos y Gracias por sus atenciones

![image](https://user-images.githubusercontent.com/91275783/156035597-efa5ea58-456e-4a31-bd9d-f2f104484bec.png)
[PruebaSaveAsPdf.pdf](https://github.com/FridaSupport/CognitiveTestingMX/files/8155659/PruebaSaveAsPdf.pdf)
[PruebaSaveAsPdf.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/8155660/PruebaSaveAsPdf.xlsx)

**Comment by ErlikC** [comment]
Hola, ya envié el update.
Saludos

**Comment by gantonioid** [comment]
@mireyna algún comentario? ya probaste?

**Comment by ErlikC** [comment]
ya cerramos el ticket?
