### ISSUE TITLE
Error en instrucción Background Color [BUG][Excel]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#192]
**Describe the bug**
buen día, la instrucción Background color, parece no ser válida en la versión 20220301T1612 y en versiones anteriores no ocurre este problema

**To Reproduce**
Tu script o instruccioens que tienen la falla
Excel BackgroundColor from {ConsolidadoCopiaHoja1} range {C2:C1737} to {255,230,153} visible : Running
22/03/2022 16:05:31 - Syntax Error in BackgroundColor from {ConsolidadoCopiaHoja1} range {C2:C1737} to {255,230,153} visible
22/03/2022 16:05:31 - Excel BackgroundColor from {ConsolidadoCopiaHoja1} range {C2:C1737} to {255,230,153} visible : Error

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Qué esperabas como resultado?

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
 - Version de Turing 20220301T1612

**Additional context**
Máquina física, VDI/Máquina virtual, Desatendido, Turing Listener, Mail Watcher, Scheduling

**Comment by ErlikC** [comment]
De acuerdo a la documentación, esa sintaxis no es válida. Visible no se puede poner en la sintaxis de rango.
