### ISSUE TITLE
Permitir la carga de un GRID con datos donde se puedan insertar datos como parámetros

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#2]
Esto mediante un archivo excel donde se vacíen todos los datos necesarios para ejecutar el script y en caso de necesitar una plantilla diferente de datos, solo se modifique el excel y se inicie el script

**Comment by gantonioid** [comment]
DataDriven?
@andresCruzF

**Comment by FridaSupport** [comment]
Sí, es data driven
