### ISSUE TITLE
La aplicación FRIDA se cierra inesperadamente

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#20]
Al momento de dar clic en "Edit Instructions" o en "Run" se inhibe la interfaz por unos segundos hasta que causa su cierre.

**Comment by julio-soto-0517** [comment]
Versión: 20190812T1159

**Comment by RickProductivity** [comment]
Ya se resolvió este tema?

**Comment by julio-soto-0517** [comment]
Buen día, este problema se solía presentar de manera intermitente, si bien no afecta a la creación y ejecución de scripts, ya que al cerrar y abrir nuevamente FRIDA, se puede trabajar normalmente, por otro lado, actualmente este problema se presenta cada vez menos.
