### ISSUE TITLE
El espacio al hacer Tab es muy grande y agregar funcionalidad con los avpag

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#21]
- Disminuir el espacio que se hace cuando se al incluir un tab para mejor organizacion del codigo.
al usar la tecla avpag para ir por secciones en el código,  hace scroll hasta el final del codigo, sería bueno que se fuera por secciones para revisar el mismo

**Comment by gantonioid** [comment]
Todas las ideas y mejoras relacionadas con el editor de scripts, pueden ser solventadas usando la extensión de VSCode
