### ISSUE TITLE
Incluir operador matemático %

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#22]
incluir este operador para obtener el residuo de una division y poder guardarlo en una variable

**Comment by RickProductivity** [comment]
Hola Heber cómo dura para que lo utilizas ?

**Comment by heber-solis** [comment]
Hola, pues la otra vez, queríamos dividir entre 2 un valor y si el residuo fuera 0 pues que hiciera algo

**Comment by Johhnn117** [comment]
Hole Heber, empezaremos a trabajar en la mejora que solicitas.

**Comment by Johhnn117** [comment]
Hola Heber, la función que buscas es la siguiente
if ((4 % 2 ) -eq 0)
(Aqui va lo que quieras ejecutar en caso de que sea cero)
end

**Comment by heber-solis** [comment]
muchas gracias!
