### ISSUE TITLE
Ana Alvarado <anaalvarado@hebmex.com> no puede utilizar FRIDA

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#23]
Al abrir la aplicación se muestra el splash screen de FRIDA y tras unos segundos, se cierra y no la puede abrir.
Tenemos esta oportunidad desde la sesión de entrenamiento del 31Julio, pueden contactar a Ana vía Teams (ana.maria.alva11@gmail.com)

**Comment by Johhnn117** [comment]
Ana ya cuenta con su Turing funcional
