### ISSUE TITLE
Bug scroll Chromium

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#24]
se adjunta imagen en la que se muestra que en el caso uno, cuando se está ejecutando el script, no se muestra la página en su totalidad, es por eso que no se ve el fondo del scroll,  y en el caso 2 es tomado desde google chrome donde se muestra correctamente el final de la página
 
[Evidencia scroll.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/3623665/Evidencia.scroll.zip)

![Evidencia scroll](https://user-images.githubusercontent.com/54727278/65083251-ab4b1d00-d96d-11e9-9028-0bdcdc72c799.png)

**Comment by gantonioid** [comment]
Las nuevas versiones de Browpet tienen la instrucción de SetViewPort, para ajustar las dimensiones de la ventana
