### ISSUE TITLE
RenameFile de Mixed Reader no permite poner una variable como nombre

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#27]
me lanza error al intentar hacer esto

`RenameFile "C:\Users\MX02689\Downloads\test.zip" with "C:\Users\02689\Desktop\Test<<<Reporte>>>.xlsx" and save as "NewFileName"`

> - error: RenameFile "C:\Users\MX02689\Downloads\inf044_MERKardexdeArticulo.pdf" with "C:\Users\MX02689\Downloads\NuevoArchivo15:11.pdf" and save as "NewFileName" : System.NotSupportedException: The given path's format is not supported.
>    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
>    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
>    at System.IO.FileInfo.MoveTo(String destFileName)
>    at MixedReader.MixedExecute.RenameFile(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 2815
> 9/25/2019 3:11:35 PM - RenameFile "C:\Users\MX02689\Downloads\inf044_MERKardexdeArticulo.pdf" with "C:\Users\MX02689\Downloads\NuevoArchivo15:11.pdf" and save as "NewFileName" : Error
> 9/25/2019 3:11:37 PM - Execution ended

**Comment by gantonioid** [comment]
Por favor adjuntar siempre los logs al reportar errores

**Comment by heber-solis** [comment]
una disculpa, ya adjunté el log

**Comment by gantonioid** [comment]
El error que te marca se debe a que quieres hacer el rename con caracteres inválidos, en tu caso los dos puntos ':'
`The given path's format is not supported.`
![image](https://user-images.githubusercontent.com/9600868/69667156-13e00580-1053-11ea-9941-c5deb5e9f18e.png)
