### ISSUE TITLE
La opción Schedule cierra la aplicación

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#28]
Al dar clic en el botón **Schedule** para programar la ejecución de un script, FRIDA se cierra inesperadamente.

Versión: 20190920T1242

**Comment by gantonioid** [comment]
Por favor poner screenshot o mandar link a un vídeo para ver qué pasos estás siguiendo para configurar un scheduling

**Comment by julio-soto-0517** [comment]
Adjunto documento con capturas
[Issue 28.docx](https://github.com/FridaSupport/CognitiveTestingMX/files/3672403/Issue.28.docx)

**Comment by gantonioid** [comment]
Corregido en nuevas versiones
