### ISSUE TITLE
Definir variables al inicio del script donde se permita indicar tipo de dato, su valor, descripción 

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#3]
Esto se refiere a las variables que se crean en la seccion de EDIT VARIABLES, las cuales son accesadas con `<<variable>>` ya que si se comparte un script con este tipo de variables, la persona a la que se le comparte, tiene que volver a dar de alta estas varibles si las quiere utilizar

**Comment by gantonioid** [comment]
Te refieres a configurarle un valor default para que ya venga llena esta parte?
![image](https://user-images.githubusercontent.com/9600868/64255094-524ba580-cee6-11e9-94f3-1e29e947364f.png)

Al compartir un script, la plataforma se encarga de distribuir esos cambios que hiciste en EDIT VARIABLES para todas las computadoras que lo usen. ¿Puedes dar más detalle de a qué te refieres?

**Comment by heber-solis** [comment]
esto se refiere a que por ejemplo cuando creas una variable en la sección de EDIT VARIABLES y compartes el script, la persona a la que se lo compartes tiene que volver a hacer el proceso de dar de alta las variables, entonces pues la idea es que se comparta con todo y las variables

**Comment by gantonioid** [comment]
Esto se implementó para variables de contraseña en PasswordVault (inicios del año 2020), pero podrías usarla para compartir variables aunque no se trate de contraseñas.
