### ISSUE TITLE
FRIDA se cierra cuando guardas o al ejecutar un script

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#30]
al guardar y al querer correr un scrpt se traba la aplicación y despues de 1 minuto mas o menos se cierra la aplicación

**Comment by andresCruzF** [comment]
Se agrego una vista de error para cuando la aplicación presenta un problema en la ventana de edit instructions para evitar este error.

**Comment by andresCruzF** [comment]
Hola @heber-solis , me podrias confirmar tu numero de version de Turing y el script que te encuentras queriendo ejecutar para poder empezar a realizar un diagnostico ?

**Comment by heber-solis** [comment]
Hola Andrés es esta 20200312T0609 , de momento no recuerdo que con esta versión me haya pasado, pero lo que si me ha pasado es que por ejemplo, abro un script, y quiero copiar el process id dandole doble clic a este y segundos después se cierra FRIDA
