### ISSUE TITLE
Conversión de variable String, dar formato y convertir a numérico

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CognitiveTestingMX#31]
Con "Web2 Extract" obtengo el valor en string de el precio de un artículo ejemplo "$250"

Con que instrucción puedo eliminar el simbolo de $ y después convertir a número el valor para realizar operaciones como una suma de precios.

Adicional en caso de usar JS utilizando "Web2 Evaluate" donde puedo saber que valor tiene la variable "Web2Output"

Gracias.

**Comment by Johhnn117** [comment]
Hola @raulhgit para eliminar el simbolo puedes usar la instrucción 

ApplyRegex "<Regex>" to the string "<String>" and save as "<VarName>"

de la siguiente forma

ApplyRegex "[0-9]+" to the string "(Aqui va la variable)" and save as "(El nombre de la variable)"

haciendo eso ya puedes usar el valor con 

MathOperation <Number1> + <Number2> and save as <Result>

**Comment by FridaSupport** [comment]
@raulhgit Te funcionó? para cerrar el issue
