### ISSUE TITLE
Mandar llamar scripts

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#32]
Por ejemplo se tienen 20 scripts para una aplicacion hay posibilidad de en vez de agregar 20 veces la funcionalidad para el login, hacer esa funcionalidad en un solo script y mandar llamarlo como cuando se ejecuta un powershell o un .bat

**Comment by gantonioid** [comment]
Sí la hay
[RunScript](http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/RunScript)
`RunScript Write.txt`

**Comment by gantonioid** [comment]
Pondrías algo como 
```
...codigo
...codigo
RunScript Login.txt
...codigo
```

Así tienes por separado todo el fragmento de script que contiene la funcionalidad de login que comentas, y la incluyes dentro de todos los que requieran ese fragmento.

Pero tienes que agregarlo a cada uno de los procesos usando el boton de **Add Files** en Turing
