### ISSUE TITLE
The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CognitiveTestingMX#33]
[Error403Turing.docx](https://github.com/FridaSupport/CognitiveTestingMX/files/3833341/Error403Turing.docx)

Al ejecutar cualquier prueba aparece el error en Turing.  Al cerrar y abrir la aplicación se actualizó pero aun así continua el error.

Por web si se tiene acceso al portal de Cognitive Testing

**Comment by gantonioid** [comment]
Lo resolvimos, Favor de ajustar el reloj de tu máquina local. Los tokens de conexión a la plataforma deben de hacer match de hora local vs hora servidor, en parte por seguridad.
