### ISSUE TITLE
Instrucción Excel SortColumn para ordenamiento múltiple está inactiva

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#35]
Se valida la instrucción para realizar ordenamientos de múltiples columnas, sin embargo, al ejecutarla, solo aparece "Error", por lo que se piensa se encuentra inactiva: 
SortColumns in WSName1 in UsedRange by columns {1/ascending,2/descending,3/descending} header Yes

**Comment by FaustinoLechuga** [comment]
Se activo la función y se realizaron algunas pruebas para comprobar el buen funcionamiento de esta. Debido a esto cierro el ticket.
