### ISSUE TITLE
GetHome varía ubicación

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#36]
La ubicación de Home varía de usuario a usuario, hay algunos que lo toma en C:\Users\Usuario y a otros se lo toma como C:\Users\usuario\One Drive\Desktop y a otros se los toma como C:\Users\usuario\One Drive

De qué depende esto?

**Comment by gantonioid** [comment]
Tienes scripts y logs que nos den más info?

**Comment by heber-solis** [comment]
de momento no :/ pero pues el caso es así 
GetHome as home
<<<home>>>Downloads
y en el log el valor varía según cada quien, 
esto de GetHome, de casualidad depende de como se tenga configurada la variable de entorno Home?  será por eso que varía de usuario a usuario?

**Comment by gantonioid** [comment]
Sí, se utilizan las variables de ambiente para esto. Cómo están configuradas en estos casos de error que reportas?

**Comment by heber-solis** [comment]
no sabría decirte, se me acaba de ocurrir esto de la variable de entorno, pero supongo que con eso se resuelve el "error". Es que no puedo checar ni mis variables de entorno por que nos quitaron permisos de admin

**Comment by ErlikC** [comment]
Hola
Es correcto, el valor se toma de las variables de entorno.
Puedes validar con (Tecla Windows)+r -> cmd -> set
La variable USERPROFILE indica la ubicación que te arroja getHome.

**Comment by rubenleal** [comment]
> Hola
> Es correcto, el valor se toma de las variables de entorno.
> Puedes validar con (Tecla Windows)+r -> cmd -> set
> La variable USERPROFILE indica la ubicación que te arroja getHome.

![GetHome](https://user-images.githubusercontent.com/54807268/77788451-e61dc400-7026-11ea-8e53-85f46fbfd97f.png)

Se formateó mi máquina hace unas semanas, y antes y después me marca lo mismo, no sé qué tengo configurado pero al menos el CMD me devuelve correctamente la ruta, pero FRIDA no.

Me encuentran en Teams como rleal@hebmex.com por si quieren revisar algo adicional.

**Comment by gantonioid** [comment]
Se envió el update `20200327T0958` a @rubenleal con un fix

**Comment by rubenleal** [comment]
> Se envió el update `20200327T0958` a @rubenleal con un fix

Funcionando, muchas **gracias**!
27/03/2020 04:07:26 p. m. - GetHome as "home": Running
27/03/2020 04:07:26 p. m. - Se agrego una nueva variable : 
Var Name : home
Value : C:\Users\L041409\
