### ISSUE TITLE
Agregar sheet_index a RemoveSheets

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#37]
Agregar la opción de indicar el sheet index a la instrucción Excel Remove Sheets ya que causa conflicto cuando se tiene diferencia de idiomas en excel, por ejemplo cuando el sheet-name es "Sheet1" en inglés y en español "Hoja1"

**Comment by gantonioid** [comment]
Puedes usar una combinación de instrucciones, no?
Por ejemplo:

1. LoadWSheet por index (como lo mencionas)
2. ChangeWSName a un nombre fijo que no varíe por el idioma
3. RemoveSheets

**Comment by heber-solis** [comment]
fue lo que le dije ayer, pero pues dice Rubén que prefiere que esa instrucción tenga sheet-index

**Comment by Johhnn117** [comment]
Buen día,

Ya está implementada la sintaxis para eliminar hojas de acuerdo al indice.

`Excel RemoveSheets from TestBook sheet_index 1`

Se añadirá la instrucción para que aparezca en el autocomplete pero la instrucción ya se encuentra en funcionamiento.
