### ISSUE TITLE
Permitir a instrucciones de Excel pegar solo valores

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#38]
En la instrucción de Excellium "Excel WriteFormula" hay un atributo que permite agregar solo los valores o resultados consecuentes de una determinada fórmula, sin embargo, al intentar probar con un "if" anidado, se marca un error en la ejecución. A continuación, dejo un log con la ejecución de esta fórmula con y sin el atributo "paste only value": 

**Con paste only value:** 

2/7/2020 11:56:09 AM - Excel Write "Existencias" in hojaDatos1 in cell J1: Running
2/7/2020 11:56:09 AM - Excel Write "Existencias" in hojaDatos1 in cell J1 : Success
2/7/2020 11:56:09 AM - Excel WriteFormula hojaDatos1 in J2:J279 formula "=VLOOKUP(A2,'C:\Users\MX02688\Downloads\[HEB.Star__HEB.Star_0702202011_54_46.xlsx]RepGralArtXSuc'!B:V,20,FALSE)" paste only value: Running
2/7/2020 11:56:10 AM - Excel WriteFormula hojaDatos1 in J2:J279 formula "=VLOOKUP(A2,'C:\Users\MX02688\Downloads\[HEB.Star__HEB.Star_0702202011_54_46.xlsx]RepGralArtXSuc'!B:V,20,FALSE)" paste only value : Success
2/7/2020 11:56:10 AM - #Columna "Departamento": Running
2/7/2020 11:56:10 AM - #Columna "Departamento" : Success
2/7/2020 11:56:10 AM - Excel Write "Departamento" in hojaDatos1 in cell K1: Running
2/7/2020 11:56:10 AM - Excel Write "Departamento" in hojaDatos1 in cell K1 : Success
2/7/2020 11:56:10 AM - Excel WriteFormula hojaDatos1 in K2:K279 formula "=IF(A2="0","", IF(A2="", "",VLOOKUP(A2,'C:\EVA\[ReporteGeneralArt_STAR.xlsx]RepGralArtXSuc'!A:C,2,FALSE)))" paste only value: Running
2/7/2020 11:56:10 AM - Error WriteFormula hojaDatos1 in K2:K279 formula "=IF(A2="0","", IF(A2="", "",VLOOKUP(A2,'C:\EVA\[ReporteGeneralArt_STAR.xlsx]RepGralArtXSuc'!A:C,2,FALSE)))" paste only value
2/7/2020 11:56:10 AM - **Excel WriteFormula hojaDatos1 in K2:K279 formula "=IF(A2="0","", IF(A2="", "",VLOOKUP(A2,'C:\EVA\[ReporteGeneralArt_STAR.xlsx]RepGralArtXSuc'!A:C,2,FALSE)))" paste only value : Error**
2/7/2020 11:56:10 AM - Catch Block Running

**Sin el paste only value:**

2/7/2020 12:16:36 PM - #Columna "Existencias": Running
2/7/2020 12:16:36 PM - #Columna "Existencias" : Success
2/7/2020 12:16:36 PM - Excel Write "Existencias" in hojaDatos1 in cell J1: Running
2/7/2020 12:16:36 PM - Excel Write "Existencias" in hojaDatos1 in cell J1 : Success
2/7/2020 12:16:36 PM - Excel WriteFormula hojaDatos1 in J2:J279 formula "=VLOOKUP(A2,'C:\Users\MX02688\Downloads\[HEB.Star__HEB.Star_0702202012_15_10.xlsx]RepGralArtXSuc'!B:V,20,FALSE)" paste only value: Running
2/7/2020 12:16:37 PM - Excel WriteFormula hojaDatos1 in J2:J279 formula "=VLOOKUP(A2,'C:\Users\MX02688\Downloads\[HEB.Star__HEB.Star_0702202012_15_10.xlsx]RepGralArtXSuc'!B:V,20,FALSE)" paste only value : Success
2/7/2020 12:16:37 PM - #Columna "Departamento": Running
2/7/2020 12:16:37 PM - #Columna "Departamento" : Success
2/7/2020 12:16:37 PM - Excel Write "Departamento" in hojaDatos1 in cell K1: Running
2/7/2020 12:16:37 PM - Excel Write "Departamento" in hojaDatos1 in cell K1 : Success
2/7/2020 12:16:37 PM - Excel WriteFormula hojaDatos1 in K2:K279 formula =IF(A2="0","", IF(A2="", "",VLOOKUP(A2,'C:\EVA\[ReporteGeneralArt_STAR.xlsx]RepGralArtXSuc'!A:C,2,FALSE))): Running
**2/7/2020 12:16:39 PM - Excel WriteFormula hojaDatos1 in K2:K279 formula =IF(A2="0","", IF(A2="", "",VLOOKUP(A2,'C:\EVA\[ReporteGeneralArt_STAR.xlsx]RepGralArtXSuc'!A:C,2,FALSE))) : Success**

Nótese que la fórmula para ambos casos es la misma, y esta regresa el resultado esperado al ejecutar, sin embargo, al tener la fórmula, se agrega peso al archivo final.

**Comment by julio-soto-0517** [comment]
Resultado final con la fórmula mostrada en el log (sin paste only value): 

![image](https://user-images.githubusercontent.com/54809099/74071933-dd1b5980-49ca-11ea-9d21-0c85d4f4df6a.png)

**Comment by julio-soto-0517** [comment]
Actualización:
Siguiendo el ejemplo en la documentación de la instrucción para escribir fórmulas (WriteFormula <wskey> in <rangekey> formula "<formula>" paste only value),
anexo aquí otro ejemplo de fórmula en la cual no puede ejecutarse el atributo "paste only value" para la fórmula "SUBSTITUTE":

3/23/2020 11:58:40 AM - #Excel Write "Barcodes (Sin comillas)" in hojaFiltros cell M1 : Success
3/23/2020 11:58:40 AM - Excel WriteFormula hojaFiltros in M2:M979 formula "=SUBSTITUTE(B2,CHAR(34),"")" paste only value: Running
3/23/2020 11:58:40 AM - Error WriteFormula hojaFiltros in M2:M979 formula "=SUBSTITUTE(B2,CHAR(34),"")" paste only value
3/23/2020 11:58:40 AM - Excel WriteFormula hojaFiltros in M2:M979 formula "=SUBSTITUTE(B2,CHAR(34),"")" paste only value : Error
3/23/2020 11:58:40 AM - Catch Block Running

**Comment by ErlikC** [comment]
Hola.
La función WriteFormula tiene la siguientes variantes:
`WriteFormula <wskey> in <rangekey> formula "<formula>"`
`WriteFormula <wskey> in <rangekey> formula <formula>`
`WriteFormula <wskey> in <rangekey> formula "<formula>" paste only value`
`WriteFormula <wskey> in <rangekey> formula <formula> paste only value`
 
La regla que podríamos tomar en cuenta para considerar si encerrar <formula> entre comillas o no, es que la misma formula no debería tener comillas de forma interna, de lo contrario se mostrará como error.

En los ejemplos que agregas:
Excel WriteFormula hojaFiltros in M2:M979 formula "=SUBSTITUTE(B2,CHAR(34),`""`)" paste only value 

o en

Excel WriteFormula hojaDatos1 in K2:K279 formula "=IF(A2=`"0"`,"", IF(A2=`""`, `""`,VLOOKUP(A2,'C:\EVA[ReporteGeneralArt_STAR.xlsx]RepGralArtXSuc'!A:C,2,FALSE)))" paste only value : Error

**Comment by rubenleal** [comment]
@ErlikC tienen alguna fecha estimada de solución a este tema?
¿Podría ser que FRIDA en lugar de utilizar comillas utilizara algún otro caracter como las llaves {} que utilizan otras funciones de Excellium?

**Comment by ErlikC** [comment]
En realidad la solución fue la explicación de como usar la sintaxis.
El hecho de agregar llaves, sería una nueva sintaxis que debe ser codificada, por el momento no esta considerada como prioridad, dado que la otra sintaxis funciona, pero puedo revisar si se le puede dar prioridad.

**Comment by ErlikC** [comment]
Voy a agregar la sintaxis para que se puedan usar las llaves. Proximamente estaré enviando la actualización, si se requiere.

**Comment by ErlikC** [comment]
La funcionalidad ya fue creada. Quieres que te mande actualización?

**Comment by ErlikC** [comment]
Aunado con ticket #46,  se creo versión, por lo tanto queda resuelto el ticket.

**Comment by rubenleal** [comment]
Excelente! Muchas gracias @ErlikC, me la mandas, no sé si ya la tiene también @julio-soto-0517

**Comment by ErlikC** [comment]
cual es tu usuario?

**Comment by rubenleal** [comment]
> cual es tu usuario?

rleal@hebmex.com

**Comment by ErlikC** [comment]
Listo, ya te envié la misma versión que tiene  @julio-soto-0517.
Saludos.

**Comment by rubenleal** [comment]
@ErlikC me puedes confirmar la nueva sintaxis y ayudarme a actualizar los Readers por favor:
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/WriteFormula

**Comment by ErlikC** [comment]
Ya actualice la documentación.
`WriteFormula <worksheetKey> in <rangeKey> formula {<formula>}`
`WriteFormula <worksheetKey> in <rangeKey> formula {<formula>} paste only value`
