### ISSUE TITLE
DownloadEmbedded no descarga imagen

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#39]
La instrucción no me está descargando una imagen, ya probé poniendo la instrucción varias veces y lo unico que hace es abrir una pestaña nueva con la imagen que se quiere descargar, pero no descarga la imagen

**Comment by gantonioid** [comment]
Esa instrucción abre la dirección que viene indicada en el attr src del tag en una ventana nueva. El comportamiento que presentas es el esperado.

Si quieres la imagen usa un screenshot

**Comment by heber-solis** [comment]
necesitamos descargar la imagen, el screenshot toma la imagen con un fondo negro y eso no es lo que se busca. Son 5000 imágenes entonces editar una por una pues tampoco es una opción hay alguna alternativa para descargar la imagen?

**Comment by gantonioid** [comment]
Tal vez algún código que puedas insertar con Evaluate  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download
