### ISSUE TITLE
Delete character no permite borrar espacios

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#40]
Quiero eliminar los espacios en "Upgrade de Kronos" para terminar en "UpgradedeKronos" será el nombre de un archivo.

El código:
#Variable a recortar
DefineVariable type "string" as "N1" with the value "Upgrade de Kronos"
#Se recorta string y se guarda en una variable
Delete character " " in the string "<<<N1>>>" and save as "Resultado"
#Se imprime la variable
SystemNotify Type "Notification" with message "<<<Resultado>>>"
 
El error (no tolera espacios el borrado):
String cannot be of zero length.

**Comment by Johhnn117** [comment]
Buen día,
Se añade un cambio en la sintaxis para poder eliminar los espacios sin que exista confusión por parte de la instrucción
```
DefineVariable type "string" as "Empty" with the value "Prueba para eliminar los espacios"
Delete character "<blank>" in the string "<<<Empty>>>" and save as "Empty"
```

En vez de poner literalmente el espacio se pone `<blank>` para que se pueda identificar y lo elimine del string, te mando un update para que tengas este cambio.

Saludos
