### ISSUE TITLE
Agregar espera hasta que elemento sea clickeable

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#41]
Sería posible agregar esta funcionalidad a FRIDA?
WebDriverWait wait = new WebDriverWait(Scenario1Test.driver, 10); 
WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("(//div[@id='brandSlider']/div[1]/div/div/div/img)[50]")));
element.click();
Actualmente solo se tiene el ElementExists pero este solo indica si el elemento está presente, pero no se espera hasta que este elemento sea clickeable.

**Comment by oscarlaureano** [comment]
Ya se puede agregar un timeout al click para que vuelva a buscar en caso de no encontrar algún elemento: http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/Click
