### ISSUE TITLE
Asignar tiempo en ElementExists

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#42]
Permitir asignar el tiempo que deberá esperar ElementExists en decir si un elemento es encontrado o no

**Comment by oscarlaureano** [comment]
Ya se puede agregar un timeout para que vuelva a buscar el elemento: http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/ElementExists

**Comment by RickProductivity** [comment]
Gracias
