### ISSUE TITLE
Fórmula sin "@" para filtros de búsqueda y ordenamientos

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#43]
En las fórmulas de búsqueda y ordenamientos se muestra un signo de "@" durante la ejecución, lo cual no permite ver todos los valores filtrados de un determinado rango de celdas. Se muestra aquí un ejemplo: 

![image](https://user-images.githubusercontent.com/54809099/77367769-7656c300-6d20-11ea-9061-e283a960a1c5.png)

Por otro lado, la fórmula que aplico en este ejemplo no es un solo valor, sino varias columnas siendo ordenadas, a las cuales no se le ingresa el delimitador. Aquí muestro el log.

3/23/2020 4:06:48 PM - Excel WriteFormula hojafinal1 in A2:L979 formula "=SORTBY(ExistenciasAyer!A2:M10000,ExistenciasAyer!N2:N10000,1,ExistenciasAyer!O2:O10000,-1,ExistenciasAyer!J2:J10000,-1)": Running
3/23/2020 4:06:48 PM - Excel WriteFormula hojafinal1 in A2:L979 formula "**=SORTBY(ExistenciasAyer!A2:M10000,ExistenciasAyer!N2:N10000,1,ExistenciasAyer!O2:O10000,-1,ExistenciasAyer!J2:J10000,-1)**" : Success

**Comment by ErlikC** [comment]
Hola. 
Esto es la conclusión a la que he llegado después de leer el funcionamiento de SORTBY.
Esta función que nació en 2018, es una de las llamadas Dynamic Array Function. Que son funciones nuevas que reemplazan la necesidad de funciones CSE (Ctrl+Shift+Enter) en funciones de arreglos, las cuales había que seleccionar previamente el rango donde se depositaría el resultado de la función, escribir la formula y presionar esa combinación de teclas.

La documentación indica que si se crea la formula en una versión de Excel que no soporta las DAs, al abrir el documento Excel en una versión que si las soporte, se mostrará un @ al inicio. Que es el [Operador de Intersección Implicita](https://support.office.com/en-us/article/implicit-intersection-operator-ce3be07b-0101-4450-a24e-c1c999be2b34). Es decir, la función arreglo, solo se aplica para la celda en especifico y no como un rango de celdas. 

Mi suposición es que las librerías para manejo de Excel no soportan aun estas funciones DA y eso es lo que provoca el comportamiento que observas. 
La sugerencia es realizar el ordenamiento de las celdas usando otro método.

Se tiene una funcionalidad nueva, que aun está pendiente por liberarse llamado SortColumns, con el que se podrá ordenar asc/desc en un maximo de 3 columnas. Si gustas, podemos acabar las pruebas para liberar este funcionamiento y te actualizaría tu versión de Turing para que lo puedas usar.

**Comment by ErlikC** [comment]
Listo, me dices si estas en posibilidad de que te libere versión o ya tienes otro workaround.

**Comment by julio-soto-0517** [comment]
Hola, 
Enterado, muchas gracias por la retroalimentación.  Efectivamente hice un workaround, consiste básicamente en usar la instrucción "Write" de Excel, en la que puedo escribir algún texto en una celda, así que probé escribir la fórmula con esa instrucción y me dio un resultado exitoso:

<img width="953" alt="captura1" src="https://user-images.githubusercontent.com/54809099/77798898-5b929000-7039-11ea-9d02-6fa3f281ec78.png">

Por otro lado, de ser posible, considero que si podrías liberar la versión para validar también su funcionamiento y tener presente en futuros scripts.

**Comment by ErlikC** [comment]
Si, claro. Cual es el correo que tienes registrado para turing?

**Comment by julio-soto-0517** [comment]
Mi correo es el siguiente: julio.soto@softtek.com

**Comment by ErlikC** [comment]
Tu versión era: 20200116T1026, te lo actualice a la versión 20200330T0955

**Comment by julio-soto-0517** [comment]
Hola, buen día,
este problema se ha presentado nuevamente en la versión: 20200414T1144
![image](https://user-images.githubusercontent.com/54809099/80035462-b511a180-84b5-11ea-8ce0-80cdbfddfff4.png)

**Comment by julio-soto-0517** [comment]
También falla para esta versión: 20200420T0632

**Comment by ErlikC** [comment]
La versión liberada fue de SortColumns, y como se explicó en https://github.com/FridaSupport/CognitiveTestingMX/issues/43#issuecomment-604034466
no hay implementación para SortBy.
