### ISSUE TITLE
Error Message: Exception from HRESULT: 0x800A01A8 en instrucciones de Excellium

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#46]
La instrucción de Excellium "_CopyColumn <indexcolumn> from <wskey> start_at <indexrow> to the sheet <wskey> in column <columnindex> start_at <rowindex>"_  presenta un error de manera intermitente. 
El caso en el que utilizo esta instrucción es para sobre escribir una columna en otra:

En esta primer imagen extraigo la columna B a la Columna P sin las comillas con esta fórmula: "=TRIM(SUBSTITUTE(B2,CHAR(34),CHAR(32)))"

![image](https://user-images.githubusercontent.com/54809099/78385817-b6783a00-7599-11ea-9056-a8a16dce7655.png)

En esta segunda imagen se pasa la columna P a la columna B sin las comillas
![image](https://user-images.githubusercontent.com/54809099/78385895-dc9dda00-7599-11ea-883d-229d53e1e7d7.png)

Sin embargo,  hay ocasiones en que las ejecuciones automáticas, me regresan el log con error: 

```
03/04/2020 8:51:50 - #Barcodes sin comillas: Running
03/04/2020 8:51:50 - #Barcodes sin comillas : Success
03/04/2020 8:51:50 - Progress : 0
03/04/2020 8:51:50 - Excel WriteFormula ExistenciasHoy in P2:P2245 formula "=TRIM(SUBSTITUTE(B2,CHAR(34),CHAR(32)))" paste only value: Running
03/04/2020 8:51:50 - Excel WriteFormula ExistenciasHoy in P2:P2245 formula "=TRIM(SUBSTITUTE(B2,CHAR(34),CHAR(32)))" paste only value : Success
03/04/2020 8:51:50 - Progress : 0
03/04/2020 8:51:50 - #Copia y pega sin comillas: Running
03/04/2020 8:51:50 - #Copia y pega sin comillas : Success
03/04/2020 8:51:50 - Progress : 0
03/04/2020 8:51:50 - Excel CopyColumn 16 from ExistenciasHoy start_at 1 to the sheet ExistenciasHoy in column 2 start_at 1: Running
03/04/2020 8:51:51 - Number of rows copied: 2245
03/04/2020 8:51:51 - Error message:    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.Copy(Object Destination)
   at ExcelReader.ExcelExecute.CopyColumn(String action) in C:\Users\jonathan.camacho\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 20346
03/04/2020 8:51:51 - **Error message: Exception from HRESULT: 0x800A01A8**
03/04/2020 8:51:51 - Excel CopyColumn 16 from ExistenciasHoy start_at 1 to the sheet ExistenciasHoy in column 2 start_at 1 : Error
```

En ocasiones, se suele presentar otro error como este: _Error message: Exception from HRESULT: 0x800A03EC_

```
03/04/2020 12:03:06 - Excel CopyColumn 16 from ExistenciasHoy start_at 1 to the sheet ExistenciasHoy in column 2 start_at 1: Running
03/04/2020 12:03:16 - Number of rows copied: 2245
03/04/2020 12:03:16 - Error message:    at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure , CallSite , Object , Int64 , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at ExcelReader.ExcelExecute.CopyColumn(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 20363
03/04/2020 12:03:16 - Error message: Exception from HRESULT: 0x800A03EC
03/04/2020 12:03:16 - Excel CopyColumn 16 from ExistenciasHoy start_at 1 to the sheet ExistenciasHoy in column 2 start_at 1 : Error
```

Cabe mencionar que no es la única instrucción que ha presentado este tipo de errores, también instrucción como WriteFormula y AutoFit 

```
4/3/2020 11:10:15 AM - #Formula final : Success
4/3/2020 11:10:15 AM - Excel CopyPaste hojaFiltros Q2:AB1786 to ExistenciasHoyF A2 paste only value: Running
4/3/2020 11:10:16 AM - Excel CopyPaste hojaFiltros Q2:AB1786 to ExistenciasHoyF A2 paste only value : Success
4/3/2020 11:10:16 AM - SystemNotify Type "Notification" with message "Copia resultados filtrados en hoja nueva configurada": Running
4/3/2020 11:10:16 AM - SystemNotify Type "Notification" with message "Copia resultados filtrados en hoja nueva configurada" : Success
4/3/2020 11:10:17 AM - Excel AutoFit ExistenciasHoyF by column: Running
4/3/2020 11:10:17 AM - Exception from HRESULT: 0x800AC472
4/3/2020 11:10:17 AM - Error CopyPaste hojaFiltros P2:P1786 to hojaFiltros B2
4/3/2020 11:10:17 AM - Excel AutoFit ExistenciasHoyF by column : Error
```

**Comment by ErlikC** [comment]
Hola, me puedes compartir el ID de tu proceso y si es posible una copia de algún archivo de excel que utilice, para realizar pruebas.
CopyColumn recientemente fue corregido en un error como el que te ocurre, pero los otros parecen ser nuevos.

**Comment by julio-soto-0517** [comment]
Hola, 
sí, claro, el proceso original es: 1322247317, el cual es un script de producción, lo tengo programado para ejecutar cada ciertas horas diariamente. 
Por otro lado tengo este otro proceso donde exclusivamente pruebo la parte de las instrucciones de Excellium y las fórmulas, el cual es este: 850973050

Estos son los exceles que utilizo como ejemplo en el segundo proceso : 

El primer excel es en el que se hace la parte de las columnas y las fórmulas
[Ejemplo-Cornershop.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/4440914/Ejemplo-Cornershop.xlsx)

Este segundo excel es una plantilla donde se copia y pega el resultado final: 
[EVA-Cornershop-Reporte-Huecos.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/4440913/EVA-Cornershop-Reporte-Huecos.xlsx)

Cualquier duda, quedo al pendiente. ¡Saludos!

J.S.

**Comment by ErlikC** [comment]
Hice un update a CopyColumn. El error que ocurría detecté que era por que la columna A en ocasiones  podría estar vacía, lo cual provocaba el error que mencionas.
Esto se debía a un mal manejo de UsedRange, que es el grupo de celdas con información en la hoja. Esto, dentro del código.
Sigo intentando reproducir escenarios con Autofit y WriteFormula, para darles una corrección.

Si gustas que te envíe una versión de turing, con gusto te la propociono.

Saludos.

**Comment by ErlikC** [comment]
Se realizaron correcciones a WriteFormula.

**Comment by julio-soto-0517** [comment]
Hola, enterado, muchas gracias, y claro, ¿podrías enviarme la actualización? 
Quedo al pendiente. 
Saludos.

J.S.

**Comment by ErlikC** [comment]
Claro. Tenías versión 20200331T0729, se actualizó a la versión 20200414T1144.

**Comment by gantonioid** [comment]
Te sirvió la actualización @julio-soto-0517 ? podemos cerrar el ticket?

**Comment by julio-soto-0517** [comment]
Hola, buen día,
Efectivamente la última actualización me ha servido mucho. 
¡Muchas gracias por su apoyo! 
¡Saludos!

J.S.
