### ISSUE TITLE
Instrucción GoTo no me deja ingresar a un FTP

### ISSUE THREAD

**Issue by rodolfopze** [FridaSupport/CognitiveTestingMX#48]
usando browpet en FRIDA tengo esto:
Web2 GoTo "ftp://ftphebmx.heb.com.mx/" 

Al ejecutarlo me da error debido a que al abrir el navegador, captura esto: 
{"error":"Page could not be reached...Error: net::ERR_CONNECTION_TIMED_OUT at http://ftp://ftphebmx.heb.com.mx/"}

Le agrega un "http://" y yo requiero entrar a un "ftp://"
[FTP Error log.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4452654/FTP.Error.log.txt)

**Comment by oscarlaureano** [comment]
Ya se resolvió ese problema
