### ISSUE TITLE
Error en Excel Write

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#49]
estos errores son de 2 scripts diferentes que se ejecutaron sin problemas anteriormente y que no se han movido, la ultima ejecución existosa de estos fue el viernes a las 2:20 

13/04/2020 7:01:15 - Excel Write "100062" in hojaProjects in cell N1: Running 13/04/2020 7:01:15 - Error message:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)    at ExcelReader.ExcelExecute.Write(String action) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 16683

​

13/04/2020 06:50:31 a. m. - Excel Write "Existencias" in hojaDatos1 in cell J1: Running 13/04/2020 06:50:31 a. m. - Error message:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)    at ExcelReader.ExcelExecute.Write(String action) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 16683

**Comment by ErlikC** [comment]
Me puedes compartir el ID de tus procesos porfavor?

**Comment by heber-solis** [comment]
1322247317

525482892

**Comment by ErlikC** [comment]
Los scripts tienen error de sintaxis. Esta es la sintaxis correcta.
`Write "<something>" in <wsKey> cell <ColRow>`

Como veras, tu script tiene la palabra "in" en dos ocasiones.
Excel Write "100062" in hojaProjects in cell N1.
Anteriormente, había un problema con la función Write, que quitaba "in " al estar leyendo la instrucción. En ocasiones eso podía crear errores como, por ejemplo Excel Write "Mantein " ... quedaba como Excel Write "Mante", lo mismo con nombres de la hoja, terminaban con nombres inexistentes en el diccionario de variables.

Ahora lo que sucede con tu script es que se esta interpretando que tu variable de la hoja de excel se llama "hojaProjects in"  que no existe en el diccionario de variables.

**Comment by heber-solis** [comment]
En versiones anteriores si funcionaba, cambió la sintaxis? y Aldo nos regresó a una versión anterior y corre sin problemas el script, agradeceríamos alguna notificación en caso de que cambie la sintaxis de alguna función para revisar los scripts y hacer cambios de ser necesario

**Comment by ErlikC** [comment]
No, es como te explico. Antes el script por error quitaba todos los "in " en la instrucción. Y ahora ya toma los valores correctamente, por lo que piensa que tu variable se llama "hojaProjects in".

**Comment by ErlikC** [comment]
Se dio explicación del comportamiento a Aldo de igual manera, por lo tanto se cierra el ticket.
