### ISSUE TITLE
Definición de ruta en la función ScreenShot para indicar donde se guardarán las imágenes

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#5]
al momento de usar la funcion Screenshot de Browpet agregar la posibilidad de definir la ubicación en la que se guardará la captura

**Comment by gantonioid** [comment]
Ya se atendió, va a salir cuando se haga release. La documentación está actualizada por si quieren irla viendo
[http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/Screenshot](url)
