### ISSUE TITLE
Error, {"error":"Error at select. Could not find element"} 

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#50]
Estoy teniendo problemas con un select, me dice que no puede seleccionar el valor por que no lo encuentra, pero la instrucción está dentro de un if, precedido por un element exists, si el elemento existe entonces selecciona el valor, entonces entra al if por que si existe el elemento
[log.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4483201/log.txt)
el script tiene el process id  "49878199"
pudieran ayudarme por favor? gracias

**Comment by ErlikC** [comment]
Hola, las instrucciones en cuestión son:
`
Web2 ElementExists in xpath="//select[../..//text()[contains(., '22676')]]" save as "select2"
Web2 Select value="1" in xpath="//select[../..//text()[contains(., '22676')]]
`
La primera identifica que existe el objeto en la hoja.
La segunda intenta elegir el valor "1" de ese objeto. Y el error indica que no existe "1".

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/79399080-f7802f00-7f47-11ea-8a9a-734d1151ad91.png)
ese es el elemento y tiene los valores 0,1 y 2

**Comment by heber-solis** [comment]
Hola buenos días, podrías darnos un tiempo estimado de cuando estaría este fix listo? debido  a que estamos trabajando en sprints. Para comentarlo en nuestra planeación, muchas gracias

**Comment by gantonioid** [comment]
@heber-solis Si la instrucción es:
`Web2 Select value="1" in xpath="//select[../..//text()[contains(., '22676')]]`
y se relaciona con el screenshot que mandaste... yo no veo ahí por ningún lado el número 22676 como para que sea válido el xpath contains.

Yo creo que es un campo select atípico... ya probaste con un javascript inyectado con la instrucción `Web2 Evaluate`??

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/79760886-55b16700-82e6-11ea-881f-3ddd45ccac18.png)
eso es lo que trato de hacer, el 22676 es el sku del producto, que forma parte de una orden de compra, entonces solo se va a cambiar el sku, para que vaya al select que corresponde y cambie según el valor

**Comment by heber-solis** [comment]
con javascript directamente en la consola intento esto: document.evaluate(//select[../..//text()[contains(., '22676')]])  y me regresa el elemento, pero si intento: document.evaluate(//select[../..//text()[contains(., '22676')]]).selectedIndex=2 solo me regresa un 2 pero no cambia la selección, desconozco si es la forma correcta de trabajar con select en javascript, pero no me funciona

**Comment by gantonioid** [comment]
Web2 ya establece que es un Evaluate, lo que va dentro no es document.evaluate, sino ya directamente el comando que quieres, por decir:
`document.querySelector("el_Selector").selectedIndex=3`

donde "el_Selector" es del tag `<select />`, (no de `<option />`). La instrucción FRIDA completa sería

```
##elSelector = puede ser una variable que nos diga a dónde apuntar
Web2 Evaluate frame=main `document.querySelector("el_Selector").selectedIndex=3`
```
Usando xpath
```
##elxpath= puede ser una variable que nos diga a dónde apuntar
## según lo que indicas, puede ser "//select[../..//text()[contains(., '22676')]]"
Web2 Evaluate frame=main `$x('elxpath')[0].selectedIndex = 1`
```

Dicho lo anterior, por qué no usas el id o name del elemento dentro de la instrucción Web2 Select ??
![image](https://user-images.githubusercontent.com/9600868/79778598-9c12c000-82fe-11ea-9232-aa5cb51deadf.png)

Quedaría algo así:
`Web2 Select value="1" in id="picker_action_4169"`
Es mucho más fácil de leer, no?

**Comment by heber-solis** [comment]
el id no es algo fijo o algo que nosotros sepamos de donde sale, en otra orden de compra puede ser picker_action_#aleatorio, por esa razón no lo podemos usar,  usé esta linea de codigo como sugeriste 
Web2 Evaluate frame= "main" `$x('//select[../..//text()[contains(., '22676')]]')[0].selectedIndex = 1`
y me regresó este error
Evaluation failed: SyntaxError: missing ) after argument list\n    at __puppeteer_evaluation_script__:2:45"
pero no veo nada que le sobre a la linea como para que arroje eso

**Comment by gantonioid** [comment]
Se indica un error de sintaxis, fíjate en las comillas
prueba cambiar '22676' por "22676"

**Comment by heber-solis** [comment]
ahora me arroja este error
{"error":"Evaluation failed: ReferenceError: $x is not defined\n    at eval (eval at <anonymous> (:2:40), <anonymous>:1:1)\n    at __puppeteer_evaluation_script__:2:40"}
disculpa no conozco mucho de javascript

**Comment by heber-solis** [comment]
disculpa de este tema podrías apoyarme por favor?  al parecer ni con evaluate funciona, no marca error pero no hace cambio alguno 
```
esto me marca el log Web2 Evaluate frame= "main" `('//select[../..//text()[contains(., "22676")]]')[0].selectedIndex = 1`: Running
4/23/2020 3:43:59 PM - JavaScript sent
4/23/2020 3:43:59 PM - Se agrego una nueva variable : 
Var Name : web2Output
Value : 1
```
y no cambia nada en el select

**Comment by heber-solis** [comment]
ya lo resolví, en vez de select, le doy click y con las flechas selecciono el valor, pero el xpath sigue siendo el mismo
