### ISSUE TITLE
Excel  write formula escribe #NA 

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#51]
Tengo este script "1409689580" toda la ejecución la hace sin problemas, pero me escribe #N/A en la columna donde escribe una formula, pero si abro el excel y doy doble clic en la celda y me quito de ahí, se pone el valor que se esperaba.

Ya intenté con y sin paste only value.
Ya intenté poniendo el ApplyFormat antes de escribir la formula, con General, texto y Number y lo que hace es ponerme #NA y aunque me ponga en la celda se queda el #NA.
Ya intenté con un Excel Write normal y un AutoFill y es el mismo resultado.
Ya intenté copiar la columna de un lado a otro poniendo diferentes formatos que es como está actualmente el script

Si escribo la formula manualmente si me da el resultado esperado.
Adjunto los archivos utilizados en el script 
Gracias por el apoyo

[Rappi.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4489815/Rappi.zip)

**Comment by ErlikC** [comment]
Me parece que es por el ancho de la columna.  Con un AutoFit lo puedes resolver.

**Comment by heber-solis** [comment]
Pues puse el Excel AutoFit antes y despues de usar la formula y me sigue escribiendo #NA

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/79582486-6a48f180-8091-11ea-9e58-fac68825b1a3.png)
esto es lo que me pone

**Comment by gantonioid** [comment]
Oye @heber-solis no creo que #N/A sea algo que Turing maneje, de hecho es común ese error cuando las referencias en las fórmulas apuntan a lados incorrectos, tipos de datos, etc

Te paso referencia: [https://support.office.com/es-es/article/corregir-un-error-n-a-a9708411-f82e-4e1b-8a7e-28c28311b993](https://support.office.com/es-es/article/corregir-un-error-n-a-a9708411-f82e-4e1b-8a7e-28c28311b993)

**Comment by gantonioid** [comment]
Compartiste tu script? no lo veo

**Comment by heber-solis** [comment]
hola,les compartí el process id pensé que con ese podían ver el código jaja mi error, pero pues creo ya lo resolví, tuve que convertir el csv a xlsx, y pues como la conversión me deja los campos con un triangulo verde, apliqué =value a la columna de datos que quiero tomar para el value y pues ya esa la tomé para el vlookup, pero a la formula no le cambié nada, te digo si la hacía manualmente, me daba el dato que esperaba, no sé si sea por que en csv no funciona los de write formula pero intenté muchas cosas

**Comment by gantonioid** [comment]
Podemos verlo con el ID de proceso, sin embargo pedimos que adjuntes tu código que tiene el problema porque podrías estar trabajando en algún work-aroud sobre el mismo ID de proceso, que convertirían el código que nosotros recuperamos, en inválido para el escenario de error que reportas.

Se trata de tener toda la info disponible aquí mismo, gracias.

_____
Correcto, sí pudiera afectarnos el que sea CSV, porque para abrirlo sin afectar los campos que contengan fechas, todas las celdas tienen formato de texto. Hay que encontrar como manejar el archivo en ese caso. Dices que ya lo resolviste, entonces cerramos?

**Comment by heber-solis** [comment]
ok, para tenerlo en cuenta la próxima vez, muchas gracias por el apoyo, si ya podemos cerrar, gracias nuevamente
