### ISSUE TITLE
como activar Flash? 

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#52]
un sistema de HEB está hecho con Flash y se necesita activar para poder acceder a la página
![image](https://user-images.githubusercontent.com/54727278/79905230-8921ed80-83db-11ea-893e-8a6ac1b2686e.png)

anteriormente, el script lo activaba yendo a la configuración del sitio 
![image](https://user-images.githubusercontent.com/54727278/79905344-b40c4180-83db-11ea-9040-b09c93e8c1cf.png)
pero ahora sale esto, al momento de hacer el web2 GoTo
![image](https://user-images.githubusercontent.com/54727278/79905386-cbe3c580-83db-11ea-9e1a-3eae9e64fddb.png)

se podría implementar alguna función para activarlo?

**Comment by RickProductivity** [comment]
Puedes adjuntar el script que estás usando para llegar a los settings

**Comment by heber-solis** [comment]
```
##############
#Activar FLASH
##############
Web2 GoTo "http://sca2011260.ad.heb.com.mx/wfc/navigator/logon"
Web2 Navigation
Web2 GoTo "chrome://settings/content/siteDetails?site=http%3A%2F%2Fsca2011260.ad.heb.com.mx"
Web2 Navigation
for 22 times {
Web2 Key "Tab"
}
Web2 Key "Enter"
Web2 Key "ArrowDown"
Web2 Key "Enter"
```

**Comment by gantonioid** [comment]
Parece que ya no es posible desde Chrome 42
[https://support.google.com/chrome/forum/AAAAP1KN0B0yq2KNwS38n0/?hl=es](https://support.google.com/chrome/forum/AAAAP1KN0B0yq2KNwS38n0/?hl=es)

[http://www.chromium.org/developers/npapi-deprecation](http://www.chromium.org/developers/npapi-deprecation)

Vamos a ver qué opciones podemos ofrecerte para solucionarlo (tiempo de exploración)

**Comment by RickProductivity** [comment]
@heber-solis oye y si lo haces con el Desktop Recorder (Shotter) ?

**Comment by heber-solis** [comment]
@RickProductivity esto funcionaría aún si la máquina se encuentra bloqueada?

**Comment by heber-solis** [comment]
Cierro este issue por que no tiene caso implementar lo de flash ya que en diciembre será obsoleto
