### ISSUE TITLE
Element Exists no respeta el tiempo de espera 

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#53]
Tenemos el siguiente script
```
Web2 GoTo "www.google.com.mx"
Web2 InsertValue "House of heroes" in selector="#tsf > div:nth-child(2) > div.A8SBwf > div.RNNXgb > div > div.a4bIc > input"
Web2 Key "Enter"
Web2 Navigation
for 10 times{
Web2 ElementExists in xpath="//h3[@class='LC20lb DKV0Md'and contains(text(),'Wikipedia')]" save as "link"
if ("<<<link>>>" -eq "true")
Web2 Click in xpath="//h3[@class='LC20lb DKV0Md'and contains(text(),'Wikipedia')]"
end
if ("<<<link>>>" -eq "false")
Web2 Evaluate frame = "main" `window.history.back();`
end
}
```
la primera vez si se espera a ver si existen los elementos, despues ejecuta las acciones luego luego, creemos que la instruccion se queda con los valores de la primera vez, es por eso  que no vuelve a hacer la espera

**Comment by gantonioid** [comment]
Qué error sale en el log?
El history.back() dispara una navegación o cambio de página, lo cual invalida el DOM que tienes cargado en ese momento. Sugiero que pruebes poniendo un Web2 Navigation.

**Comment by gantonioid** [comment]
Tal vez incluso:
```
Web2 Evaluate frame = "main" `window.history.back();`
Web2 Reload
Web2 Navigation
```

**Comment by heber-solis** [comment]
no sale error en el log, lo que pasa es que la idea del script es probar si el ElementExists se espera los 20 segundos, Rubén me pidió hacer una prueba con esa instruccion por que el tiene otro script donde le pasa el mismo comportamiento, de que al parecer una vez que indica que es true, o false la existencia del elemento, se queda guardado dicho valor y ya no se espera a revisar si existe o no, desconozco si también usa el history.back(), usé el navigation como dijiste, pero ahora solo es mas lento el cambio que hace, pero no se espera los 20 segundos para indicar si existe el elemento o no, en el caso del false

**Comment by rubenleal** [comment]
![ElementExists20seg](https://user-images.githubusercontent.com/54807268/79989798-e5395000-8475-11ea-90c8-0c435c61c44d.png)
@gantonioid ahí se ve que en la siguiente ejecución el ElementExists ya no otorga 20seg y esa instrucción nos es de utilidad para que se espere en la carga de páginas que son lentas.

**Comment by gantonioid** [comment]
> Tal vez incluso:
> 
> ```
> Web2 Evaluate frame = "main" `window.history.back();`
> Web2 Reload
> Web2 Navigation
> ```

Probaron esto? no hubo comentario del resultado

**Comment by heber-solis** [comment]
si, no hubo cambios se espera el tiempo del navigation solamente

**Comment by rubenleal** [comment]
@oscarlaureano, me puedes enviar la nueva versión por favor, quiero probar la solución, gracias.

**Comment by oscarlaureano** [comment]
@rubenleal acabo de liberar la actualización que al parecer resuelve ese problema, favor de confirmar el correcto funcionamiento por aquí para que quede documentado y (en caso de ser efectivo) cerrar el ticket

**Comment by heber-solis** [comment]
esto si funciona con el ejemplo que puse allá arriba
ahorita no me está funcionando el timeout
```
5/20/2020 4:18:16 PM - Web2 ElementExists in selector="#maincontent > div.columns > div > div > div.product-info-wrapper > div > div.product_info_right.product-item-details > div.add-to-wrapper > div.actions-primary > form" save as "inputQty" timeout= 60000: Running
5/20/2020 4:18:25 PM - element existes
5/20/2020 4:18:25 PM - Se agrego una nueva variable : 
Var Name : inputQty
Value : false
5/20/2020 4:18:25 PM - Web2 ElementExists in selector="#maincontent > div.columns > div > div > div.product-info-wrapper > div > div.product_info_right.product-item-details > div.add-to-wrapper > div.actions-primary > form" save as "inputQty" timeout= 60000 : Success
```
tiene un timeout de 60 segundos y en 9 segundos ya me dijo que no existe, y aparte el elemento que estoy diciendole que busque, si aparece en pantalla desde hace mucho, y no está dentro de un iFrame  tengo la versión 20200512T0419

**Comment by gantonioid** [comment]
@oscarlaureano
