### ISSUE TITLE
DB RunOutputQuery requiere parámetro de timeout para scripts que tardan mucho

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#54]
Script tarda 1:34mins en arrojar resultados directo en SQL, sin embargo FRIDA a los 30seg (el default) marca error de timeout.

Se debe poder enviar el tiempo de tolerancia para responder y con ello permitir que consultas grandes no marquen error por timeout, tenemos otros scripts que tardan 10-15mins.

Comparto log de FRIDA y pantalla del tiempo en SQL.
[logTimeout.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4547862/logTimeout.txt)
![SQLTiempo](https://user-images.githubusercontent.com/54807268/80525146-5f764280-8956-11ea-840e-9ec17c4b6b8a.png)

 **Inicio en FRIDA:** 28/04/2020 **01:38:48** p. m. - DB RunOutputQuery {scriptSQL.txt} in {myDB} as {milista}: Running
 **Fin en FRIDA:** 28/04/2020 **01:39:19** p. m. - Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or

**Comment by RickProductivity** [comment]
En lo que revisamos el Cambio he visto que usemos try Catch para repetir el procedimiento , por si te pude funcionar en el Inter.
Saludos

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gantonioid** [comment]
El timeout viene relacionado con cómo pusiste el connection string
[DB Connect](http://automationplatform.azurewebsites.net/Readers/Tools/DBReader/Connect)

![image](https://user-images.githubusercontent.com/9600868/80529789-9b60d600-895d-11ea-85fb-a45462c232ab.png)

Si el problema persiste, lo revisamos

**Comment by rubenleal** [comment]
Gracias @RickProductivity en este caso creo que no me funciona el try...catch ya que es en la BD.
Gracias @gantonioid lo intenté así y mismo error, ese debe ser el timeout solo para la conexión, falta el del query.
[logTimeout2.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4548107/logTimeout2.txt)

Por ejemplo en PowerShell es:
    $command = $sqlConn.CreateCommand()
    $command.CommandText = $Query
    $adapter = New-Object System.Data.SqlClient.SqlDataAdapter $command
    #15mins de timeout para que responda con resultados la BD
    $adapter.SelectCommand.CommandTimeout=900

**Comment by gantonioid** [comment]
Ok, al update que te menciono en #56 le pondré que el timeout que traiga en el connection string, se herede a los comandos ejecutados.

**Comment by gantonioid** [comment]
Ya cerramos esto entonces?

**Comment by rubenleal** [comment]
Funcionando, se cierra, muchas gracias!
