### ISSUE TITLE
DB Connect solo acepta conexiones de SQL

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#55]
Ojalá se puedan incorporar conexiones a otras BD, en HEB tenemos también **MySQL y Oracle** como principales, entre otras.

http://automationplatform.azurewebsites.net/Readers/Tools/DBReader/Connect

Considerar que al permitir las conexiones a otras BD, quizás se tengan que cambiar también las funciones:
- RunInputQuery
- RunOutputQuery
- RunStoredProcedure

**Comment by RickProductivity** [comment]
My SQL debería ser más fácil , te sirve que priorízemos esta ?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rubenleal** [comment]
De acuerdo! Tengo una petición pendiente para MySQL, solo me deja incertidumbre de una vez que se tira el query, ¿cómo podemos trabajar los datos? Si eso lo vaciamos a un Excel directo estará genial (#56)

**Comment by gantonioid** [comment]
> De acuerdo! Tengo una petición pendiente para MySQL, solo me deja incertidumbre de una vez que se tira el query, ¿cómo podemos trabajar los datos? Si eso lo vaciamos a un Excel directo estará genial (#56)

Ese es tu otro ticket, no?

**Comment by gantonioid** [comment]
Ya está lista la compatibilidad con MySQL, Oracle será más complicado.

Te mando otro update para que lo tengas?

**Comment by gantonioid** [comment]
Solo cambia la isntrucción [Connect](http://automationplatform.azurewebsites.net/Readers/Tools/DBReader/Connect), donde le dices de qué tipo es la BD. Los valores posibles por ahora son:

- SQL_SERVER (Default)
- MY_SQL

**Comment by RickProductivity** [comment]
@rubenleal tuviste oportunidad de revisarlo?

**Comment by RickProductivity** [comment]
Gracias

**Comment by rubenleal** [comment]
Se agregó Oracle hace unas semanas 👍 
Buen trabajo!
