### ISSUE TITLE
DB RunOutputQuery no arroja los valores del array

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#56]
El objetivo es arrojar el resultado del Query en un Excel, sin embargo se presentan las siguientes cuestiones:
**1. No pude ver los valores del array en el SystemNotify.** Comparto log y video al respecto:
Reparto el tema en 2 puntos
[logArrayBD.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4548007/logArrayBD.txt)

[IssueValoresArray.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4548011/IssueValoresArray.zip)

**2. El resultado del query será un conjunto de filas y columnas (array bidimensional)**:
 - ¿Cómo se podría pasar esta información a Excel rápidamente si algunas consultas podrían traer miles de registros?

**Comment by gantonioid** [comment]
Tu script es correcto, te puedo mandar un update?

Para pasarlo a Excel, te serviría _Excel WriteVariableValue_ 
```
DB Connect to DB connectionstring={connStr} name={midb}
DB RunOutputQuery {db_out.txt} in {midb} as {query}

foreach row in query{
##Esto se soluciona con un update
	Message <<<row[1]>>>
	Titanium Sleep 500
}

GetHome
Excel LoadWBook "<<<home>>>Downloads/libro.xlsx" as book
Excel LoadWSheet book sheet_index 1 as sheet
Excel WriteVariableValue {query} in {sheet} start_at_row {1} start_at_column {1}
SystemNotify Type "Notification" with message "Ya está en Excel"
```

**Comment by rubenleal** [comment]
Sí, mándame el update por favor, gracias @gantonioid

**Comment by gantonioid** [comment]
Se te asignó la v.20200428T0836

**Comment by rubenleal** [comment]
Funciona @gantonioid, ¡eres genial! 
Solamente estoy extrañando los encabezados de las columnas, ¿cómo se los agrego al Excel?

**Comment by gantonioid** [comment]
Puedes hacer Excel Write para cada columna, creo que es consistente el orden en el que los trae el query, no? Si no, puedes especificar en el query el orden que quieres
```
Select Email, first_name, ID
From pruebas.usuarios
```
o

```
Select ID, first_name, Email
From pruebas.usuarios
```

Así te lo trae en un orden específico, lo pones dentro de tu txt del query

**Comment by rubenleal** [comment]
Perdón, no entendí bien, en el txt tengo el query y las columnas ordenadas de cierta manera, pero, ¿hay posibilidad de que el mismo query imprima los encabezados en el Excel? Así, si actualizo el query tengo todo bien alineado en el Excel, en caso contrario, entiendo que con el Write, tendría que actualizar el query + el script de FRIDA para mover los encabezados, ¿no?

**Comment by gantonioid** [comment]
No, el query no trae los headers. Solo los valores. Pero mi respuesta anterior asumía que conocías los nombres de los headers, y puedes entonces escribirlos en tu hoja de Excel. La escritura de la tabla con Excel WriteVariable que te había dicho, solo le podrías que lo haga en la row 2.
```
Excel Write Header1...
Excel Write Header2...
Excel Write Header3...
Excel Write Header4...
Excel WriteVariableValue {query} in {sheet} start_at_row {2} start_at_column {1}
```

Aprovechando esto fresco, hice que los queries además de guardar la tabla de valores en tus variables, se te estará guardando otra (en el fondo) que se llama "query_field_names", de tipo lista, y tendrá los nombres de las columnas. Puedes iterarlas o manejarlas como cualquier otra variable lista.

**Comment by gantonioid** [comment]
Te asigno la versión `20200429T1221` para que tengas lo de `query_field_names`

**Comment by rubenleal** [comment]
Funciona muy bien, gracias, aquí el script final como me quedó:
#Conexión a BD
DB Connect to DB connectionstring={Server=SCD201001;Database=BDCMP;User Id=consulta;Password=consulta;Connection Timeout=900;} name={myDB}
DB RunOutputQuery {scriptSQL.txt} in {myDB} as {query}

#Lógica para colocar el resultado del query en el Excel
GetHome
Excel LoadWBook "<<<home>>>Downloads/libro.xlsx" as book
Excel LoadWSheet book sheet_index 1 as sheet
Excel WriteVariableValue {query} in {sheet} start_at_row {2} start_at_column {1}

#Lógica para colocar los encabezados en el Excel
DefineVariable type "int" as "i" with the value "1"
foreach header in query_field_names{
	Excel Write "<<<header>>>" in sheet row 1 and column <<<i>>>
	MathOperation <<<i>>> + 1 and save as i
}

SystemNotify Type "Notification" with message "Ya está en Excel"
