### ISSUE TITLE
Error en proceso calendarizado

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#57]
Cuando se ejecuta un script calendarizado mientras Turing está abierto, el proceso se ve interrumpido debido a un error en la consola.

**Comment by gantonioid** [comment]
Puedes compartir el error que mencionas de la consola?

**Comment by heber-solis** [comment]
no es un error en la consola, cuando se calendariza un proceso y este se ejecuta, y FRIDA está abierto aparece un error como tipo 
SystemNotify 
siempre olvido tomarle captura cuando aparece

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/81295590-45afbc00-9036-11ea-9b2e-90f564ce5ab5.png)
este es, no se corrió un proceso ayer a las 7 pm y hoy a las 6:52 por este error

**Comment by julio-soto-0517** [comment]
Se hizo prueba en otro proceso y se muestra la ventana emergente anterior mencionada. 
[eva-07-05-2020-10-27.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4594035/eva-07-05-2020-10-27.zip)

**Comment by FaustinoLechuga** [comment]
Hola Julio, el problema con la ejecución del Turing calendarizado aun persiste?

**Comment by julio-soto-0517** [comment]
Hola Faustino, buen día,
Sí, de hecho el problema persiste, si bien, en una de las versiones funciona bien, en otra, al llegar a la hora calendarizada con Turing abierto, no me aparece ningún error ni muestra de que se haya ejecutado, este inconveniente suele ocurrir de forma intermitente.

Adjunto aquí dos vídeos de las calendarizaciones que realicé en dos equipos, una en una máquina virtual (la cual se ejecutó correctamente) y otra en mi máquina (no se muestra nada a menos que cierre frida, prueba que también hice con el task scheduler y me mostró el mismo resultado).

Prueba exitosa (Versión de turing: 20200527T0913):
[Prueba-Script-con-horario-M90.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4703411/Prueba-Script-con-horario-M90.zip)

Prueba fallida (Versión de turing: 20200429T1221):
[Prueba-Script-con-horario-failed.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4703537/Prueba-Script-con-horario-failed.zip)

**Comment by julio-soto-0517** [comment]
Muchas gracias, Faustino,
Respecto a mi versión de Turing, actualmente no tengo tarea en específico con esta versión, estaría bien si pudieras mandar updates.
¡Saludos!
J.S.

**Comment by FaustinoLechuga** [comment]
Okay, por lo que vi ese tema ya quedo resuelto con versiones posteriores, te hare mandare un update a esta version 20200527T0913, estas de acuerdo?

**Comment by gantonioid** [comment]
Sí @FaustinoLechuga por favor

> Muchas gracias, Faustino,
> Respecto a mi versión de Turing, actualmente no tengo tarea en específico con esta versión, **estaría bien si pudieras mandar updates**.
> ¡Saludos!
> J.S.

**Comment by FaustinoLechuga** [comment]
Se le asigno esa versión ese mismo dia, @julio-soto-0517 funciono correctamente con esa version?
