### ISSUE TITLE
ApplyFilter with empty no filtra

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#58]
tengo este excel
![image](https://user-images.githubusercontent.com/54727278/81320873-7b18d180-9057-11ea-8fdd-336d6bdeefaf.png)
cuenta con 12,000 registros, quiero filtrar estos registros que están en blanco y copiarlos a otro excel
usé esta sentencia
Excel ApplyFilterWithEmpty to the worksheet {ResultadosQuery} to the column with the index {1} with the criteria {=VALUE} and copy their value on {RappiEmpty}

y en el log me marca que no tiene valor, entonces cuando va a escribirlo al otro excel truena por que no escribe nada 
Excel ApplyFilterWithEmpty to the worksheet {ResultadosQuery} to the column with the index {1} with the criteria {=VALUE} and copy their value on {RappiEmpty}: Running
07/05/2020 10:59:51 a. m. - Var Name : RappiEmpty
Value : 

si es correcta la sintaxis?

**Comment by Johhnn117** [comment]
Se encontró un workaround con Heber que dio el resultado esperado

**Comment by RickProductivity** [comment]
Podrías Documentar el Work Around?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by heber-solis** [comment]
fue con Excel If empty put "Eliminar"
ApplyFilter "=Eliminar" y esos ya los elimino
