### ISSUE TITLE
No cerrar el navegador por default, que sea a través de una función

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#6]
Al momento de terminar la ejecucion del script se cierra automaticamente el navegador, sería bueno que se agregara un checkbox como el de "headless" para evitar que se cierre y hacer operaciones manuales de ser necesario

**Comment by gantonioid** [comment]
Puedes poner pausas en tus scripts para lograr que no se cierre. Nosotros debemos terminar limpiando para no dejar cabos sueltos.
