### ISSUE TITLE
Extensión de VS Code pierde formato al identar

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#60]
Al identar el código los comentarios dejan de ser verdes y pasan a color blanco, no recuerdo haber visto este comportamiento hasta esta semana. Comparto video:
[ExtensiónFRIDA.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4610516/ExtensionFRIDA.zip)

Extensión utilizada:
https://github.com/AntonyFagundez/Frida

**Comment by gantonioid** [comment]
Gracias por el reporte. Se considerará para la siguiente versión de la extensión. Sin fecha estimada.
