### ISSUE TITLE
No puedo abrir FRIDA despues de actualizar

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#61]
actualicé FRIDA y al querer abrirlo me aparece este mensaje
![image](https://user-images.githubusercontent.com/54727278/81697699-d74e6d80-942a-11ea-9b67-8eaebbb2c06c.png)

ya revisé que no haya otra instancia corriendo antes de querer abrirlo

**Comment by rubenleal** [comment]
Mismo tema en otro equipo donde se tienen procesos calendarizados:
![image](https://user-images.githubusercontent.com/54807268/81703556-61e69b00-9432-11ea-9925-ba2476d381a2.png)

**Comment by heber-solis** [comment]
Al parecer el TuringExpo.exe se corrompió, Jonathan ya me pasó un ejecutable limpio y se resolvió el problema

**Comment by Johhnn117** [comment]
los dos Turing ya están corriendo con normalidad, corroborado por @heber-solis  y @rubenleal
