### ISSUE TITLE
Formato de fecha en Excel se cambia

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#62]
Se realizó una prueba ingresando una fecha manual en el Excel y otra con fórmula, en el caso de la fórmula Excel muestra el formato esperado de acuerdo a la configuración de Windows (dd/mm), pero en la escrita a pesar del formato escrito, se muestra al revés (mm/dd).

![image](https://user-images.githubusercontent.com/54807268/81818783-17c5ee00-94f4-11ea-9711-31c87ea24007.png)

**Comment by gantonioid** [comment]
Eso es de esperarse, porque depende de la configuración de idioma de la máquina.

Puedes primero aplicar un formato de texto a las celdas y luego escribir? A ver si te sirve

**Comment by ErlikC** [comment]
Estuve realizando pruebas y efectivamente es un bug en la instrucción.
El workarround que encontré es un truco muy "excel". Puedes poner una comilla sencilla antes, para que lo tome como texto.
`Excel Write "'12/05/2020" in WS cell A2`
No se si te sea útil, de todos modos sigo trabajando para ver como corregir esto.

**Comment by ErlikC** [comment]
Hola. Les tengo un update en el tema.
Tengo este resultado de usar una combinación distinta de formatos en las celdas.
![image](https://user-images.githubusercontent.com/60276982/81960546-ba569d80-95d6-11ea-85d2-760fc3811f6d.png)


El script usado fue este

```
Excel LoadWBook "<<arc>>" as WB
Excel LoadWSheet WB sheet "Sheet1" as WS

Excel Write "12/05/2020" in WS cell A1
Excel WriteFormula WS in A2 formula "=Today()"

Excel ApplyFormat from WS in_column_index 2 format @
Excel Write "12/05/2020" in WS cell B1
Excel WriteFormula WS in B2 formula "=Today()"

Excel Write "12/05/2020" in WS cell C1
Excel WriteFormula WS in C2 formula "=Today()"
Excel ApplyFormat from WS in_column_index 3 format @

Excel ApplyFormat from WS in_column_index 4 format mm-dd-yyyy
Excel Write "12/05/2020" in WS cell D1
Excel WriteFormula WS in D2 formula "=Today()"

```

Ahora la explicación. Write hasta cierto punto toma en cuenta el formato de la celda (General, Texto, etc.). De forma default todo es General, con lo cual hace una interpretación del texto a escribir y si lo puede ver como numero, pega un número, si es texto lo pega tal cual, pero para fechas siempre interpreta usando el formato de US, por lo que tenemos el resultado que reportan. 

Si inicialmente damos formato a la columna para indicar que es texto. Todo se pega como texto. Pero entendería si el hecho de que =Today() ya no se pegue como formula, sea un problema para ustedes.

Usar ApplyFormat despues de escribir los Write. Provoca que tome las fechas como numero (que internamente son numero de días desde 1/1/1900), y por esta razón se muestran los 44170.

Por otro lado, como ven en la columna D. No importó que inicialmente ponga el formato mm-dd-yyyy. Write interpreta primero el valor como formato gringo y luego le da a la celda el formato indicado.

Se que lo ideal es que si dicen Write "12/05/2020", se escriba exactamente eso, y excel interprete correctamente la fecha de acuerdo a la configuración local. Por compatibilidad, no puedo hacer el cambio así tan directo, por que podría pegar en bots productivos y los workorround que hayan realizado.

Propongo una sintaxis especifica para cuando sea necesario formatear fechas o algo mas, por ejemplo 
**Write "12/05/2020" in WS cell E1 with format dd/mm/yyyy.** 
La idea es que el resultado sea así.
![image](https://user-images.githubusercontent.com/60276982/81963501-cb091280-95da-11ea-93bf-e686af96492a.png)

```
Excel ApplyFormat from WS in_column_index 5 format dd/mm/yyyy
Excel Write "12/05/2020" in WS cell E1 with format dd/mm/yyyy
Excel WriteFormula WS in E2 formula "=Today()"

```

**Comment by ErlikC** [comment]
Ya hice el cambio. Dejo algunos ejemplos de la sintaxis. Hace uso de formato del modo que applyFormat lo hace, pero especifico para la celda y no toda la columna.
![image](https://user-images.githubusercontent.com/60276982/81976604-6952a380-95ee-11ea-98e2-65c7d4c37d4c.png)


```
Excel Write "12/05/2020" in WS cell E1
Excel Write "12/05/2020" in WS cell E2 with format dd/mm/yyyy
Excel WriteFormula WS in E3 formula "=Today()"
Excel Write "12/05/2020" in WS cell E4 with format [$-es-MX]dddd, d" de "mmmm" de "yyyy
Excel Write "12/05/2020" in WS cell E5 with format dd-mmm

Excel Write "12345678" in WS cell F1 with format #,###.00
Excel Write "15" in WS cell F2 with format [Red][<100]0;[Blue][>=100]0 
Excel Write "115" in WS cell F3 with format [Red][<100]0;[Blue][>=100]0 
Excel Write "1" in WS cell F4 with format [=1]0" día";0" días"
Excel Write "2" in WS cell F5 with format [=1]0" día";0" días"

```

**Comment by ErlikC** [comment]
Podemos cerrar el ticket?

**Comment by rubenleal** [comment]
Una disculpa @ErlikC, buen trabajo!
Copié el último código que me compartes y me marca error en la última línea:
20/05/2020 06:13:43 p. m. - Excel Write "2" in WS cell F5 with format [=1]0" día";0" días: Running
20/05/2020 06:13:43 p. m. - Error message:    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.set_NumberFormat(Object )
   at ExcelReader.ExcelExecute.Write(String action) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 16926
20/05/2020 06:13:43 p. m. - Unable to set the NumberFormat property of the Range class
20/05/2020 06:13:43 p. m. - Error message: Unable to set the NumberFormat property of the Range class
20/05/2020 06:13:43 p. m. - Excel Write "2" in WS cell F5 with format [=1]0" día";0" días : Error

Tengo versión: **20200519T0702**

**Comment by ErlikC** [comment]
Gracias.
Por lo que veo falta cerrar las comillas.

**Comment by rubenleal** [comment]
Eso era, se cierra el issue, gracias por el apoyo @ErlikC
