### ISSUE TITLE
OutOfMemory en DBReader - RunOutputQuery

### ISSUE THREAD

**Issue by gantonioid** [FridaSupport/CognitiveTestingMX#63]
A Rubén le aparece un error de memoria cuando se ejecuta un query que resulta en medio millón de filas.
```
14/05/2020 19:04:02 - Connection failed
14/05/2020 19:04:02 - Exception of type 'System.OutOfMemoryException' was thrown.
14/05/2020 19:04:02 - DB RunOutputQuery {SQL.txt} in {myDB} as {query} : Error
```
![image](https://user-images.githubusercontent.com/9600868/82065161-5d6ced00-9693-11ea-94e0-a551d3b0a989.png)

**Comment by gantonioid** [comment]
@rubenleal te mandé un update para probar si se arregla. Hice un ajuste en el reader basado en esta referencia.
[CommandBehavior](https://docs.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=netcore-3.1&viewFallbackFrom=dotnet-plat-ext-3.1)

**Comment by heber-solis** [comment]
a mi me está arrojando ese mismo error, tengo la version 20200527T0913

**Comment by gantonioid** [comment]
De qué tamaño es el resultado de tu consulta @heber-solis ?
la de rubén es de +500,000 y funciona correctamente la primera vez, el error de memoria es después.

**Comment by heber-solis** [comment]
200980, también le quité la instrucción para escribir los encabezados por que si no, crashea el script pero no muestra ningún error

**Comment by rubenleal** [comment]
@gantonioid mi script sigue funcionando, pero corro el de Heber y falla por memoria, lo que estoy viendo es que el de Heber ejecuta un SP y de ahí vienen los resultados, quizás algo ahí genere el conflicto, el script es el id 4719971.

Ya probamos con las funciones RunOutputQuery y RunStoredProcedure pero ambas marcan el  Exception of type 'System.OutOfMemoryException' was thrown.


Script de SQL:
--SRD299201
USE BDCMP
EXEC spReporteAnalisisAbastoTiendaSTEPSYMBOL @FechaIngreso='<<<fechaActual>>>',@Cadena=0,@Sucursal='2992',@Depto=0,@Proveedor=0,@Articulo=0

**Comment by RickProductivity** [comment]
Sabes cuantos resultados regresa el store procederé?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by heber-solis** [comment]
@RickProductivity regresa 200980

**Comment by RickProductivity** [comment]
Ups , creo que por eso es el problema de memoria.
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rubenleal** [comment]
Tenemos otro script de SQL funcionando bien y trae +500K resultados, creo que este en particular algún conflicto le está generando el SP.

**Comment by RickProductivity** [comment]
Lo revisamos , que buena noticia no sabía que teníamos 500k , gracias por el Update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gantonioid** [comment]
Re-leyendo este issue, veo que el de heber es un problema distinto porque la instrucción es RunStoredProcedure. Este ticket es de RunOutputQuery.

@rubenleal te voy a mandar update para que tengas la nueva instrucción [QueryToCSV
](http://automationplatform.azurewebsites.net/Readers/Tools/DBReader/QueryToCSV) aquí documentada.

Eso te exporta el resultado del query directo a un archivo CSV, por lo tanto se espera reducir los problemas de memoria con RunOutputQuery en escenarios de gran magnitud.

##------
@heber-solis de todas maneras, estaré aplicando en este mismo update, una solución similar a la instrucción de RunStoredProcedure con propiedades de _CommandBehavior_

**Comment by gantonioid** [comment]
En cada caso, el seguimiento se daría en otro ticket porque son instrucciones distintas a la reportada aquí.

**Comment by heber-solis** [comment]
@gantonioid  una disculpa, vi que era "el mismo tema" y en vez de abrir otro issue supuse que el fix sería similar abro otro issue para que se le de seguimiento?

**Comment by gantonioid** [comment]
Si probando el update se resuelve tu problema, no es necesario un ticket nuevo. El cambio aplicado fue similar a éste.

**Comment by heber-solis** [comment]
**Proceso 1829347 ejecuta 2 querys con RunOutputQuery:**
Versión 20200601T1021 - Funciona
Versión 20200611T0758 (nueva) - marca error 
12/06/2020 8:44:44 - DB RunOutputQuery {SQL2.txt} in {myDB} as {query2}: Running
12/06/2020 8:48:16 - Exception of type 'System.OutOfMemoryException' was thrown.
12/06/2020 8:48:16 - DB RunOutputQuery {SQL2.txt} in {myDB} as {query2} : Error

 

**Proceso 4719971 - RunStoredProcedure:**
No funciona la instrucción para colocar los encabezados en el Excel, la ejecución termina intempestivamente sin ejecutar todo el script y sin indicar que hubo algún error.
12/06/2020 8:35:46 - DefineVariable type "int" as "i" with the value "1" : Success
12/06/2020 8:35:54 - Execution ended


**Proceso 5801171 - QueryToCsv
Marca syntax error que no encuentra la dbkey en el diccionario, se corrió primero el Run Output query con ese dbkey
12/06/2020 10:39:13 - DB RunOutputQuery {transmisiones.txt} in {myDB} as {output}: Running
12/06/2020 10:39:25 - Se agrego una nueva variable : 
Var Name : output
Value : System.Collections.Generic.List`1[System.Collections.Generic.List`1[System.String]]
12/06/2020 10:39:25 - Se agrego una nueva variable : 
Var Name : query_field_names
Value : System.Collections.Generic.List`1[System.String]
12/06/2020 10:39:25 - DB RunOutputQuery {transmisiones.txt} in {myDB} as {output} : Success
12/06/2020 10:39:25 - DB QueryToCsv {transmisiones.txt} in {myDB} as {C:\Users\MX02689\Documents\Embarcado_20200605_20200611}: Running
12/06/2020 10:39:25 - Syntax error
12/06/2020 10:39:25 - The given db does not exist in the dictionary.
12/06/2020 10:39:25 - DB QueryToCsv {transmisiones.txt} in {myDB} as {C:\Users\MX02689\Documents\Embarcado_20200605_20200611} : Error
12/06/2020 10:39:25 - Execution ended

**Comment by gantonioid** [comment]
### Error memoria RunOutputQuery
Lo revisamos, me das más detalles? log, script sql, tamaño de la respuesta(filas, columnas)

### RunStoredProcedure
En algún momento te funcionó? es bastante improbable porque no teníamos implementado lo de "query_field_names" para los Stored Procedures, solo estaba en RunOutputQuery. Ahora te mando update para que también se encuentre en RunStoredProcedure

### QueryToCsv
Primero te marca error de sintaxis porque debería de ser
`DB QueryToCsv {transmisiones.txt} in {myDB} save as {C:\Users\MX02689\Documents\Embarcado_20200605_20200611.csv}`
Te falta el "save" además de la extensión csv en el archivo. Ya complementé la documentación de eso.

**Comment by heber-solis** [comment]
**Error memoria RunOutputQuery**
pero esto si funcionaba con la versión anterior, la query Regresa 550k
[log_1829347.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4772239/log_1829347.txt)

**RunStoredProcedure**
si nunca funcionaba
**QueryToCsv**
lo escribí directo de lo que me sugería FRIDA.
DB QueryToCsv {<script>} in {<dbkey>} as {<csvfilepath>}

**Comment by gantonioid** [comment]
> **RunStoredProcedure**
> si nunca funcionaba

Eso creí, si gustas puedes probarlo con el nuevo update

> **QueryToCsv**
> lo escribí directo de lo que me sugería FRIDA.
> DB QueryToCsv {<script>} in {} as {}

Me dices el resultado con la sintaxis corregida por favor? Te decía que ya complementé la documentación que estaba equivocada.

**Comment by heber-solis** [comment]
si muchas gracias ya funciona con la sintaxis corregida :D solo que FRIDA me sugería otra sintaxis :)
y lo del stored procedure con los encabezados también funciona,  muchas gracias :D

**Comment by heber-solis** [comment]
el process Id 1829347 sigue marcando Out of memory después de actualizar :(
Excel WriteVariableValue {query2} in {Detalle1} start_at_row {2} start_at_column {1}: Running
12/06/2020 14:52:26 - Error in WriteVariableValue
12/06/2020 14:52:26 - System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
me marcó error
