### ISSUE TITLE
Error al aplicar filtro [Excelium]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#65]
Este script funcionaba sin errores y empezó a arrojar este 
```
Excel ApplyFilter to the worksheet ResultadosQuery to the column with the index {1} with the criteria "=aeliminar" and copy their value on "RappiEmpty": Running
20/05/2020 06:01:50 p. m. - Error message:    at CallSite.Target(Closure , CallSite , Object )
   at ExcelReader.ExcelExecute.ApplyFilter(String action) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 4397
20/05/2020 06:01:50 p. m. - Error:    at ExcelReader.ExcelExecute.WriteVariableValue(String action) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 5429
20/05/2020 06:01:50 p. m. - Excel ApplyFilter to the worksheet ResultadosQuery to the column with the index {1} with the criteria "=aeliminar" and copy their value on "RappiEmpty" : Error
```
tengo la versión 20200519T072

**Comment by ErlikC** [comment]
Me puedes compartir el Id del proceso y el excel que esta filtrando por favor.

**Comment by heber-solis** [comment]
1555471505 este es el process id
sabes que, una disculpa, el error está en esta linea, es que me fui hasta abajo y pues vi que marcó errror en apply filter y ya no le di mas para arriba, el error está en que quiere escribir una variable, pero este script ya funcionaba bien, igual te anexo el excel que usa el proceso por si quisieras ejecutarlo para hacer pruebas, lo puedes correr, no hay problema  y te anexo el log. 
Gracias!
[Rappi ExcelRodo.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/4665270/Rappi.ExcelRodo.xlsx)

[log.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4665265/log.txt)

**Comment by ErlikC** [comment]
En contré que había un error con WriteVariableValue, te hice un update. Tu versión anterior era 20200521T1031.

**Comment by heber-solis** [comment]
Muchas gracias

**Comment by heber-solis** [comment]
el fix que me pasaste si funciona, por si quisieras cerrar el issue

**Comment by ErlikC** [comment]
Ok, gracias.
