### ISSUE TITLE
Error en ReadColumn con start at{}

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#66]
me arroja este error al usar la instrucción 
ReadColumn from the worksheet {<worksheetKey>} with the column index {<ColumnIndex>} start_at {<RowIndex>} and save its value as {<varName>} visible
```
Excel ReadColumn from the worksheet {articulosSheet} with the column index {1} start_at {2} and save its value as {columnaArticulos} visible: Running
5/21/2020 8:45:15 AM - Error message:    at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ExcelReader.ExcelExecute.ReadColumn(String action) in C:\Users\gilberto.isida\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 7653
5/21/2020 8:45:15 AM - Error message: Cannot implicitly convert type 'string' to 'object[*,*]'
5/21/2020 8:45:15 AM - Excel ReadColumn from the worksheet {articulosSheet} with the column index {1} start_at {2} and save its value as {columnaArticulos} visible : Error
5/21/2020 8:45:19 AM - Execution ended
```
pero si uso la instrucción 
ReadColumn from the worksheet <worksheetKey> with the column index {<ColumnIndex>} and save its value as {<varName>}
lo hace sin problemas

**Comment by ErlikC** [comment]
Error message: Cannot implicitly convert type 'string' to 'object[*,*]'

Esto me hace suponer que tienes una fila con un solo valor? 
He visto este error en otra ocasión. Lo voy a corregir en esa función. Lo que me causa duda, es que en mi prueba, el error me sale con ambas sintaxis que mencionas.
Me podrías compartir el excel o un pantallazo del mismo por favor?

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/82610898-e351d200-9b84-11ea-901e-80d4f0e39f3a.png)
este es el excel y esta es la instrucción desde el log
```
5/21/2020 5:01:53 PM - Excel ReadColumn from the worksheet articulosSheet with the column index {1} and save its value as {columnaArticulos}: Running
5/21/2020 5:01:53 PM - Var Name : columnaArticulos
Value : 
[0] : articulos
[1] : 750151848530
[2] : 750129560012
[3] : 4011
[4] : 750101113388
[5] : 750105534989
[6] : 750100011145
[7] : 762221083379
[8] : 750179166934
[9] : 750103239932
[10] : 750105535776

5/21/2020 5:01:53 PM - Excel ReadColumn from the worksheet articulosSheet with the column index {1} and save its value as {columnaArticulos} : Success
```

**Comment by ErlikC** [comment]
Gracias Heber.
Eso me dio mucha pista del problema. Te generé una versión. Tenías 20200519T0702 anteriormente.

**Comment by heber-solis** [comment]
muchas gracias deja actualizo

**Comment by ErlikC** [comment]
Hola Heber, podemos cerrar el ticket?

**Comment by heber-solis** [comment]
si, adelante, gracias
