### ISSUE TITLE
Password Vault no me muestra áreas para asignarles contraseñas

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#67]
Ingreso al Password Vault con mi correo rleal@hebmex.com pero no me muestra las áreas para crear variables:
![image](https://user-images.githubusercontent.com/54807268/82619831-9a0d7c80-9b9c-11ea-8989-f9e13cad73d3.png)

Versión 20200519T0702

**Comment by AlanArteche** [comment]
Buenos días, Rubén, no se te muestra áreas porque ese usuario no es PasswordsAdmin de ningún área, es decir, no tiene permiso para crear y editar contraseñas de ningún área. Recientemente se hizo una mejora para que la pantalla se muestre como la imagen adjunta si se tiene precisamente este caso para que el usuario sepa esta información en vez de pensar que se trata de un error.

En el siguiente enlace puedes consultar más información sobre la funcionalidad: http://automationplatform.azurewebsites.net/Documentation/Tools

Si requieres hacer uso de ella, puedes decirme el nombre de las áreas en las que requieres ser PasswordsAdmin para que puedas crear y editar las contraseñas. Saludos.

![image](https://user-images.githubusercontent.com/48565879/82677799-36bc3280-9c0e-11ea-83df-66b56f676ba2.png)

**Comment by rubenleal** [comment]
Gracias @AlanArteche por favor dame PasswordAdwin de las siguientes áreas:
![image](https://user-images.githubusercontent.com/54807268/82824187-7e40f980-9e6e-11ea-9681-354572a8eafd.png)

Tenía confusión de si las áreas eran Apps o Suites, sugiero que actualicemos la leyenda a Suites en la pantalla de Turing.

**Comment by AlanArteche** [comment]
Listo, Rubén, te deberían aparecer las siguientes áreas/suites en Password Vault. También se tomó tu sugerencia y se cambio la palabra Area por Suite para que sea coherente con la ventana principal de Turing.

![image](https://user-images.githubusercontent.com/48565879/82933436-81f87d00-9f4f-11ea-8b4b-1bece80d0359.png)

**Comment by rubenleal** [comment]
Funcionando, podemos cerrar el ticket, comenzaré a explorar la funcionalidad, muchas gracias @AlanArteche.
