### ISSUE TITLE
Resultados de query no pasan a Excel en versión 20200519T0702

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#68]
Se comparte video, tengo copia de la versión 20200516T1200 y ahí si funciona.
[SQLaExcel.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4669254/SQLaExcel.zip)

*Código:*
####################
####################
#Servidor de base de datos
#DefineVariable type "string" as "ServidorBD" with the value "SRD201001"
DefineVariable type "string" as "ServidorBD" with the value "SCD201001"
#Base de datos a la que se conectará
DefineVariable type "string" as "BaseDatos" with the value "BDCMP"
#Tiempo de espera de respuesta del servidor de base datos (segundos)
DefineVariable type "string" as "Timeout" with the value "300"
#Indica si la autenticación será por Windows o SQL (ingresa Win o SQL)
DefineVariable type "string" as "Autenticacion" with the value "SQL"
#Si la autenticación es SQL utilizará las siguientes credenciales:
#DefineVariable type "string" as "Usuario" with the value "AdminReports"
#DefineVariable type "string" as "Contrasena" with the value "AdminReports"
DefineVariable type "string" as "Usuario" with the value "consulta"
DefineVariable type "string" as "Contrasena" with the value "consulta"
#Directorio principal del usuario
GetHome
#Obtiene fecha de hoy
GetCurrentDate Date{yyyyMMdd es} and save as Fecha
################

####################
####################
Message Conectándose a <<<ServidorBD>>>.<<<BaseDatos>>>...
if ("<<<Autenticacion>>>" -eq "SQL")
    #Si la autenticación es por SQL
    DB Connect to DB connectionstring={Server=<<<ServidorBD>>>;Database=<<<BaseDatos>>>;User Id=<<<Usuario>>>;Password=<<<Contrasena>>>;Connection Timeout=<<<Timeout>>>;} name={myDB}
else
    #Si la autenticación es por Windows
    DB Connect to DB connectionstring={Server=<<<ServidorBD>>>;Database=<<<BaseDatos>>>;Integrated Security=True;Connection Timeout=<<<Timeout>>>;} name={myDB}
end
#Ejecutamos la consulta a la BD
Message Ejecutando el script en <<<ServidorBD>>>.<<<BaseDatos>>>...
DB RunOutputQuery {SQL.txt} in {myDB} as {query}

####################
####################
#Crea y carga un Excel
Message Moviendo los resultados del query a Excel...
Excel NewWB in {<<<home>>>Downloads} as {tmpEVA}
Excel LoadWBook "<<<home>>>Downloads/tmpEVA.xlsx" as XLSBook
Excel LoadWSheet XLSBook sheet_index 1 as ResultadosQuery
#Vacía los resultados del query en el Excel
Excel WriteVariableValue {query} in {ResultadosQuery} start_at_row {2} start_at_column {1}

#Ingresa los Encabezados de las columnas del query al Excel
DefineVariable type "int" as "i" with the value "1"
foreach header in query_field_names {
    Excel Write "<<<header>>>" in ResultadosQuery row 1 and column <<<i>>>
    MathOperation <<<i>>> + 1 and save as i
}

#Guardamos el Excel
Excel Save XLSBook

**Comment by gantonioid** [comment]
Me parece que podría estar relacionado con #65

@ErlikC puedes considerarlo para mandarle el fix también a Rubén? Gracias!

**Comment by ErlikC** [comment]
Listo, ya te envié la versión 20200522T0450

**Comment by rubenleal** [comment]
Gracias ya funciona, se puede cerrar!
@ErlikC Me ayudas a enviarle la misma versión por favor a:
Rodolfo Pallares <rodolfo.pallares@softtek.com>; 
Alejandro Solis <heber.solis@softtek.com>; 
Julio Soto <julio.soto@softtek.com>

**Comment by ErlikC** [comment]
Muy bien, Listo ya mande las actualizaciónes.
