### ISSUE TITLE
Scheduler no muestra scroll para ver todos los procesos programados

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#69]
Comparto imagen (este tema no urge)
![image](https://user-images.githubusercontent.com/54807268/82689965-f4e8b780-9c20-11ea-845b-8dde55d1f16a.png)

**Comment by AlanArteche** [comment]
Listo, Rubén, se ha realizado el cambio para que se muestre un scroll y se puedan visualizar todos los procesos scheduleados como se muestra en las siguientes capturas. ¿Deseas que te mande un update? Saludos y buen fin de semana.

![image](https://user-images.githubusercontent.com/48565879/82705405-38511f00-9c3d-11ea-9564-dc45cc6967d9.png)

![image](https://user-images.githubusercontent.com/48565879/82705445-47d06800-9c3d-11ea-8ca6-5c6ff3450ef0.png)

**Comment by rubenleal** [comment]
Sí, mándame el update por favor, gracias!

**Comment by AlanArteche** [comment]
@rubenleal Qué tal, ¿ya podemos cerrar también este ticket con el cambio? Saludos.

**Comment by rubenleal** [comment]
No me llegó la actualización, todavía no veo el scroll en la versión 20200522T0450

**Comment by AlanArteche** [comment]
Buenos días, @rubenleal , recibirás un update con la versión de Turing que tiene varias funcionalidades nuevas y una interfaz gráfica distinta. ¡Saludos!

**Comment by rubenleal** [comment]
Se ve muy bien, funciona el scroll, muchas gracias @AlanArteche!
![image](https://user-images.githubusercontent.com/54807268/83207008-d2bad200-a117-11ea-8fa9-99a8676cbe00.png)
