### ISSUE TITLE
Versión mostrada en Turing es la de la BD y no la instalada actualmente

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#70]
Al abrir Turing se debe mostrar la versión de la aplicación actual, sin embargo se muestra la versión que está disponible para el usuario aún y cuando no esté instalada.

Para efectos de soporte esto puede generarles confusión ya que les diremos que tenemos una versión instalada cuando en realidad está otra trabajando: 
![image](https://user-images.githubusercontent.com/54807268/82690184-5ad53f00-9c21-11ea-8df0-2fa53506383d.png)

(no urge)

**Comment by AlanArteche** [comment]
Revisaré si este bug aún persiste en las versiones actuales de Turing. Si aún persiste aplicaría el cambio para que muestre la versión del archivo TurV.txt y no la proveniente del gestor de versiones PUMBA.

**Comment by AlanArteche** [comment]
Revisando en mi Turing actual, este bug ya no ocurre debido a modificaciones que se hicieron al agenta gestionador de versiones, PUMBA.exe . Igualmente tengo un update no aceptado y dentro de los Settings de Turing no es esa la versión que me está mostrando si no la actual.

![image](https://user-images.githubusercontent.com/48565879/100277333-9af6e080-2f28-11eb-99ba-2743dd62e329.png)

![image](https://user-images.githubusercontent.com/48565879/100277202-63883400-2f28-11eb-899e-f6a2069e8462.png)

Aquí se ha modificado después de haber aceptado el update.

![image](https://user-images.githubusercontent.com/48565879/100279020-65072b80-2f2b-11eb-9ed6-f436e7f0a45f.png)

Me mandé un nuevo update:

![image](https://user-images.githubusercontent.com/48565879/100279171-a26bb900-2f2b-11eb-91fa-2c2521763abe.png)
