### ISSUE TITLE
Puntos decimales de BD pasan como comas a Excel

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#71]
Las cantidades pierden sentido al pasar de BD a Excel debido a la sustitución de los puntos por comas:
![image](https://user-images.githubusercontent.com/54807268/82704361-fcb55580-9c3a-11ea-9e97-88909b1f7a50.png)

**Comment by ErlikC** [comment]
Hola, me puedes compartir el ID de tu proceso por favor.

**Comment by rubenleal** [comment]
Gracias @ErlikC, es el 1829347

**Comment by ErlikC** [comment]
Al hacer referencia con https://github.com/FridaSupport/CognitiveTestingMX/issues/75#issuecomment-639616262 se cierra el ticket.
