### ISSUE TITLE
Duda Powershell

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#73]
Tenemos un script de powershell que sube archivos a un SFTP , se usa el modulo Posh-SSH y manualmente funciona todo bien, al querer que FRIDA lo corra marca muchos errores 

este lo marca aun cuando está la linea de Import-Module
```
command was found in the module 'Posh-SSH', but the module could not be loaded. 
For more information, run 'Import-Module Posh-SSH'.
```
y este, por ejemplo, instalé el modulo manualmente, el modulo se instala en Documents/WindowsPowershell/Modules/Posh-SSH/2.2 pero me dice que no es válido

```
The member 'FileList' in the module manifest is not valid: The path is not of a legal form.. Verify that a valid value 
is specified for this field in the 'C:\Users\eva\Documents\WindowsPowerShell\Modules\Posh-SSH\2.2\Posh-SSH.psd1' file.
Import-Module : The member 'FileList' in the module manifest is not valid: The path is not of a legal form.. Verify 
that a valid value is specified for this field in the 
'C:\Users\eva\Documents\WindowsPowerShell\Modules\Posh-SSH\2.2\Posh-SSH.psd1' file.
At line:11 char:1
+ Import-Module Posh-SSH
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\eva\Do...2\Posh-SSH.psd1:String) [Import-Module], 
ArgumentException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand

``` 
si borro el modulo que no es válido, marca el primer error
se han topado con algo similar? 

el process id es 614405538

**Comment by ErlikC** [comment]
Hola Heber. 
Estoy revisando qué causa este mensaje de error, pero me doy cuenta que me falta mas información. El Id del proceso es de un proceso para pruebas, es correcto? por lo que ya no veo el código que tiene que ver con este ticket.

**Comment by heber-solis** [comment]
aa si permiteme es que lo cambié deja hago un especifico para ese o igual mira este es el codigo de powershell que se busca ejecutar
```
try
{

$modules = Get-Module -list
if ($modules.Name -notcontains 'Posh-SSH'){
 # Install-Module -Name Posh-SSH (https://github.com/darkoperator/Posh-SSH)
Install-Module Posh-SSH -Scope CurrentUser
}
# Set the credentials
$Password = ConvertTo-SecureString 'oNaLZ7CA' -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ('rappi', $Password)

 

# Set local file path and SFTP path

$FilePath1 = $fileLocation
 

$SftpPath = '/incoming'

 

# Set the Hostname of the SFTP server
$SftpServer = 'sftpvendor.heb.com.mx'

 

# Load the Posh-SSH module
Import-Module Posh-SSH

 

# Establish the SFTP connection
$ThisSession = New-SFTPSession -ComputerName $SftpServer -Credential $Credential -AcceptKey -Port 22

 

# Upload the files to the SFTP path
Set-SFTPFile -SessionId ($ThisSession).SessionId -Localfile $FilePath1 -RemotePath $SftpPath -Overwrite

 

#Disconnect all SFTP Sessions
Get-SFTPSession | % { Remove-SFTPSession -SessionId ($_.SessionId) }
}
catch{
$Error | Out-File D:\logRappi.txt -Append
$fileLocation | Out-File D:\fileLocation.txt -Append
}
```
al darle RunPowershell marca los errores que te comento, dime si gustas que haga un script con eso o si con el código de powershell es suficiente para indagar el error.
muchas gracias

**Comment by ErlikC** [comment]
Creo con llamar con RunPowershell este script, debo poder ver el problema. Gracias Heber

**Comment by ErlikC** [comment]
Hola. Respecto a la instalación y luego uso del modulo, me parece que no va a ser posible. De acuerdo a la documentación.

![image](https://user-images.githubusercontent.com/60276982/86033997-75a88980-b9ff-11ea-8eee-30a0bad4403a.png)

Así que lo que hiciste de instalarlo manualmente, es el camino correcto.
Estuve investigando respecto al siguiente error que marca. En el archivo Posh-SSH.psd1 Tiene registrado valores para FileList, en otros blogs encuentro que este valor realmente no se usa. Inicialmente al crear los manifest viene vació. Aun que no encuentro mayor detalle al respecto.

Pero si comento esa linea, ya todo funciona correctamente. (Antes tuve que cambiar la política de ejecución con : Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser )
![image](https://user-images.githubusercontent.com/60276982/86046775-6e8b7680-ba13-11ea-9d40-1618cd3d71ed.png)

https://stackoverflow.com/questions/52435830/powershell-module-manifest-filelist-property-specifically-what-does-it-do
https://www.reddit.com/r/PowerShell/comments/d34akg/powershell_module_file_loading_files_in_filelist/

Este fue el script que ejecute:
```
try
{
	 Get-Host | Select-Object Version | Out-File C:\Users\erlik.corona\Documents\Erlik\TICKETS\Temp\logRappi.txt
	 Get-ExecutionPolicy -Scope CurrentUser | Out-File C:\Users\erlik.corona\Documents\Erlik\TICKETS\Temp\logRappi.txt -Append
	 $modules = Get-Module -list
     Find-Module -Name Posh-SSH | Out-File C:\Users\erlik.corona\Documents\Erlik\TICKETS\Temp\logRappi.txt -Append
	 if ($modules.Name -notcontains 'Posh-SSH'){
		echo "no esta" | Out-File C:\Users\erlik.corona\Documents\Erlik\TICKETS\Temp\logRappi.txt -Append
	 }
     else
     {
		echo "si esta" | Out-File C:\Users\erlik.corona\Documents\Erlik\TICKETS\Temp\logRappi.txt -Append
	 }
 	 # Load the Posh-SSH module
	 Import-Module -Name Posh-SSH
	 Get-PoshSSHModVersion | Out-File C:\Users\erlik.corona\Documents\Erlik\TICKETS\Temp\logRappi.txt -Append

}
catch{
   $Error | Out-File C:\Users\erlik.corona\Documents\Erlik\TICKETS\Temp\logRappi.txt -Append
}

```
![image](https://user-images.githubusercontent.com/60276982/86046462-dee5c800-ba12-11ea-9953-291509b45c49.png)

Porfa revisa si esto te permite avanzar.
Saludos

**Comment by heber-solis** [comment]
Excelente! deja lo intento, muchas gracias Erlik!

**Comment by heber-solis** [comment]
puedes cerrar el issue, si me funcionó, muchas gracias!
