### ISSUE TITLE
Exception from HRESULT en instrucción ApplyFormat

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#75]
Buen día, 
intenté aplicar formato a una columna como alternativa para remover las comas en los valores numéricos (Issue relacionado: https://github.com/FridaSupport/CognitiveTestingMX/issues/71)
sin embargo, me sale un error con esa instrucción, dejo aquí el log: 

`03/06/2020 9:11:34 - Message Ajustando formato... : Success
03/06/2020 9:11:34 - Excel ApplyFormat from ResultadosQuery in_column "Existencias" format @: Running
03/06/2020 9:11:41 - Exception from HRESULT: 0x800A03EC
03/06/2020 9:11:41 - Error message:    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.get__Default(Object RowIndex, Object ColumnIndex)
   at ExcelReader.ExcelExecute.ApplyFormat(String action) in C:\Users\alanm.gonzalez\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 23910
03/06/2020 9:11:41 - Error message: Exception from HRESULT: 0x800A03EC
03/06/2020 9:11:41 - Excel ApplyFormat from ResultadosQuery in_column "Existencias" format @ : Error`

La columna que trato de convertir es la que está seleccionada: 
![image](https://user-images.githubusercontent.com/54809099/83649575-f8fbca00-a57c-11ea-8725-fac4db2ce511.png)

**Comment by julio-soto-0517** [comment]
Actualización: El nombre de la columna es Existencia no Existencias, hice una nueva prueba, sin embargo, eliminó algunas comas pero no reemplazó el valor: 
![image](https://user-images.githubusercontent.com/54809099/83653899-f64fa380-a581-11ea-888e-190d8a09135c.png)

**Comment by ErlikC** [comment]
hola. Lo que veo es que identificaba las comas como separador de miles. Y por eso elimino las comas "que hacian sentido", por asi decirlo. Por que 0,0000 no es algo que podamos identificar como separador de miles.
Bueno, entonces interpreto que el error viene desde la lectura de BD y no dentro de excel. Algo esta sucediendo que lee comas en vez de puntos.

**Comment by julio-soto-0517** [comment]
Hola, 
me parece raro, porque desde la base de datos, vienen como puntos, y al traerlos al excel, se convierten a comas, no sé si haya algo erróneo con el tipo de variable, anteriormente era decimal, y ahorita intenté con numeric:
![image](https://user-images.githubusercontent.com/54809099/83664872-39187800-a590-11ea-8e7e-2c496b7fa9cf.png)


![image](https://user-images.githubusercontent.com/54809099/83665019-70872480-a590-11ea-8482-42257aa4c73c.png)

**Comment by julio-soto-0517** [comment]
Por cierto, también intenté con una instrucción llamada ReplaceCharacter, se muestra en el log de una de las pruebas que hice que si se ejecutó esa línea, pero al ver el excel, no se cambia, ¿podré dejar esto en este issue o sería un tema aparte?


`03/06/2020 11:40:49 - Excel ReplaceCharacter "," from the worksheet ResultadosQuery with "." in the column with the index 3: Running
03/06/2020 11:40:50 - Excel ReplaceCharacter "," from the worksheet ResultadosQuery with "." in the column with the index 3 : Success`

![image](https://user-images.githubusercontent.com/54809099/83666730-0754e080-a593-11ea-9c67-24d5a9c51242.png)

**Comment by RickProductivity** [comment]
Podrías ponerlo como otro issue para llevar el control.
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by julio-soto-0517** [comment]
Al ejecutar  SELECT @@LANGUAGE me aparece esto: 
![image](https://user-images.githubusercontent.com/54809099/83681410-fb274e00-a5a7-11ea-973a-9f0b46ca0d86.png)

Sobre los datos que llegan a Excel, tengo duda, ¿cómo canalizaría esa parte?, ya que los datos me los traigo de esta manera:

```
#Crea y carga un Excel
Message Moviendo los resultados del query a Excel...
Excel NewWB in {<<<home>>>Downloads} as {tmpEVA}
Excel LoadWBook "<<<home>>>Downloads/tmpEVA.xlsx" as XLSBook
Excel LoadWSheet XLSBook sheet_index 1 as ResultadosQuery
#Vacía los resultados del query en el Excel
Excel WriteVariableValue {query} in {ResultadosQuery} start_at_row {2} start_at_column {1}


#Ingresa los Encabezados de las columnas del query al Excel
DefineVariable type "int" as "i" with the value "1"
foreach header in query_field_names {
    Excel Write "<<<header>>>" in ResultadosQuery row 1 and column <<<i>>>
    MathOperation <<<i>>> + 1 and save as i
}
```

**Comment by ErlikC** [comment]
Ok, mira hice un script donde leo la informacion de un CSV (que seria mi resultado del Query)

```
Excel LoadWBook "<<arc>>" as WB
Excel LoadWBook "<<csv>>" as WCSV
Excel LoadWSheet WB sheet "Sheet7" as WS
Excel LoadWSheet WCSV sheet "Sheet1" as WSCSV

Excel ReadRowsCSV from {WSCSV} start_at {1} as {lista} by {;}
foreach varE in lista {
    foreach inner in varE {
	Message <<<inner>>>
    }
}
Excel WriteVariableValue {lista} in {WS} start_at_row {1} start_at_column {1}

```

Para vaciar la información tal cual llegó de lo que leyo, use WriteVariableValue. En tu caso "lista" es "query" que es lo que podrías iterar en los 2 foreach para ver que tienen las variables antes de que sean escritas a excel.

**Comment by julio-soto-0517** [comment]
De acuerdo, hice la prueba con la iteración, me trajo los valores de la database, para efectos de prueba, reduje el número de resultados, no sé si lo habré hecho bien, me iteró todo en message y luego lo pasé a excel, sin embargo, antes de cargarlos al excel, el log me arroja esto (muestro aquí una parte de los resultados, ya que son demasiados):
```
04/06/2020 9:02:50 - Foreach Block Running
04/06/2020 9:02:50 - Foreach Iterator Name : varE
04/06/2020 9:02:50 - Foreach Variable Name : query
04/06/2020 9:02:50 - Foreach Block Running
04/06/2020 9:02:50 - Foreach Iterator Name : inner
04/06/2020 9:02:50 - Foreach Variable Name : varE
04/06/2020 9:02:50 - Message 398: Running
04/06/2020 9:02:50 - Message 398 : Success
04/06/2020 9:02:50 - Message BAFAR SALCHICHA CAMPESTRE PARA ASAR: Running
04/06/2020 9:02:50 - Message BAFAR SALCHICHA CAMPESTRE PARA ASAR : Success
04/06/2020 9:02:50 - Message 0,00: Running
04/06/2020 9:02:50 - Message 0,00 : Success
04/06/2020 9:02:50 - Message 210 - CARNES: Running
04/06/2020 9:02:50 - Message 210 - CARNES : Success
04/06/2020 9:02:50 - Message Suspendido: Running
04/06/2020 9:02:50 - Message Suspendido : Success
04/06/2020 9:02:50 - Foreach Block End
04/06/2020 9:02:50 - Foreach Block Running
04/06/2020 9:02:50 - Foreach Iterator Name : inner
04/06/2020 9:02:50 - Foreach Variable Name : varE
04/06/2020 9:02:50 - Message 9825: Running
04/06/2020 9:02:50 - Message 9825 : Success
04/06/2020 9:02:50 - Message CHIMEX SALCHICHA PARA ASAR: Running
04/06/2020 9:02:50 - Message CHIMEX SALCHICHA PARA ASAR : Success
04/06/2020 9:02:50 - Message 62,00: Running
04/06/2020 9:02:50 - Message 62,00 : Success
04/06/2020 9:02:50 - Message 210 - CARNES: Running
04/06/2020 9:02:50 - Message 210 - CARNES : Success
04/06/2020 9:02:50 - Message Activo: Running
04/06/2020 9:02:50 - Message Activo : Success
04/06/2020 9:02:50 - Foreach Block End
```

Los números me aparecen con comas antes de pasarlos al excel, y al momento de pasarlos, es como se muestran con las comas:

![image](https://user-images.githubusercontent.com/54809099/83769010-f5337a80-a644-11ea-8897-958c04874bdd.png)

**Comment by ErlikC** [comment]
Ok, entonces queda confirmado que no es excel. Ahora me falta investigar por que si tu idioma es us_english, esta poniendo comas en los numeros.

**Comment by ErlikC** [comment]
A nivel código, veo que no hace distinciones por el idioma, toma lo que venga del query y con el idioma definido en el login del usuario. 
Podrías lanzar el query de select @@language desde turing porfa?

otras opciones, pueden estar aqui
https://stackoverflow.com/questions/15705983/how-to-change-default-language-for-sql-server

me llama la atención la parte que dice
![image](https://user-images.githubusercontent.com/60276982/83800015-57ec3c80-a66c-11ea-9dde-194f6677770d.png)

**Comment by julio-soto-0517** [comment]
Te dejo aquí vídeo de la ejecución, creo que se trae con el que inicia sesión en el servidor de BD. 
[Prueba-SQL-I75.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4732810/Prueba-SQL-I75.zip)

Sobre las otras opciones, entonces habría que revisar a nivel usuario o nivel Query el idioma que se selecciona por default o elegirlo desde uno de estos niveles?

**Comment by ErlikC** [comment]
Entiendo que se puede configurar a distintos niveles. Pero el problema es que desde que ejecutas, ya esta en idioma de estados unidos. 
Ya arregle replace character. Y otra opción para seguir intentando identificar si es tema de idioma es poner Set language Spanish; o algo diferente para ver si afecta en la salida de los datos.

**Comment by gantonioid** [comment]
Después de investigación y pruebas, entiendo que el Reader de SQL toma por default la cultura de la máquina al momento de leer los resultados del query.

Te mandaré un update en el que se le especifica que sea `CultureInfo.InvariantCulture` para que siempre sea igual (no varíe de una máquina a otra)

**Comment by julio-soto-0517** [comment]
Enterado, actualicé a la versión que me enviaron, aquí un vídeo de la ejecución, la cual resultó exitosa, ¡Muchas gracias, equipo! 

[PruebaSQL-FridaVersion-20200604T1143.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4737372/PruebaSQL-FridaVersion-20200604T1143.zip)
