### ISSUE TITLE
Habilitar Función ReplaceCharacter

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#76]
(Este issue está relacionado con el https://github.com/FridaSupport/CognitiveTestingMX/issues/71
 y https://github.com/FridaSupport/CognitiveTestingMX/issues/75 , ya que se busca que los valores puedan expresarse con decimales correctamente) . Se intentó una prueba para reemplazar valores en una columna específica con la instrucción de Excellium Replace Character, al terminar la prueba, el log muestra que se realizó el cambio exitosamente, sin embargo, al ver el archivo donde este cambio debe efectuarse, no se muestra el reemplazo:

`03/06/2020 11:40:49 - Message Ajustando formato... : Success
03/06/2020 11:40:49 - #Excel ApplyFormat from ResultadosQuery in_column_index 3 format @: Running
03/06/2020 11:40:49 - #Excel ApplyFormat from ResultadosQuery in_column_index 3 format @ : Success
03/06/2020 11:40:49 - Excel ReplaceCharacter "," from the worksheet ResultadosQuery with "." in the column with the index 3: Running
03/06/2020 11:40:50 - Excel ReplaceCharacter "," from the worksheet ResultadosQuery with "." in the column with the index 3 : Success
03/06/2020 11:40:50 - Excel Save XLSBook: Running
03/06/2020 11:40:51 - Excel Save XLSBook : Success
03/06/2020 11:40:51 - Excel Close XLSBook: Running
03/06/2020 11:40:51 - Excel Close XLSBook : Success`

![image](https://user-images.githubusercontent.com/54809099/83669234-d676aa80-a596-11ea-9476-4b7bbb1afb68.png)

**Comment by ErlikC** [comment]
Se corrigió el bug que encontraste. Te generé la versión 20200604T1047.

Saludos

**Comment by julio-soto-0517** [comment]
Perfecto, hice prueba y efectivamente se cambian los caracteres que reemplazaré. ¡Muchas gracias! 
Saludos.
<img width="831" alt="Anotación 2020-06-05 114418" src="https://user-images.githubusercontent.com/54809099/83902397-ebcc1000-a721-11ea-967c-9f3b13dbdbc0.png">

J.S.
