### ISSUE TITLE
[Duda] error al ejecutar un script desde powershell

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#77]
Si ejecuto un script desde powershell `Start-Process -FilePath "C:\Turing\App\TuringExpo.exe"  "6172852" -Wait` y sucede un error, se puede mandar el error a powershell? como un $LASTEXITCODE = 1

**Comment by gantonioid** [comment]
Lo llamas desde PowerShell, pero dentro de una ejecución de FRIDA? Es decir... dentro de un proceso FRIDA, llamas a otro?
Tenemos esta instrucción
[RunFRIDAProcess](http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/RunFRIDAProcess)

**Comment by heber-solis** [comment]
no, es que por ejemplo calendarizamos procesos de FRIDA desde azure, pero todas las ejecuciones marcan como 'successful' aunque ocurra un error, la duda es si es posible que powershell reciba la "señal" de ese error?

**Comment by gantonioid** [comment]
Por ahora no. Tu script tendrá que encargarse del reporte de errores por vía mail u otro medio. Ves que la plataforma tiene sus bitácoras de ejecución independientes y analytics propios, capacidades de try/catch. Entonces ese "control" lo tienes que definir en tu script. Porque finalmente, el $LASTEXITCODE sería siempre exitoso (a menos que Turing crashee).

En todo caso, puedes loggear las fallas (try/catch, u otros errores) en un txt que tú definas. Así, en cuanto recibas el $LASTEXITCODE, lo revisas para tener los detalles en el PowerShell que comentas.

**Comment by ErlikC** [comment]
Hola Heber.
No es tan recomendable el uso de Start-Process.
https://stackoverflow.com/questions/39496829/powershell-start-process-not-setting-lastexitcode

Puse codigos de retorno de error. Y como identifique que funciona mejor es con llamados como este

`C:\Turing\App\TuringExpo.exe 6172852 |  Out-Null`

para que tome en cuenta $LASTEXITCODE.
En mi ejemplo ejecute el proceso con un error de sintaxis primero y luego sin error.
![image](https://user-images.githubusercontent.com/60276982/85473905-88dbd500-b579-11ea-9bfe-f6f50870202e.png)

Te actualizó tu Turing (20200623T1054), por favor revisalo, si tienes temas lo revisamos.

**Comment by heber-solis** [comment]
muchas gracias Erlik! deja termino unas cosas y lo reviso, podrías apoyarme con el issue #73 por favor? no he recibido respuesta sobre ese

**Comment by heber-solis** [comment]
funciona muy bien Erlik :) si gustas puedes cerrarlo, muchas gracias!
