### ISSUE TITLE
DB reader no acepta variables de FRIDA

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#78]
[log.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4781735/log.txt)
adjunto log de ejecución, el script me marca sintax near '<' el único < que tengo es el de la variable de FRIDA , lo que me hace pensar que el valor de la variable no se está pasando al script de SQL

**Comment by ErlikC** [comment]
Hola, es correcto, no toma variables de frida. 
Se tendría que pasar, armando el query previamente y creando un archivo
`RunOutputQuery {GetProducts.txt} in {mybd} as {products}`
o
pasando el query armado
`RunOutputQuery {Select * from users} in {mybd} as {products}`

**Comment by heber-solis** [comment]
pero en la versión anterior si funcionó de esta forma 

CREATE TABLE #TemporalRAPPI
	(Fecha INT,
	Tienda INT,
	DescripcionTienda CHAR(50),
	BIN NVARCHAR(10),
	Cliente VARCHAR(4),
	Monto FLOAT)
<<<listaQueries>>>

**Comment by gantonioid** [comment]
@heber-solis te estoy pasando la corrección en el update `20200616T0509`

**Comment by heber-solis** [comment]
16/06/2020 04:16:10 p. m. - Incorrect syntax near '-'. ahora me marca esto

**Comment by heber-solis** [comment]
una disculpa, el error era por que mandaron el excel con una fila de más, si funcionó el update con lo de la variable :) muchas gracias
