### ISSUE TITLE
Anexar múltiples archivos a la vez con la función UploadFile

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#8]
permitir carga de multiples archivos en vez de solo 1

**Comment by gantonioid** [comment]
Te refieres en Turing como scripts adicionales o en Browpet?

**Comment by heber-solis** [comment]
en Browpet

**Comment by gantonioid** [comment]
Hay que considerar casos en los que el campo de <input type="file" /> no lo permita

**Comment by oscarlaureano** [comment]
Ya esta disponible la funcionalidad:
http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/UploadFile
