### ISSUE TITLE
Error en ReadMail New

### ISSUE THREAD

**Issue by julio-soto-0517** [FridaSupport/CognitiveTestingMX#80]
Hola, buen día,
Tengo un script en el que envío un correo, y después, entro al correo a leer ese mismo que fue enviado para extraer el archivo adjunto y guardarlo, este al leerse se mueve a una carpeta específica, sin embargo, suele marcar error:

```
15/06/2020 19:46:31 - Mail ReadMailNew and get "attachment" from the folder "Bandeja de entrada" that fulfills the multifilter {eva@hebmex.com,sender;2020/06/15,date;Opinion de cumplimiento,subject} and save as "C:\Users\MX02688\Desktop" finally move it to "Prueba QR": Running
15/06/2020 19:46:36 - Error : The specified object was not found in the store., The process failed to get the correct properties.
15/06/2020 19:46:36 - Mail ReadMailNew and get "attachment" from the folder "Bandeja de entrada" that fulfills the multifilter {eva@hebmex.com,sender;2020/06/15,date;Opinion de cumplimiento,subject} and save as "C:\Users\MX02688\Desktop" finally move it to "Prueba QR" : Error
15/06/2020 19:46:36 - Catch Block Running
```
A pesar de que el archivo si fue movido a una carpeta, el log suele marcar error en la ejecución
![image](https://user-images.githubusercontent.com/54809099/84719921-3891c100-af42-11ea-9107-d9b9ff664651.png)

![image](https://user-images.githubusercontent.com/54809099/84720026-86a6c480-af42-11ea-868f-92968826991a.png)

**Comment by rubenleal** [comment]
Al parecer algo se movió en la función ReadMailNew, estaba trabajando bien y ahorita se está presentando el problema con distintos procesos bajo distintas sintaxis #79

**Comment by julio-soto-0517** [comment]
Este ticket puede cerrarse, el problema fue originado debido a detalles con la sintaxis. Muchas gracias por el apoyo, ¡Saludos!
