### ISSUE TITLE
DB reader no acepta variables de FRIDA

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#82]
buen dia, tengo este issue nuevamente #78  tengo la versión 20200616T0509

**Comment by gantonioid** [comment]
Esa es la versión que lo solucionó en el ticket pasado (78).

@ErlikC puedes asegurarte de que tenga esa v? o si se trata de un problema distinto?

**Comment by ErlikC** [comment]
hola, Heber.
Podemos borrar el archivo turV para forzar nuevamente el update de tu turing por favor?

**Comment by heber-solis** [comment]
al usuario de alpha@hebmex.com le pasa lo mismo, acaba de actualizar hace unos minutos pero igual haré lo de borrar turV

**Comment by ErlikC** [comment]
Sigue siendo este script?
![image](https://user-images.githubusercontent.com/60276982/85180611-7a27b200-b249-11ea-9795-04cec188e04e.png)

**Comment by heber-solis** [comment]
no, ahora es  este
![image](https://user-images.githubusercontent.com/54727278/85180777-ddb1df80-b249-11ea-8bee-3c9cbbd378ba.png)
pero la de << >> si las agarra 
la variable de fechaActual se declara antes de que se ejecute el script de BD
este es el process id 4719971

**Comment by heber-solis** [comment]
no hubo cambio al borrar TurV.txt

**Comment by ErlikC** [comment]
ok, voy a ejecutar una prueba. Te comento lo que encuentre

**Comment by ErlikC** [comment]
Si habían problemas con la lectura de las variables. Te generé la versión 20200620T1224 con la corrección.

**Comment by heber-solis** [comment]
muchas gracias Erlik :D
