### ISSUE TITLE
Función RoundAllNumbersTo ingresa comas a los números (miles)

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#83]
Al cruzar el 1000, se agrega una coma y se reinicia el contador al ser 1,000 alfanumérico
DefineVariable type "int" as "LRow" with the value "1"
#Definimos cero decimales para los cálculos
**RoundAllNumbersTo "0"**
#Ciclo
for 1005 times {
    MathOperation <<< LRow >>> + 1 and save as LRow
}

Si se elimina la función RoundAllNumbersTo, el ciclo funciona correctamente.

Aquí un ejemplo en el log, en lugar de colocar 1001, la variable se regresa a 2:
![image](https://user-images.githubusercontent.com/54807268/85298388-a1f56080-b469-11ea-8b93-6ae834360567.png)

**Comment by ErlikC** [comment]
Me parece que es un tema, por un lado de configuración en tu computadora, por que te esta arrojando 999 + 1 = 1,000 en lugar de 1000. A mi me sale:
![image](https://user-images.githubusercontent.com/60276982/85324841-2d81e800-b490-11ea-9828-568950f16756.png)

Luego 1,000 en formato de algunos países es el equivalente a 1.000 y por esta razón 1+1=2
Y para ellos el separador de miles es ".", por ejemplo 2.300,00 es correcto.

Pero, eso no debería ser factor para que por un lado te ponga separador de miles y luego al hacer la suma te tome la coma como separador de decimales.

Intentaré cambiar el formato de salida en mi computadora para llegar a como lo toma tu computadora y con eso arreglar en código.

**Comment by rubenleal** [comment]
Gracias @ErlikC, quizás sea la función RoundAllNumbersTo si la elimino no me coloca las comas.

**Comment by ErlikC** [comment]
Hola, efectivamente había una combinación de factores entre RoundAllNumbersTo y MathOperation. Ya esta resuelta. Quieres que te mande versión?
