### ISSUE TITLE
[HEB] Password Vault no hereda la contraseña para otros usuarios

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#84]
Se generó una variable en la bóveda, al utilizarla con el usuario Admin de los passwords la variable se interpreta correctamente, sin embargo, al ejecutar el mismo script con otro usuario, la variable no se convierte.

Comparto video con el ejercicio:
[PasswordVault_Usuarios.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/4815602/PasswordVault_Usuarios.zip)

**Comment by AlanArteche** [comment]
Vale, reviso qué podría estar sucediendo, ya que sí debería poder acceder a los valores de las contraseñas para utilizarlas.

**Comment by rubenleal** [comment]
rleal@hebmex.com - 20200616T0509
heber.solis@softtek.com - 20200601T1021

**Comment by AlanArteche** [comment]
Confirmo que este tema no se origina en la versión de heber, sin embargo, adjunto prueba de que para la Suite Procesos EVA el único usuario es "heb2", ni Rubén ni Heber son usuarios de la Suite. Veo que el problema es más bien una confusión entre la base de datos de Automation y la de Cognitive. Para que un usuario pueda acceder a los valores de las contraseñas de Password Vault, debe ser un usuario en la base de datos de Automation. Las contraseñas se administran por Suite, no por App, así que los permisos que se ven en Cognitive no tienen impacto sobre Password Vault, ya que sólo hay permisos a nivel App.

![image](https://user-images.githubusercontent.com/48565879/85431443-2e298580-b547-11ea-9f36-fc2e39c1d7a8.png)

![image](https://user-images.githubusercontent.com/48565879/85431724-88c2e180-b547-11ea-9b9d-31517b220d5e.png)

Comento que está en la mesa una propuesta de mejora para que desde Cognitive se puedan editar las contraseñas de Password Vault, para ello también existirían permisos de Admin/Editor/Read Only ahora a nivel Suite y no sólo App. Esa mejora aún no está en desarrollo y recién hoy ha surgido como necesidad para un cliente.

Para solucionar ahorita el problema del ticket, bastaría con que agregue en los Users de la base de datos de Automation a Heber, ¿gustan que agregue a algún otro usuario? Saludos.

**Comment by AlanArteche** [comment]
@gantonioid Adicionalmente a la mejora que comenté que está en el Git de TuringSupportSSH en el ticket #699, considero que también debería haber una lógica por parte de Cognitive al momento de agregar un usuario a una App para que vaya a la base de Automation y agregue a esos usuarios a la lista de Users de todas las Suites dentro de esa App, ¿qué opinas?

**Comment by rubenleal** [comment]
Gracias @AlanArteche, en mi caso ocupo que esas contraseñas las vean todos los que están asignados a HEB, puedes platicar con Aldo Vega para ver la lista de usuarios por favor.

Aprovechando el nivel que comentas de incorporar permisos a nivel App, yo tengo la necesidad de asignar passwords para múltiples o todas las Apps, ¿la pueden considerar?

Por ejemplo, todos mis procesos utilizan la misma cuenta de correo, ahorita tengo que darla de alta en cada una de las Apps, ¿podría definir una sola variable y heredarla a todas las apps? Habría que hacer otras validaciones también como si la contraseña ya está asignada a nivel General, Suite o App para evitar que se empalmen y se esté tomando otra en su lugar.

**Comment by AlanArteche** [comment]
Estaré trabajando una mejora para dar alternativa a esta inconsistencia entre Cognitive y Automation, creo que se me ocurre una alternativa. Comento que no se manejarán contraseñas a nivel App, sólo a nivel Suite.

**Comment by AlanArteche** [comment]
Listo, ya tengo una mejora que, si el usuario no es parte de los Users de la Suite, pero es un User de la App que contiene a la Suite que contiene el Test que se está ejecutando, en ejecución FRIDA ya pueda tomar las contraseñas de Password Vault. Ya probé y funciona en ejecución manual y a través del Listener, sólo estoy detectando que hay otro problema diferente respecto al modo de ejecución Scheduling que también afecta Password Vault, estaré revisando este último tema.

**Comment by AlanArteche** [comment]
Comento que ya se han arreglado los problemas mencionados con la funcionalidad de Scheduling. Adicionalmente, ya se puso en la mesa un cambio para que se puedan manejar passwords a nivel App también y que se compartan entre las Suites dentro de la misma.

**Comment by AlanArteche** [comment]
@rubenleal ¿Requieres que te mande un update con estos cambios? ¿También a los usuarios de HEB? Saludos.

**Comment by rubenleal** [comment]
Gracias, mandemos versión por favor a:
Ruben Leal <RLeal@hebmex.com>; Rodolfo Pallares <rodolfo.pallares@softtek.com>; Julio Soto <julio.soto@softtek.com>; Alejandro Solis <heber.solis@softtek.com>

**Comment by AlanArteche** [comment]
Listo, @rubenleal , los 4 usuarios ya deben poder recibir un nuevo update, favor de confirmar que el problema del ticket queda resuelto. Saludos.

**Comment by rubenleal** [comment]
Gracias @AlanArteche funciona muy bien!
¿Cerramos el ticket o lo dejamos como seguimiento para las contraseñas a nivel App (que herede a todas las Suites)?

**Comment by AlanArteche** [comment]
Vale, lo podemos dejar abierto para esos temas. Lo primero que se cambiará es que en la ventana de Password Vault, si un usuario es Admin de una App en Cognitive, las Suites de esa App aparecerán en la lista y el usuario tendrá permiso de crear y editar las contraseñas de esas Suites. Después se verá lo de Passwords a nivel App.

**Comment by gantonioid** [comment]
@AlanArteche hay updates? lo cerramos?

**Comment by AlanArteche** [comment]
Sobre el tema de passwords a nivel App no es un desarrollo que se vaya a hacer, se seguirán manejando a nivel Suite solamente.
Pero sí hay noticias nuevas respecto a la integración de Password Vault a Cognitive que valen la pena mencionar. En Cognitive se puede administrar las passwords de una Suite en la siguiente opción:

![image](https://user-images.githubusercontent.com/48565879/94458944-4af3db80-017c-11eb-81a9-e2b53a55f624.png)

Para que aparezca esta opción, debemos tener permiso de Passwords Admin el cual puede ser otorgado desde Cognitive o desde Turing por alguien que sea Passwords Admin como se muestra a continuación:

![image](https://user-images.githubusercontent.com/48565879/94459199-a2924700-017c-11eb-8fe6-8f9cf37a3fa6.png)

![image](https://user-images.githubusercontent.com/48565879/94459416-eedd8700-017c-11eb-9e7d-976ffd620b88.png)

El Listener, que ahora ha sido reemplazado por el componente Turing Watcher, igualmente es compatible con Password Vault. Dejo estos comentarios solamente, podemos cerrar el ticket.
