### ISSUE TITLE
Contraseña se puede extraer si se invoca variable en alerta

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#85]
Hice la prueba con variable del Password Vault pero asumo que es lo mismo con cualquiera.

En el log la contraseña aparece cifrada (*******), sin embargo si alguien la imprime en una alerta (SystemNotify) la misma se expone y no debería:
![image](https://user-images.githubusercontent.com/54807268/85336326-0b926080-b4a4-11ea-9e44-529edb5f66fb.png)

**Comment by AlanArteche** [comment]
Buenas tardes, Rubén, más allá de ser un asunto de confianza o ética, esta brecha ya se había detectado tiempo atrás como algo que no puede ser resuelto al 100%. Como parte de la solución parcial, podemos bloquear el acceso a los valores de las variables tipo password de algunas instrucciones como SystemNotify, Excel Write, entre otras, más seguiría existiendo una brecha con instrucciones más complicadas como aquellas que son necesarias de Browpet para escribir los valores en una ventana de Login de algún portal o con Titanium Type, ya que algunas veces se introducen credenciales en otros programas de escritorio. Sobre el tema de Browpet yo tengo una propuesta de cambio para algunas instrucciones que creo podría ayudar a bloquear la escritura si se realiza en un elemento web que no es un input de contraseña, pero para Titanium type sí parecería que no hay una solución directa.

**Comment by rubenleal** [comment]
De acuerdo contigo @AlanArteche, es un tema complejo, pero me agrada tu propuesta para Browpet.

**Comment by gantonioid** [comment]
Para entender bien... PasswordVault almacena usuarios y contraseñas, no? Me gusta que as contraseñas se pueden controlar como menciona @AlanArteche (revisar primero si el campo es de tipo Password), pero no veo manera de bloquear o validar que los usuarios o incluso llaves de acceso a bases de datos, authStrings, etc. se escriban en lugares indebidos.

**Comment by AlanArteche** [comment]
Sí, por ejemplo, revisar si el elemento de la página tiene alguna propiedad que nos permita saber que se trata de un password y que, si no lo tiene, no haga ninguna acción. Aquí hay un ejemplo de inicio de sesión en el portal de DHL donde vemos que el input de la contraseña tiene type password.

![image](https://user-images.githubusercontent.com/48565879/85418097-fd8d2000-b535-11ea-8850-0f273109c479.png)

También habría que considerar la posibilidad de que en los campos de usuario podrían introducir valores de contraseñas y volvería a perder sentido esta validación, sin embargo creo para solucionar esa parte lo mejor sería que Password Vault almacene exclusivamente contraseñas de acceso y ya no considere un usuario de acceso como un password, ya que, como podemos ver en cualquier portal, el usuario nunca se oculta. Si es necesario que en Password Vault sí se almacenen usuarios de accesos, otra solución sería tener 2 tipos de objetos diferentes y no sólo passwords.

![image](https://user-images.githubusercontent.com/48565879/85418530-7f7d4900-b536-11ea-8d22-2748b69808ac.png)

**Comment by AlanArteche** [comment]
Muestro que para la instrucción System Notify ya se realiza un bloqueo si se intenta utillizar con una variable tipo password. Procederé a realizar el mismo cambio para otras instrucciones cono DefineVariable y todo el Reader de Excel.

![image](https://user-images.githubusercontent.com/48565879/85587555-7f00b300-b607-11ea-9d6b-5c6e80294051.png)

**Comment by AlanArteche** [comment]
Lo mismo ahora funciona con DefineVariable y sus variantes para que no pudiera haber un truco de asignar valor de contraseña a otra variable y esa ya mostrarla con SystemNotify.

![image](https://user-images.githubusercontent.com/48565879/85594107-406df700-b60d-11ea-8202-6a0a35faf963.png)

**Comment by AlanArteche** [comment]
Se comenta que igualmente se bloquea el uso de contraseñas con el reader de Excel completo, ya que no veo un escenario donde escribir o utilizar contraseñas dentro de un Excel tega sentido.

![image](https://user-images.githubusercontent.com/48565879/85890095-52d56580-b7b2-11ea-9b55-d1be56fd8725.png)

**Comment by gantonioid** [comment]
Excepto cuando son libros protegidos, no?

**Comment by AlanArteche** [comment]
> Excepto cuando son libros protegidos, no?

Hmmm, no sé si en el reader se revisa si es libro protegido o no, pero en general no se pueda, sin excepeciones.
