### ISSUE TITLE
agregar save as a ReadMail

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#86]
tenemos calendarizado en azure, un proceso calendarizado en azure que obtiene correos con la instrucción
Mail ReadMailNew and get "sender" from the folder "Bandeja de entrada" that fulfills the filter "Archivos de rastro para HEB" in the "subject" and save as "Sender" finally move it to "Bandeja de Entrada"
sin embargo hay veces que no encuentra correos y marca error

```
30/06/2020 05:30:23 p. m. - Error in ReadMailNew and get "sender" from the folder "Bandeja de entrada" that fulfills the filter "Archivos de rastro para HEB" in the "subject" and save as "Sender" finally move it to "Bandeja de Entrada" : 
No emails found
30/06/2020 05:30:23 p. m. - Mail ReadMailNew and get "sender" from the folder "Bandeja de entrada" that fulfills the filter "Archivos de rastro para HEB" in the "subject" and save as "Sender" finally move it to "Bandeja de Entrada" : Error
30/06/2020 05:30:23 p. m. - Execution ended
```
 
es posible que la instrucción pueda guardar el valor en una variable, para en caso de ser nulo, poder contener el error en un if,?Algo así como
if (<<<correos>> -eq null)
y si es null que no haga nada y termine el ciclo

**Comment by ErlikC** [comment]
Cierro el ticket, con el comentario que dejaste, que encontraste el workarround con un try/catch.
