### ISSUE TITLE
ApplyFormat no aplica el formato a toda la columna

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#87]
```
Excel NewWB in {<<<home>>>Downloads} as {Conciliacion}
Excel LoadWBook "<<<home>>>Downloads/Conciliacion.xlsx" as libroConciliacion
Excel LoadWSheet libroConciliacion sheet_index 1 as resultadosTotales
Excel ApplyFormat from resultadosTotales in_column_index 1 format @

```
En este código solo me aplica el formato a la primera celda

**Comment by ErlikC** [comment]
De que modo quieres usar esa función?
Actualmente si tu hoja tiene en columna 1, solo 5 valores. Esos 5 valores los pone al formato indicado, mas abajo lo que se escriba posterior a esa instrucción no tendría formato.

**Comment by heber-solis** [comment]
Buen día, estaba interesado en aplicar el formato a toda la columna, ya que en el pasado,hemos tenido problemas de que escribimos la información y  una vez que se aplica el formato, no lo respeta, y luego tenemos que vaciar la columna, aplicar el formato y luego escribir la información pero ya pude resolver el problema con un workaround, no sé si gustes cerrar el issue o tomar en consideración la propuesta de aplicar el formato a toda la columna
Saludos!

**Comment by ErlikC** [comment]
Hola Heber, ya tengo el cambio listo.

**Comment by heber-solis** [comment]
Hola Erlik, me lo mandas porfa para checarlo?  se cambió la sintaxis normal? es que estoy trabajando en la cuenta de eva, por que mi usuario de red no tiene permisos, y usé  esto
Excel ApplyFormat from resultadosTotales in_column_index 3 format Number
y me marcó esto
03/07/2020 14:40:42 - Unable to set the NumberFormat property of the Range class
03/07/2020 14:40:42 - Error message:    at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at Microsoft.Office.Interop.Excel.Range.set_NumberFormat(Object )
   at ExcelReader.ExcelExecute.ApplyFormat(String action) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 23890
03/07/2020 14:40:42 - Error message: Unable to set the NumberFormat property of the Range class

supongo que es por el cambio que hiciste verdad?

**Comment by ErlikC** [comment]
Hola, no, aun no lo libero. Te lo acabo de asignar 20200703T0818
La sintaxis es así, adicional a lo que ya había
```
ApplyFormat from <worksheetKey> in_column_index <columnIndex> all format <format>
ApplyFormat from <worksheetKey> in_column "<columnName>" all format <format> 
```
