### ISSUE TITLE
Particionar resultset de DBReader

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#89]
Tenemos un proceso que regresa 1.6M de resultados, al escribirlo en excel nos regresa un error ya que excel tiene el limite de un poco más de un millón, sería posible particionar el result set en caso de ser mayor a un millón?

**Comment by gantonioid** [comment]
WOW...

Lo podrías particionar en tu query, no?
O también probar la función que lo escribe directamente en un CSV... aunque no sé qué pase si lo abres luego en Excel.

Qué vas a hacer después con ese resultado?

**Comment by heber-solis** [comment]
pues, a lo que sé de sql solo se me ocurre un select top 1040000 pero no sé como obtener el restante :( 

el problema es que el usuario pide escribirlo en 2 hojas, igual le planteo lo del csv si es que este no tiene el limite de 1040000 como el xlsx

pues nada, solo pegarlo en en un excel y ese excel subirlo a una ruta especifica jaja

**Comment by gantonioid** [comment]
y puedes subir un `csv` a esa ruta en vez de un `xlsx` ??

**Comment by heber-solis** [comment]
si si puedo subir csv a la ruta, intenté con el querytocsv y me sale el error de run out of memory :/

**Comment by gantonioid** [comment]
> pues, a lo que sé de sql solo se me ocurre un select top 1040000 pero no sé como obtener el restante :(

Se llama paginación, encontré este [link](https://www.sqlshack.com/pagination-in-sql-server/) que lo explica con ejemplos y todo
