### ISSUE TITLE
Permitir más atributos para localizar objetos (https://www.seleniumhq.org/docs/03_webdriver.jsp#locating-ui-elements-webelements)

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#9]
permitir la localizacion de objetos por:
id
clase
tag
por ejemplo

**Comment by gantonioid** [comment]
Ahora tenemos Magic syntax que podría ayudar a encontrar elementos sin inspeccionar el HTML de la página. Además, puedes hacer tus propias extensiones con un Evaluate de JavaScript.
