### ISSUE TITLE
Generar mas de una variable output en DB Reader?

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#90]
ejecutamos un script de BD que dura 20 min que genera varias tablas temporales y al final genera 3 resultados sería posible guardar cada resultado en una variable genérica algo así como output1, output2 ...outputX  y  poder manipular esas variables
ahorita ejecutamos el script 3 veces  y sobre cargamos el servidor con peticiones para obtener los datos

**Comment by gantonioid** [comment]
Me compartes una versión simplificada para analizarlo? es decir... un script mínimo que te genere un triple resultado como lo mencionas.

**Comment by rubenleal** [comment]
Va un ejemplo banal

--#########Obtiene Datos#########
--Inventario
Select * 
into #InventarioFinal
from inventario a 
join tomafisica b on a.ID=b.ID

--Ventas
Select * 
into #VentasFinal
from ventas a 
join tiendacluster b on a.ID=b.ID

--Venta Promedio Diaria
Select * 
into #VPD
from #VentasFinal a 
join VentaUltimasSemanas b on a.ID=b.ID

--#########Resultados#########

--Obtiene Artículos con Huecos Sin Existencia
select *
from #VPD a 
join #InventarioFinal b on a.ID=b.ID
join ajustes c on a.ID=c.ID
where a.VPD13>10 and HSE=1

--Obtiene Artículos con Huecos Con Existencia
select *
from #VPD a 
join #InventarioFinal b on a.ID=b.ID
join ajustes c on a.ID=c.ID
where a.VPD13>10 and HCE=1

--Genera sugerido de pedido en base a inventario y ventas
select *
from #VentasFinal a 
join #InventarioFinal b on a.ID=b.ID
Where Inventario<venta

**Comment by gantonioid** [comment]
@heber-solis Te envié la `v.20200731T0711`.

En ella verás que cada "resultado" se agrega a tus variables, concatenando un índice consecutivo
Ejemplo:
Dado este script SQL más sencillo
```
Select Top(50) *
from [dbo].[Plants];

Select TOP(50) *
from [dbo].[Persons]
where FirstName = 'Antonio';
```

la instrucción FRIDA
`DB RunOutputQuery {dbOut.txt} in {brasil} as {queryResult}`

arroja como resultado las variables:

1. queryResult  (tabla Plants)
2. query_field_names  (encabezados Plants)
3. queryResult2  (tabla Persons)
4. query_field_names2  (encabezados Persons)

Cabe mencionar que es más probable caer en problemas de memoria en un Turing local para resultados muy grandes, dado que ahora se almacenan más variables en cada **RunOutputQuery**

### Nota:
Esto se liberó exclusivamente para SQL_SERVER por el momento. Si se requiere en otro DB_TYPE, lo pueden solicitar.

**Comment by gantonioid** [comment]
@heber-solis me avisas si se resolvió para poder cerrar el ticket

**Comment by heber-solis** [comment]
si funciona muchas gracias!
