### ISSUE TITLE
Habilitar ciclo while?

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#91]
sería posible adicionar el ciclo while para facilitar la ejecución en algunos casos, tenemos el siguiente escenario

hay un script que barre 65 proyectos en una tabla, cada proyecto se tarda al rededor de 5 minutos y si algo falla, el script tiene que volver a barrer los 65 proyectos, sería posible habilitar el ciclo while para que se pueda dar el siguiente escenario

while (bandera=no procesado) {
barra solamente los que no fueron procesados
}

**Comment by gantonioid** [comment]
Tengo una propuesta para este tema. te mando un update `20200817T0715`

**Comment by gantonioid** [comment]
La sintaxis es igual que en el if. El while puede resolver expresiones lógicas simples 1 a 1, del tipo <, <=, ==, !=, >, >=
```
while (<<<bandera>>> == "no procesado") {
...tu código
}
```
