### ISSUE TITLE
función para solo habilitar los filtros

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#92]
Actualmente la función de applyfilter, aplica el filtro de acuerdo a un criterio, se puede agregar una función para solo activar los filtros en el top row?

**Comment by ErlikC** [comment]
Hola Heber.
Te sirve usar esta función de esta manera?
`Excel ApplyFilterStartAt to the worksheet {WS} start at row {1} to the column with the index {1} with the criteria "<>TextoInexistente"
`
Lo que hace es mostrar todo lo que no sea "textoInexistente", es decir todo. Claro el texto que busques puede cambiarse por algo mas apropiado, si gustas.

**Comment by heber-solis** [comment]
Hola Erlik, usé esta función
`Excel ApplyFilterStartAt to the worksheet {ResultadosQuery2} start at row {1} to the column with the index {<<<contadorFiltros>>>} with the criteria "prueba"`
y lo que hizo fue ponerme el excel en blanco, por que no hay celdas con el texto prueba, no sé si lo que me falta es el <> que tu tienes?

**Comment by ErlikC** [comment]
Es correcto. Hace falta <>

**Comment by heber-solis** [comment]
si funcionó, muchas gracias Erlik! :D

**Comment by heber-solis** [comment]
buen día, el fix que me mencionó Erlik, me está marcando error ahora

```
Excel ApplyFilterStartAt to the worksheet {ICSheet} start at row {1} to the column with the index {1} with the criteria "<>prueba": Running 

03/08/2020 11:37:58 - Error message: at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData) 

 at Microsoft.Office.Interop.Excel.Range.AutoFilter(Object Field, Object Criteria1, XlAutoFilterOperator Operator, Object Criteria2, Object VisibleDropDown) 

 at ExcelReader.ExcelExecute.ApplyFilterStartAt(String action) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 5587 

03/08/2020 11:37:58 - Error message: _AutoFilter method of Range class failed
```

**Comment by heber-solis** [comment]
no sé que pasó jaja, hoy corrió bien el script, no cambié nada :/

**Comment by gantonioid** [comment]
Este error ha coincidido en ocasiones, con que la hoja ya tiene filtros activos... Coméntanos si los problemas regresan.
