### ISSUE TITLE
Procentajes (%) en Arrays son cambiados a corchetes ([)

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#93]
Turing Version: 20200702T0347

DefineVariable type "string" as "URLSitioTI" with the value "https://hebmex1.sharepoint.com/sites/DocumentosTI/Scorecard%20TI/Forms/AllItems.aspx?viewid=65165e6b%2Dcd97%2D47d9%2D8f6a%2Db1fdaa31538a&id=%2Fsites%2FDocumentosTI%2FScorecard%20TI%2FEstatus%20de%20proyectos%20TI"
AddToList "Paginas" value "<<<URLSitioTI>>>"
SystemNotify Type "Validation" with message "<<<Paginas[0]>>>"

![image](https://user-images.githubusercontent.com/54807268/87947542-1de2c880-ca69-11ea-85cf-f6ed17845034.png)

**Comment by ErlikC** [comment]
Si habia un bug, ya lo tengo resuelto.
Te mando la versión?

**Comment by rubenleal** [comment]
@ErlikC máname el update por favor, gracias.

**Comment by ErlikC** [comment]
Listo, ya te envié el update.
