### ISSUE TITLE
Error message: Index was outside the bounds of the array al leer una columna

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#94]
Estoy tratando de leer una columna pero al hacerlo me marca este error

```
21/07/2020 12:12:19 - Excel ReadColumn from the worksheet {foliosSheet1} with the column index {13} start_at {2} and save its value as {colVoucher} visible: Running
21/07/2020 12:12:19 - Error message:    at ExcelReader.ExcelExecute.ReadColumn(String action) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 7743
21/07/2020 12:12:19 - Error message: Index was outside the bounds of the array
```

pero antes de eso escribo los datos y si los escribe correctamente

```
21/07/2020 12:12:15 - Excel WriteVariableValue {listvoucherPMM} in {foliosSheet1} start_at_row {2} start_at_column {13}: Running
21/07/2020 12:12:16 - Excel WriteVariableValue {listvoucherPMM} in {foliosSheet1} start_at_row {2} start_at_column {13} : Success

```
adjunto excel que uso. Gracias por el apoyo
[1Resumen_de_Folios_de_Recepcion.xlsx](https://github.com/FridaSupport/CognitiveTestingMX/files/4955540/1Resumen_de_Folios_de_Recepcion.xlsx)

**Comment by ErlikC** [comment]
Tiene problemas la función. En este caso lo que esta provocando el error es la columna vacia. Voy a ver como corregir esto
![image](https://user-images.githubusercontent.com/60276982/88112829-3f7da600-cb76-11ea-9785-55be815903df.png)

**Comment by heber-solis** [comment]
muchas gracias Erlik!

**Comment by ErlikC** [comment]
Listo. Ya hice la corrección
Dejo explicación del comportamiento de CopyColumn con visible, para futuros tickets.
Tenemos un archivo con estos posibles escenarios.
![image](https://user-images.githubusercontent.com/60276982/88213577-87580800-cc1e-11ea-8bdd-d69683e1a579.png)
La columna E esta escondida, y las filas 6 y 7 tambien, es decir.
![image](https://user-images.githubusercontent.com/60276982/88213701-b40c1f80-cc1e-11ea-8291-8c8e9cfc09b0.png)
Sobre eso hice pruebas y esto es lo que se debe esperar según la región que caiga.


`Excel ReadColumn from the worksheet {WS} with the column index   {2} start_at {2} and save its value as {colBuscada} visible`
**Zona A.** trae 9 valores visibles de Columna B, por que se inicio en fila 2 y no   toma en cuenta filas escondidas.
`Excel   ReadColumn from the worksheet {WS} with the column index {7} start_at {2} and   save its value as {colBuscada} visible`
**Zona B.** trae 9 valores visibles de Columna G, por que se inicio en fila 2 y no   toma en cuenta filas escondidas.
`Excel   ReadColumn from the worksheet {WS} with the column index {2} start_at {9} and   save its value as {colBuscada} visible`
**Zona C.** trae 2 valores visibles de Columna B, por que se inicio en fila 9 y no   toma en cuenta filas escondidas.
`Excel   ReadColumn from the worksheet {WS} with the column index {7} start_at {9} and   save its value as {colBuscada} visible`
**Zona D.** trae 2 valores visibles de Columna G, por que se inicio en fila 9 y no   toma en cuenta filas escondidas.
`Excel   ReadColumn from the worksheet {WS} with the column index {5} start_at {1} and   save its value as {colBuscada} visible`
**Zona E.** Crea variable sin contenido, por que es una columna no visible. Se   muestra en log que era columna vacía.  
**Zona F.** No se puede caer en este escenario, por que al leer las filas, solo trae lo que sea visible.

**Comment by heber-solis** [comment]
aaa ok entonces, cuenta de acuerdo a las visibles y por eso no me encuentra la 13 por que, la 13 (visible) está fuera del rango usado en el excel, entonces debo de contar de acuerdo a las columnas visibles, cierto? 

muchas gracias Erlik! 👍

**Comment by ErlikC** [comment]
Ah no, para que no haya complicaciones en las columnas, quedo tal cual, pero si hay columnas escondidas, te regresa una lista vacia.
En las filas ahí si va a llegar de acuerdo a lo que esta visible.
Ahorita te mando el update.

**Comment by ErlikC** [comment]
Listo, ya te mande la versión 20200722T0649.
