### ISSUE TITLE
Error al ejecutar Excel Save and Close

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#95]
al intentar hacer un save and close ocurre este error

```
Excel Save Consolidado and close: Running
28/07/2020 11:10:43 - Error message:    at Microsoft.Office.Interop.Excel._Worksheet.get_Parent()
   at ExcelReader.ExcelExecute.<>c__DisplayClass82_0.<SaveWB>b__0(KeyValuePair`2 p) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 9456
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ExcelReader.ExcelExecute.SaveWB(String action) in C:\Users\erlik.corona\source\repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 9456
28/07/2020 11:10:43 - Excel Save Consolidado and close : Success
```
el id del proceso es 6383625

**Comment by ErlikC** [comment]
Existen problemas de referencias, lo como lo explicamos en directo, esto es lo que ocurre.
```
...
Excel NewWs in Consolidado as FormatoCancelaciones
Excel LoadWSheet Consolidado  sheet "FormatoCancelaciones" as Formato
...
Excel RemoveSheets from Consolidado sheet Formato
...
Excel Save Consolidado and close
```

Se crea una hoja FormatoCancelaciones, que va a tener de llave FormatoCancelaciones, luego se carga nuevamente la hoja, pero con llave Formato. Es decir ambas llaves apuntan a la misma hoja de Excel.
Mas adelante en el script se borra la hoja usando la llave Formato. Esto borra la llave también. Pero no hace nada respecto a la otra llave que ahora apunta a nada, por que ya se borro esa hoja.

Al cerrar un libro, el procedimiento busca todas las llaves con hojas pertenecientes a ese libro, es decir busca en su propiedad "Parent", las quita del listado (o memoria) y después cierra el libro.
La llave que quedo en el limbo provoca error y ya no puede llegar al punto en donde cierra el libro.

El punto que hay que cuidar es si se utiliza la instrucción RemoveSheets y si se borra por llave o nombre de la hoja.
Voy a poner filtros en código, para evitar el mensaje de error y que no cierre excel, pero inicialmente el problema se puede resolver cuidando el tema de llaves repetidas para una misma hoja.

**Comment by ErlikC** [comment]
Podemos cerrar el ticket?

**Comment by heber-solis** [comment]
si muchas gracias Erlik!
