### ISSUE TITLE
Paso de variable de PowerShell a FRIDA afecta otra variable "parecida"

### ISSUE THREAD

**Issue by rubenleal** [FridaSupport/CognitiveTestingMX#96]
_Process ID: 1428197629
Turing Version: 20200728T0940_

**Se afecta variable QR cuando solo debería afectarse OpinionQR desde el PowerShell**
![image](https://user-images.githubusercontent.com/54807268/89046808-1d70ea00-d313-11ea-8501-18c43d0d3023.png)

**Código FRIDA:**
DefineVariable type "string" as "QR"
DefineVariable type "string" as "OpinionQR"
RunPowerShell fecha.txt

**Código PowerShell:**
$result = "Esto es una prueba"
Write-Output "OpinionQR : $result"

**Log:**
31/07/2020 09:40:54 a. m. - Se actualizo la variable : 
Var Name : QR
Value : OpinionEsto es una prueba
31/07/2020 09:40:54 a. m. - Se actualizo la variable : 
Var Name : OpinionQR
Value : Esto es una prueba
31/07/2020 09:40:54 a. m. - RunPowerShell fecha.txt : Success
31/07/2020 09:40:54 a. m. - Execution ended

**Comment by gantonioid** [comment]
Hola Rubén

Te mandé la `v.20200731T0502` para solucionar este problema. Quedo atento a tus comentarios.

**Comment by rubenleal** [comment]
Gracias Toño, corrí el mismo código y no me devolvió valores para ninguna variable después del PowerShell. Creí que quizás solo era solo en el log y coloqué un SystemNotify, pero la variable aparece como <<<OpinionQR>>>

![image](https://user-images.githubusercontent.com/54807268/89060737-210f6b80-d329-11ea-8e9a-bce161b1bb28.png)

**Comment by gantonioid** [comment]
Lo siento, me faltó un Trim()... va de nuevo en `v.20200731T0551`

**Comment by rubenleal** [comment]
Funcionando, muchas gracias!
![image](https://user-images.githubusercontent.com/54807268/89065113-cb3ec180-d330-11ea-9cab-ebb84819ba2f.png)
