### ISSUE TITLE
No se puede utilizar la función Web2 InsertValue

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CognitiveTestingMX#97]
Esto sucede cuando se graba un script y contiene escrita la función **Web2 InsertValue** en el editor de texto de Cognitive Testing.

Al salir y entrar del editor de texto la función cambia su sintaxis por **Web2 Insert Valuevalue**

Ejemplo.

![image](https://user-images.githubusercontent.com/56734739/89193294-66bb7680-d56b-11ea-9b02-5bc8c5640bdd.png)

**Comment by gantonioid** [comment]
@jorgebibarra nos ayudas?

**Comment by jorgebibarra** [comment]
Claro!

**Comment by gantonioid** [comment]
@jorgebibarra @raulhgit se resolvió?Podemos cerrar?

**Comment by raulhgit** [comment]
Aun no lo he validado, durante el día haré la prueba. Gracias por el seguimiento

**Comment by gantonioid** [comment]
Cierro el ticket, pero puedes comentarnos si necesitas ayuda.
