### ISSUE TITLE
Excel no me toma la ultima celda

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#98]
No me toma el ultimo dato en un excel,  no sé por que esté pasando eso :(

13/08/2020 16:45:46 - Excel Write "9999980009916.eps" in hojaRenombrado cell A57 : Success

Excel GetSpecial lastRow from hojaRenombrado and save as LRow: Running
13/08/2020 16:45:48 - Se agrego una nueva variable : 
Var Name : LRow
Value : 56

ya intenté  guardar antes del get special y cerrar el excel y volverlo a abrir,

**Comment by gantonioid** [comment]
Tienes una fila vacía al principio de la hoja?

Esta instrucción asume que la información empieza en A1

**Comment by heber-solis** [comment]
sii la A1 está vacía, no sabía eso jeje muchas gracias!
