### ISSUE TITLE
agregar hostname a la info que regresa el log

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#99]
es posible agregar el hostname a la info que regresa el log en el principio? esto por que corremos los procesos mediante azure y nos ayudaría a visualizar en qué maquina corrió de forma más rápida

- Process Name: test5
 - Process ID: 979424187
- Turing Version: 20200731T0711
 Execution started: No Headless

**Comment by gantonioid** [comment]
Ya está el update, quieres que te lo mandemos o esperamos al siguiente release?
